Stand-With-Crypto/swc-web

- src/actions/actionCreateUserActionLiveEvent.ts
Update live event server action to use new rate limiter util `getRequestRateLimiter`
**UI changes**
None 
type=routine 
risk=low 
impact=sev5
> [chore] Update live event server action to use new rate limiter util

- src/components/app/footer/index.tsx
Update disclaimer
**UI changes**
_Web_
type=routine 
risk=low 
impact=sev5
> [trivial] Update disclaimer

- .github/workflows/pr.yml
- src/components/app/pageContribute/index.tsx
- src/components/app/userActionFormVoterRegistration/sections/claimNft.tsx
- src/components/ui/button/index.tsx
- src/components/ui/iframeWithLoadingState.tsx
- src/components/ui/userActionTweetLink.tsx
- src/utils/web/createTweetLink.ts
Updates to the contribution page based off stakeholder feedback
type=routine 
risk=low 
impact=sev5
> contributing page updates

- src/components/app/userActionFormNFTMint/sections/transactionWatch.tsx
**UI changes**
_Web_
| old screenshot | new screenshot |
_Mobile Web_
| old screenshot | new screenshot |
type=routine 
risk=low 
impact=sev5
> fix: remove paralel execution on nft mint action creation

- src/components/app/pagePoliticianDetails/scoreExplainer.tsx
**UI changes**
_Web_
|
| ![image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/12b48ddb-bf60-4191-b674-170f6d8a57b2) |
_Mobile Web_
| ![image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/2e8a3e92-9605-4151-9b76-70fdc788561d) | ![image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/02c38eb6-9054-4b58-9d76-c09a3d8f0463) |
type=routine 
risk=low 
impact=sev5
> dtsi cta tweaks

- src/components/app/userActionFormSuccessScreen/userActionFormSuccessScreenMainCTA.tsx
**UI changes**
_Web_
| old screenshot | new screenshot |
_Mobile Web_
| old screenshot | new screenshot |
type=routine 
risk=low 
impact=sev5
> fix: show login cta only on actions that have nfts

- src/components/app/pagePrivacyPolicy/index.tsx
closes Stand-With-Crypto/swc-internal#4
type=routine 
risk=low 
impact=sev4
> feat: change copy of privacy policy page

- src/components/app/dtsiClientPersonDataTable/columns.tsx
- src/components/app/dtsiClientPersonDataTable/dataTable.tsx
- src/components/app/dtsiClientPersonDataTable/globalFiltersUtils.tsx
- src/components/app/dtsiClientPersonDataTable/index.tsx
Allow user to click anywhere on the politician table row to navigate to politician page
**UI changes**
None
type=routine 
risk=low 
impact=sev5
> [feat] Make full row in the politician table clickable

- src/inngest/functions/backfillNFT/logic.ts
closes https://github.com/Stand-With-Crypto/swc-web/issues/653
Fixed a comparison issue when checking if an action type has a NFT associated 
*
type=routine 
risk=low 
impact=sev5
> fixed issued with backfill nft

- src/components/app/pagePoliticianDetails/index.tsx
- src/data/dtsi/queries/queryDTSIPersonDetails/dtsiPersonDetailsQueryString.ts
closes 
fixes 
**UI changes**
See role text
_Web_
| ![image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/9c098359-3558-41f5-82fa-4cc1ce8b1267) | ![image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/1bbad5d9-ef18-4e69-9772-269d0ffd4d0a) |
type=routine 
risk=low 
impact=sev5
> ensure we are consistent about how we determine the primary role of a person

- src/components/app/pagePrivacyPolicy/index.tsx
closes https://github.com/Stand-With-Crypto/swc-internal/issues/5
Small update to the privacy policy 
**UI changes**
Just text change
type=routine 
risk=low 
impact=sev5
> Update to privacy policy

- src/components/app/authentication/thirdwebLoginContent.tsx
see https://github.com/orgs/Stand-With-Crypto/projects/1/views/10?pane=issue&itemId=57393929
type=routine 
risk=low 
impact=sev5
> turn off prepopulating email for thirdweb login until #712 is addressed

- next-sitemap.config.js
Remove unneeded pages from our sitemap
type=routine 
risk=low 
impact=sev5
> general sitemap cleanup

- next.config.js
- src/app/[locale]/layout.tsx
- src/components/app/overrideGlobalLocalStorage.tsx
closes https://github.com/Stand-With-Crypto/swc-web/issues/733
See issue for QA notes
type=routine 
risk=low 
impact=sev5
> dont crash app when browser errors on localstorage

- .vscode/settings.json
- src/app/[locale]/internal/page.tsx
- src/app/[locale]/internal/user-experiments/page.tsx
- src/hooks/useCurrentUserAddress.ts
- src/hooks/useLocalUser.ts
- src/utils/server/serverAnalytics/serverAnalytics.ts
- src/utils/server/serverLocalUser.ts
- src/utils/shared/experiments.test.ts
- src/utils/shared/experiments.ts
- src/utils/shared/localUser.ts
- src/utils/web/clientAnalytics.ts
- src/utils/web/clientExperiments.ts
- src/utils/web/clientLocalUser.ts
closes https://github.com/Stand-With-Crypto/swc-web/issues/143
See the experiments.ts file for commentary/context.
type=routine 
risk=low 
impact=sev5
> support a/b testing via mixpanel

- src/components/ui/combobox.tsx
- src/components/ui/command.tsx
- src/components/ui/googlePlacesSelect/index.tsx
There are a number of buggy issues with our address autocomplete on mobile. See comments for addressed bugs.
| ![image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/8c4a64da-a87a-4c1d-b6d8-fd9d0e8b90cb) | ![image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/f7280935-fa50-47c5-911d-82151e9c1d78) |
type=routine 
risk=low 
impact=sev5
> various UI tweaks to clean up the way we do searchable address inputs on mobile

- src/app/api/public/frames/register-to-vote/image/[index]/route.tsx
relates to #739 
This is a small PR to fix a duplicated `"and check"` string and also change the 350k count to 400k.
| ![image](https://github.com/Stand-With-Crypto/swc-web/assets/135282747/88af5824-3918-41e1-b753-19f280004eb2) | ![image](https://github.com/Stand-With-Crypto/swc-web/assets/135282747/33bd096a-e8f1-42ef-bfee-7d5f5dfa5c44) |
| ![image](https://github.com/Stand-With-Crypto/swc-web/assets/135282747/720b0125-8d37-4059-8aca-6ef6817587bd) | ![image](https://github.com/Stand-With-Crypto/swc-web/assets/135282747/05d47130-62c8-4e8c-9971-5a9521c248df) |
No PlanetScale schema updates.
N/A
type=routine 
risk=low 
impact=sev5
> [bug] fix typos in "Register to Vote" Farcaster Frame

- src/app/[locale]/partners/page.tsx
- src/app/api/public/frames/register-to-vote/image/[index]/route.tsx
- src/components/app/pageContribute/index.tsx
- src/components/app/pageHome/index.tsx
- src/components/app/userActionRowCTA/constants.tsx
- src/components/ui/userActionTweetLink.tsx
400k advocates 🍾 
type=routine 
risk=low 
impact=sev5
> update hardcoded advocate count to 400k

- cypress/e2e/8-page-politician-details.cy.ts
- next.config.js
Adds a vanity url for the politician questionnaire answers
> Feat: adds questionnaire vanity url

- src/components/app/pagePoliticianDetails/index.tsx
- src/components/app/pagePoliticianDetails/questionnaireAccordion.tsx
- src/utils/server/builderIO/swc-questionnaire.ts
- src/utils/shared/getSWCQuestionnaire.ts
Removed server related imports on client components
> fix: trying to use server envs on client

- src/components/app/pagePoliticianDetails/questionnaireAccordion.tsx
Show "not answered" for questions that the politician didn't answer in the questionnaire.
> Show not answered questions on questionnaire accordion

- cypress/e2e/6-donation-card-redirect.cy.ts
- src/components/app/navbar/index.tsx
- src/components/app/pageDonate/donateButton.tsx
- src/components/app/userActionRowCTA/constants.tsx
- src/utils/shared/activeUserAction.ts
- src/utils/shared/urlsDeeplinkUserActions.tsx
- src/utils/web/userActionUtils.ts
Re-enable donations that were turned off in https://github.com/Stand-With-Crypto/swc-web/commit/69523fa778f885c75b606bc760a2b1d51c62e92d
> turn swc donations back on

- .eslintrc.js
- src/app/api/public/frames/register-to-vote/route.tsx
- src/app/api/public/frames/register-to-vote/tx/route.tsx
- src/components/app/pagePoliticianDetails/questionnaireAccordion.tsx
> enforce convention for when/where we use curly brackets

- prisma/schema.prisma
- src/bin/seed/seedLocalDb.ts
- src/clientModels/clientUserAction/clientUserAction.ts
- src/components/app/recentActivityRow/activityAvatar.tsx
- src/components/app/recentActivityRow/variantRecentActivityRow.tsx
- src/data/recentActivity/getPublicRecentActivity.ts
- src/mocks/models/mockUserActionTweetAtPerson.ts
- src/utils/server/nft/claimNFT.ts
- src/utils/shared/userActionCampaigns.ts
This PR creates a new user action named tweet at person and it's corresponding model.
[PlanetScale deploy to testing branch PR](https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/20)
> Creates UserActionTweetAtPerson model

- src/utils/server/getGooglePlaceIdFromAddress.ts
closes #859 
fixes [PROD-SWC-WEB-1HQ](https://stand-with-crypto.sentry.io/issues/5051139135/?referrer=github_integration)
> fix: ignore ZERO_RESULTS status for places api errors

- src/components/app/userActionFormCallCongressperson/sections/intro.tsx
- src/components/app/userActionFormCallCongressperson/sections/suggestedScript.tsx
- src/components/app/userActionFormEmailCongressperson/getDefaultText.ts
Copy tweaks in prep for FIT21 activations
> copy updates for email/call flows

- src/components/app/navbar/index.tsx
> Add fit21 banner

- src/components/app/pageEndorsedCandidates/index.tsx
- src/components/app/userActionFormCallCongressperson/sections/suggestedScript.tsx
Fixes the call button being cutoff on devices with small display height
> fix: call button being cut off

- src/components/app/navbar/index.tsx
- src/components/app/userActionFormCallCongressperson/sections/intro.tsx
- src/components/app/userActionFormCallCongressperson/sections/suggestedScript.tsx
- src/components/app/userActionFormEmailCongressperson/getDefaultText.ts
> Copy changes for call and email actions

- src/utils/server/builderIO/swc-questionnaire.ts
closes #835 
Added p-retry for builder-io request so that it's going to retry the request 3 times before throwing an error. I added a timeout for 5 seconds to try to have enough time so that the builder-io service is able to accept new requests before retries.
> feat: adds builder-io requests retry

- src/components/app/userActionFormNFTMint/sections/checkout/index.tsx
- src/components/app/userActionFormNFTMint/sections/intro.tsx
- src/utils/web/nft.ts
> feat: add local metadata for nft mint action

- next.config.js
This PR adds a redirect for pizza day deep link
> Adds pizza day redirect

- src/components/app/userActionFormTweetAtPerson/sessions/tweet.tsx
> new copy for pizza day tweets

- src/components/app/userActionFormTweetAtPerson/sessions/tweet.tsx
Changed default tweet pizza day copy
> Changes default pizza tweet message

- next.config.js
closes 
fixes PROD-SWC-WEB-1WS
> Redirect old doc url to new one

- src/components/app/navbar/index.tsx
- src/components/app/pageHome/index.tsx
- src/components/ui/badge.tsx
Add post-FIT21 CTA on homepage and remove FIT21 banner.
> post-FIT21 CTA & remove FIT21 banner

- src/app/api/inngest/route.ts
- src/inngest/functions/backfillDonationAction/index.ts
- src/inngest/functions/backfillDonationAction/logic.ts
This PR creates a new Inngest function to backfill donation action for users that have a discrepancy between totalDonationAmountUsd and mintNft costs.
> Creates donation action backfill function

- src/utils/server/coinbaseCommerce/storePaymentRequest.ts
This PR adds await on createUserActionDonation call.
> Adds missing await statement

- src/components/app/userActionFormEmailCongressperson/index.tsx
- src/components/app/userActionFormEmailCongressperson/skeleton.tsx
> fix: capitalize email action title

- src/components/app/pageLocationUnitedStates/index.tsx
- src/components/app/pageLocationUnitedStates/organizePeople.tsx
- src/data/dtsi/queries/queryDTSILocationStateSpecificInformation.ts
- src/data/dtsi/queries/queryDTSILocationUnitedStatesInformation.ts
- src/utils/shared/locationSpecificPages.ts
> tweak key races page

- src/actions/actionUpdateUserHasOptedInSMS.ts
- src/components/app/footer/index.tsx
- src/components/app/pageHome/heroCTA.tsx
- src/components/app/pageHome/index.tsx
- src/components/app/smsOptInCTA.tsx
- src/components/app/smsOptInForm.tsx
- src/validation/forms/zodUpdateUserHasOptedInToSMS.ts
closes #726 
Show a SMS opt in CTA to users that have not provided a phone number
> SMS Homepage Optimizations

- src/components/app/navbar/navbarLoggedInButton/index.tsx
- src/hooks/useSession.ts
- src/utils/shared/eventListeners.ts
closes #849 
This PR changes the logout experience to happen faster than the current experience.
I replaced router.refresh with window.location.reload because the main issue that was causing the logout to take so long was that router.refresh was refreshing a lot of stuff like re-rendering server-components, refetching requests and so on(you can check the entire list [here](https://nextjs.org/docs/app/api-reference/functions/use-router)). It also maintained client state and we don't want that to happen in NavBar component and prob on the entire app. Replacing to window.location.reload made everything much smoother and faster.
Because of that, the only real change needed for this PR would be to change the router.refresh to window.location.reload, but I decided to add a CustomEvent to be …
> Improves Logout User Experience

- cypress/e2e/11-action-mint-your-supporter-nft.cy.ts
- cypress/fixture/mocks.ts
- src/app/[locale]/topLevelClientLogic.tsx
- src/components/app/updateUserProfileForm/step1/control.tsx
- src/components/app/updateUserProfileForm/step1/variant.tsx
- src/components/app/userActionFormNFTMint/sections/intro.tsx
#569
closes 
fixes 
Introduced LocalWallet for cypresses tests to mock a temporary authentication and added a test flow for the mint nft user action
> test: add mint nft action cypress

- src/hooks/useHandlePageError.ts
This PR changes the logic to try to capture the outlook error.
> Tries to capture outlook error

- src/bin/utils/sendCNNemail.ts
- src/utils/server/capitolCanary/campaigns.ts
This PR creates a new script to test sending CNN emails. This is related to the task #959
> WIP | Creates a CNN email testing script

- src/app/api/inngest/route.ts
- src/bin/utils/sendCNNemail.ts
- src/inngest/functions/testCNNEmail/logic.ts
- src/inngest/functions/testCNNEmail/testCNNEmail.ts
- src/utils/server/capitolCanary/campaigns.ts
This PR creates a new inngest function to test sending emails to CNN
This is also related to #959
> Creates send CNN email test

- cypress/e2e/07-action-voter-registration.cy.ts
- cypress/e2e/11-action-mint-your-supporter-nft.cy.ts
- cypress/e2e/12-action-join-stand-with-crypto.cy.ts
- cypress/support/commands.ts
- src/components/app/navbar/index.tsx
- src/components/app/navbar/navbarLoggedInButton/index.tsx
- src/components/app/updateUserProfileForm/step1/control.tsx
- src/components/app/updateUserProfileForm/step1/variant.tsx
#955
closes 
fixes 
- adds testing with login, logout and asserting it only asks for profile update once
> test: add cypress for join with crypto flow

- src/hooks/useHandlePageError.ts
> feat: improve global error page logs

- src/actions/actionCreateUserActionEmailCNN.ts
- src/app/[locale]/internal/user-action-deeplinks/page.tsx
- src/utils/shared/checkIfUserActionWithCampaignIsComplete.ts
- src/utils/shared/urlsDeeplinkUserActions.tsx
- src/utils/shared/userActionCampaigns.ts
closes #996 
This PR changes the CNN email address and also changes the logic in internal deeplink page to show up campaigns as well.
> CNN Email improvements

- prisma/schema.prisma
closes #574 
This PR implements all suggestions from PlanetScale
PlanetScale deploy request: https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/27
> Implements planetscale recommendations

- src/app/api/public/dtsi/all-people/route.ts
- src/data/dtsi/fetchDTSI.ts
- src/data/dtsi/queries/queryDTSIAllPeople.ts
Reverts Stand-With-Crypto/swc-web#1004
> Revert "Changes caching logic from route to fetch req in all dtsi api route"

- src/components/app/pageHome/topLevelMetrics.tsx
> Updates tooltip number style

- src/components/app/pageContribute/index.tsx
- src/components/app/pageHome/topLevelMetrics.tsx
- src/data/aggregations/getSumDonations.ts
> update donation numbers

- next.config.js
> Redirect /action/email-cnn to homepage

- prisma/schema.prisma
closes #900 
This PR adds some missing indexes to improve DB performance
Deploy request: https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/33
> Adds new indexes to improve performance

- src/components/app/updateUserProfileForm/step1/index.tsx
- src/components/app/updateUserProfileForm/step1/variant.tsx
- src/components/ui/experimentsTesting/index.ts
- src/utils/server/nft/mintPastActions.ts
- src/utils/shared/experiments.ts
closes [#67](https://github.com/Stand-With-Crypto/swc-internal/issues/67)
- Change experiment name
- Make all fields optional
- Make sure inexistent variant names don't break UI
> Modify update profile experiment

- prisma/schema.prisma
- src/mocks/models/mockAddress.ts
closes 
fixes 
[#774](https://github.com/Stand-With-Crypto/swc-web/issues/774)
- Added a new optional field to Address table called `usCongressionalDistrict`.
https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/35
> Add a new usCongressionalDistrict field to the address table

- src/components/app/navbar/index.tsx
closes #1049 
This PR creates a new top banner to inform users about the voting that will happen tomorrow around the SAB 121 veto override.
> Creates the `SAB 121 veto override` vote banner

- src/components/app/navbar/index.tsx
> Updates SAB 121 copy

- src/components/app/navbar/index.tsx
This PR removes the recently added SAB 121 banner on SWC
> Removes `SAB 121` banner

- src/app/[locale]/layout.tsx
- src/components/app/geoLocationDisclaimerBanner/geoLocationDisclaimerBanner.tsx
- src/utils/shared/urls/index.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1059
- adds disclaimer banner for Canada too alongside UK
> feat: add canada to the country banner disclaimer

- src/app/[locale]/page.tsx
- src/components/app/homepageDialogDeeplinkLayout.tsx
- src/components/app/pageAdvocatesHeatmap/advocateHeatmapActionList.tsx
- src/components/app/pageAdvocatesHeatmap/advocateHeatmapActionTooltip.tsx
- src/components/app/pageAdvocatesHeatmap/advocateHeatmapIcons.tsx
- src/components/app/pageAdvocatesHeatmap/advocateHeatmapOdometer.tsx
- src/components/app/pageAdvocatesHeatmap/advocatesHeatmap.tsx
- src/components/app/pageAdvocatesHeatmap/advocatesHeatmapPage.tsx
- src/components/app/pageAdvocatesHeatmap/advocatesHeatmapTooltip.tsx
- src/components/app/pageHome/delayedRecentActivity.tsx
- src/components/app/pageHome/index.tsx
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1053
> feat: introduce advocate map at home

- src/app/[locale]/page.tsx
- src/components/app/homepageDialogDeeplinkLayout.tsx
- src/components/app/pageAdvocatesHeatmap/advocateHeatmapActionList.tsx
- src/components/app/pageAdvocatesHeatmap/advocateHeatmapActionTooltip.tsx
- src/components/app/pageAdvocatesHeatmap/advocateHeatmapIcons.tsx
- src/components/app/pageAdvocatesHeatmap/advocateHeatmapOdometer.tsx
- src/components/app/pageAdvocatesHeatmap/advocatesHeatmap.tsx
- src/components/app/pageAdvocatesHeatmap/advocatesHeatmapPage.tsx
- src/components/app/pageAdvocatesHeatmap/advocatesHeatmapTooltip.tsx
- src/components/app/pageHome/delayedRecentActivity.tsx
- src/components/app/pageHome/index.tsx
Reverts Stand-With-Crypto/swc-web#1058
> Revert "feat: introduce advocate map at home"

- src/data/aggregations/getTotalAdvocatesPerState.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1080
fixes  https://stand-with-crypto.sentry.io/issues/5225253861/?project=4506490717470720&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0
- attempt to fix a very slow query by breaking down to each state
> refactor: adjust total advocates per state query

- src/data/aggregations/getTotalAdvocatesPerState.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1082
fixes
> refactor: rever to using group by on advocates per state query

- src/app/[locale]/(homepageDialogDeeplink)/action/share/layout.tsx
- src/app/[locale]/(homepageDialogDeeplink)/action/share/page.tsx
- src/components/app/userActionFormShareOnTwitter/sections/share.tsx
- src/components/app/userActionFormSuccessScreen/constants.ts
> fix: bugs found while testing swc home module on RN

- src/components/app/userActionFormCallCongressperson/sections/intro.tsx
- src/components/app/userActionFormCallCongressperson/sections/suggestedScript.tsx
- src/components/app/userActionFormEmailCongressperson/index.tsx
- src/hooks/useCongresspersonBillVote.ts
- src/utils/shared/constants.ts
Update Call flow copy post FIT21 passing and show copy based on congressperson vote on the bill.
Small change to the email form to make the useCongresspersonBillVote reusable
> Update call flow copy

- src/components/app/pageAdvocatesHeatmap/advocatesHeatmap.tsx
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1084
- reduces padding on the map when mobile landscape
> refactor: adjust map padding for mobile landscape devices

- src/hooks/useApiAdvocateMap.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1106
- we don't need the advocates per map information as lively as possible especially as it has such a large amount of data
> refactor: reduce time interval for advocate per state fetch

- src/components/app/recentActivityRow/variantRecentActivityRow.tsx
closes https://github.com/Stand-With-Crypto/swc-internal/issues/101
> Update text for Twitter action

- src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts
Inngest has a soft limit of 4MB for how much data it can return in each step. The get-addresses script surely was returning much more than this (100k rows that I estimate was about 15MB in data) and this may be the reason why the function was not working on production. This PR queries for each batch and updates it before querying for the next batch.
> fix: reduce inngest step returned data size

- src/inngest/functions/backfillFailedNFTCronJob/index.ts
> fix: add validation for no user on userAction

- src/inngest/functions/sms/backfillPhoneNumberValidation.ts
- src/inngest/functions/sms/backfillSMSStatusField.ts
- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
- src/inngest/functions/sms/utils/flagInvalidPhoneNumbers.ts
> fix: use user ID instead of phone number to update sms status field

- src/data/dtsi/queries/queryDTSILocationUnitedStatesInformation.ts
closes [#112](https://github.com/Stand-With-Crypto/swc-internal/issues/112)
> fix: update key races page

- src/inngest/functions/sms/backfillPhoneNumberValidation.ts
> fix: remove twilio validation

- src/utils/shared/locationSpecificPages.ts
> Remove Blake Masters from the endorsement page

- src/components/app/userActionFormNFTMint/useCheckoutController.ts
Replace thirdweb hook to ensure a valid wallet address and add Sentry logging
> Fix Thirdweb hook not returning an address

- next.config.js
> Add redirect to path being accessed and leading the user to 404

- src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts
- src/utils/shared/getCongressionalDistrictFromAddress.ts
- src/utils/shared/googleCivicInfo.ts
> Catch Civic API quota limit reached and fix congressional district backfill

- next.config.js
- src/components/app/userActionFormNFTMint/index.tsx
- src/hooks/useSendMintNFTTransaction.ts
Add thirdweb origin to our csp headers and replace thirdweb hook to ensure wallet address existence
> Update connect-src policy

- src/app/[locale]/(homepageDialogDeeplink)/action/become-member/page.tsx
- src/app/[locale]/profile/page.tsx
- src/components/app/pageUserProfile/index.tsx
- src/components/app/redirectToSignUp.ts
> Error page flashing before redirecting user to /action/sign-up

- package-lock.json
- package.json
> Upgrade thirdweb lib to latest version

- src/inngest/functions/airdropNFT/airdropNFT.tsx
closes #1151 
fixes [PROD-SWC-WEB-219](https://stand-with-crypto.sentry.io/issues/5508848344/?referrer=github_integration)
Added analytics flush call
> Add analytics.flush call

- src/utils/server/thirdweb/onLogin.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1176
> feat: add phone number sign in analytics in onLogin file

- src/components/app/pagePrivacyPolicy/index.tsx
> fix: update texting program section

- next.config.js
- src/inngest/functions/backfillSessionId/index.ts
> Fix: 404 page error

- src/components/app/pageHome/heroImage.tsx
- src/components/app/pageHome/index.tsx
Makes the entire hero image clickable
> Makes events hero image clickable

- src/components/app/userActionFormVoterRegistration/constants.ts
> Update Alaska link

- src/components/app/navbar/index.tsx
- src/components/app/pageHome/delayedRecentActivity.tsx
- src/components/app/pageHome/index.tsx
- src/utils/shared/getUserActionsProgress.ts
> Disable nft mint action

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
- src/inngest/functions/sms/utils/communicationJourney.ts
- src/inngest/functions/sms/utils/enqueueMessages.test.ts
- src/inngest/functions/sms/utils/enqueueMessages.ts
- src/inngest/functions/sms/utils/index.ts
> fix: send welcome and bulk text together to the same phone number

- prisma/schema.prisma
[#50](https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/50)
> feat: index phoneNumber field

- src/inngest/functions/backfillSessionId/index.ts
> fix: backfill session id inngest function

- src/components/app/userActionFormNFTMint/sections/checkout/index.tsx
> Add missing goToSection call

- src/components/app/pageHome/index.tsx
- src/utils/shared/getUserActionsProgress.ts
> Reenable nft mint

- src/inngest/functions/sms/backfillSMSStatusField.ts
- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
- src/inngest/functions/sms/utils/enqueueMessages.ts
- src/utils/server/sms/SendSMSError.ts
> fix: improve sms logging

- src/components/app/pagePrivacyPolicy/index.tsx
> Update privacy policy

- next.config.js
> Fix: signup not working

- src/components/app/pageEvents/components/eventsIntro.tsx
- src/components/app/pageEvents/components/eventsNearYou.tsx
- src/components/app/pageEvents/components/successfulEventSignupDialog.tsx
- tsconfig.json
Some changes and fixes on the Events page
Has to change target from `es5` to `es6` on tsconfig.json to be able to use .matchAll to iterate over all matches in the address string to get the valid US state code.
> Events page fast follows

- src/components/app/navbar/index.tsx
- src/components/app/pageHome/delayedRecentActivity.tsx
- src/components/app/pageHome/index.tsx
- src/utils/shared/getUserActionsProgress.ts
> fix: reenable donate action

- next.config.js
> feat: add az sms redirects

- src/utils/server/email/templates/reactivationReminder.tsx
- src/utils/server/email/templates/ui/keepUpTheFightSection.tsx
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1220
fixes
> style: adjust actions email template

- next.config.js
> fix: redirect

- next.config.js
> fix: second redirect

- next.config.js
> fix: group one redirect

- src/components/app/userActionFormNFTMint/useCheckoutController.ts
closes 
fixes 
Added a flag to avoid sending errors to Sentry. When a client opens the nft mint modal without being authenticated first, the `useGasFee` hook would fail due to not having any wallet address.
> Fix invalid address logs

- next.config.js
> feat: add 08/20 sms redirects

- src/middleware.ts
> Always update country code cookie

- sentry.client.config.ts
> chore: add capture console integration to sentry

- sentry.client.config.ts
> chore: remove capture console integration from sentry

- src/components/app/userActionFormNFTMint/useCheckoutController.ts
closes #1236 
This PR creates a protection to prevent the underflow error when passing a fraction to BigNumber.from function.
> Fix underflow error in gas fee estimation in mint nft flow

- package.json
- src/components/app/userActionFormVoterAttestation/index.tsx
- src/components/app/userActionRowCTA/constants.tsx
- src/hooks/useApiResponseForUserFullProfileInfo.tsx
This makes so the pledge and voter registration actions can be completed more than once.
Also this fixes an issue we are having where the address is not prefilled on login
> fix: address not auto populating on the pledge flow

- src/inngest/functions/backfillReactivation/index.tsx
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1251
fixes
> refactor: add limit and ordering

- cypress/e2e/07-action-voter-registration.cy.ts
- cypress/e2e/13-user-action-unavailable.cy.ts
- src/components/app/userActionFormNFTMint/sections/checkout/index.tsx
- src/components/app/userActionFormNFTMint/sections/checkout/quantityInput/index.tsx
- src/components/app/userActionFormNFTMint/sections/transactionWatch.tsx
- src/hooks/useSession.ts
- src/utils/server/ratelimit/throwIfRateLimited.ts
This PR fixes some issues related to query params login and nft mint
> Fix NFT bugs, E2E tests and general improvements

- src/components/app/pageEvents/components/eventCard.tsx
- src/components/app/pageEvents/components/eventDialogContent.tsx
- src/components/app/pageEvents/components/eventsMap.tsx
- src/components/app/pageEvents/components/stateEventsDialogContent.tsx
- src/inngest/functions/eventNotification/logic.ts
closes #1268
Fixes the following issues:
- Event card in all upcoming events is showing the date differently for each user because it is using the user timezone on new Date().
- State events dialog is not ordering the events by date.
- Ohio state tooltip in map view is wrapping the text.
> Some fixes on Events Page

- src/hooks/useSession.ts
> rollback useSession hook

- src/app/api/public/sendgrid/events/route.ts
- src/inngest/functions/backfillReactivation/index.tsx
- src/utils/server/email/constants.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1271
fixes
> refactor: add extra info when sending reactivation email

- next.config.js
> shortlink for swing state tour QR codes

- src/components/app/pageLocationRaceSpecific/index.tsx
- src/components/app/pageLocationStateSpecific/index.tsx
- src/components/app/pageLocationUnitedStates/index.tsx
- src/components/app/userActionRowCTA/constants.tsx
- src/utils/server/email/templates/common/constants.ts
- src/utils/server/email/templates/registerToVoteReminder.tsx
https://coinbase.slack.com/archives/C05L56L0Y9G/p1724358255998809?thread_ts=1724357097.218509&cid=C05L56L0Y9G
Please point out entry points I'm missing that need to be updated
> tweak voter registration language to encourage registered voters to confirm their status

- prisma/schema.prisma
- src/bin/seed/seedLocalDb.ts
- src/clientModels/clientUserAction/clientUserAction.ts
- src/clientModels/clientUserAction/sensitiveDataClientUserAction.ts
- src/components/app/recentActivityRow/activityAvatar.tsx
- src/components/app/recentActivityRow/variantRecentActivityRow.tsx
- src/data/recentActivity/getPublicRecentActivity.ts
- src/mocks/fakerUtils.ts
- src/mocks/models/mockUserActionViewKeyRaces.ts
- src/utils/server/nft/claimNFT.tsx
- src/utils/shared/userActionCampaigns.ts
> chore: add files needed for key_races action

- src/app/[locale]/(homepageDialogDeeplink)/action/sign-up/page.tsx
- src/app/[locale]/profile/page.tsx
- src/app/api/identified-user/full-profile-info/route.ts
- src/hooks/useSession.ts
- src/utils/server/authentication/appRouterGetAuthUser.ts
- src/utils/server/thirdweb/onLogin.ts
closes [#1263](https://github.com/Stand-With-Crypto/swc-web/issues/1263)
This PR fixes some bugs caused by users being logged in without the opt in action when signing in using wallet.
> Fix: Missing Opt In Action bug

- src/actions/actionCreateUserActionViewKeyRaces.ts
- src/utils/server/externalOptIn/handleExternalUserActionViewKeyRaces.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1291
fixes  https://stand-with-crypto.sentry.io/issues/5759108834/?project=4506871990452224&referrer=github-pr-bot
> fix: remove userSession from relation on creation

- prisma/schema.prisma
- src/actions/actionUpdateUserHasOptedInSMS.ts
- src/actions/actionUpdateUserProfile.ts
- src/app/api/public/sms/events/fails/route.ts
- src/app/api/public/sms/events/messages/route.ts
- src/app/api/public/sms/events/status/route.ts
- src/utils/server/sms/actions.ts
- src/utils/server/sms/sendSMS.ts
- src/utils/shared/urls/index.ts
closes [#161](https://github.com/Stand-With-Crypto/swc-internal/issues/161)
Adds a status callback to sendSMS so that Twilio can notify us whenever the status of a message changes. This will allow us to log updates to Mixpanel.
[#56](https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/56)
> feat: sms analytics

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> feat: add scheduled sleep to bulk sms

- src/app/[locale]/internal/user-settings/userConfig.tsx
- src/app/api/identified-user/full-profile-info/route.ts
- src/clientModels/clientUserAction/sensitiveDataClientUserAction.ts
- src/components/app/geoGate.tsx
- src/components/app/geoLocationDisclaimerBanner/geoLocationDisclaimerBanner.tsx
- src/middleware.ts
- src/utils/server/getCountryCode.ts
- src/utils/server/userActionValidation/checkCountryCode.ts
closes #1282 
This PR restores the country code bypass functionality that stopped working after a bug fix that we shipped a few days ago.
> Restores bypass country code functionality

- next.config.js
> feat: change redirects for alc tour to be more specific

- src/app/api/public/sms/events/status/route.ts
fixes [5759605772](https://stand-with-crypto.sentry.io/issues/5759605772/?project=4506490717470720)
We receive updates via the webhook after the message has been created in our database. To ensure that these logs are not lost, we need to implement a retry mechanism.
Sentry error:
Message in our database was created 1 second after the Error:
> feat: add retry mechanism to fetch messages

- src/app/api/public/sms/events/status/route.ts
> fix: increase sleep time

- src/utils/server/externalOptIn/handleExternalUserActionViewKeyRaces.ts
- src/utils/server/verifiedSWCPartner/constants.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1301
fixes
> fix: adjust user fetch for external key races api

- prisma/schema.prisma
> fix: sign up slow db query

- next.config.js
Vanity urls for https://docs.google.com/document/d/10rbmu692hXuYezVsGgR9lL21TtoWO6d3f872Rb823t8/edit#bookmark=id.76h5ocsyjjae
Please QA they work/are pointing to unique urls
> vanity urls for aug 28th

- src/components/app/pageEvents/components/promotedEvents.tsx
This PR changes the text for the promoted events dialog button
> feat: changes promoted events button text

- src/app/[locale]/topLevelClientLogic.tsx
- src/components/app/cookieConsent/useCookieConsent.ts
- src/hooks/useReloadDueToInactivity.ts
- src/utils/web/clientAnalytics.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1283
fixes 
lazy loaded modules are becoming stale and therefore no longer available leading to errors
> feat: add custom hook to reload due to inactivity

- src/components/app/pageEvents/components/eventDialogContent.tsx
- src/components/app/pageEvents/components/promotedEvents.tsx
- src/components/app/pageEvents/utils/createRsvpAction.ts
This PR changes the behavior of promoted events RSVP button to instead of opening the event dialog, directly redirecting the user to the RSVP link while creating the RSVP user action at the same time.
> Changes promoted events button behavior

- src/utils/server/sms/SendSMSError.ts
closes 
fixes [5768469563](https://stand-with-crypto.sentry.io/issues/5768469563/events/31d31ee55af5416aaab27190007ae1ec/)
> fix: add ETIMEDOUT to isTooManyRequests smsError

- next.config.js
> feat: change utm params on sst redirects

- src/inngest/functions/backfillReactivation/index.tsx
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/178
fixes
> refactor: add cron to backfill reactivation inngest function

- src/components/app/userActionFormVoterRegistration/constants.ts
closes #1322
This PR updates some URLs on the Voter Registration flow
> Update voter registration urls

- src/components/app/footer/index.tsx
> fix: adjust text wrap for footer button

- src/inngest/functions/backfillReactivation/index.tsx
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/181
fixes
> refactor: adjust backfill script

- next.config.js
> feat: add vanity urls for gotv MA sms communication

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
closes 
fixes 
We were experiencing issues with bulk SMS due to the lack of memoization of Inngest with phone numbers. Every time messages were sent in chunks and records were created in the database, Inngest was performing a new search in the database. This led to a reduction in the number of phone numbers and caused the for loop to lose its count.
To resolve this, we needed to perform the phone number search within a step of Inngest. This way, the data is memoized and not fetched again each time a step is executed.
> fix: fetch each group of phone number in its own inngest step

- prisma/schema.prisma
- src/app/api/identified-user/full-profile-info/route.ts
- src/bin/seed/seedLocalDb.ts
- src/clientModels/clientUserAction/clientUserAction.ts
- src/clientModels/clientUserAction/sensitiveDataClientUserAction.ts
- src/components/app/pageUserProfile/getAuthenticatedData.tsx
- src/components/app/recentActivityRow/activityAvatar.tsx
- src/components/app/recentActivityRow/variantRecentActivityRow.tsx
- src/data/recentActivity/getPublicRecentActivity.ts
- src/mocks/models/mockUserActionVotingInformationResearched.ts
- src/utils/server/nft/claimNFT.tsx
- src/utils/shared/userActionCampaigns.ts
[GH-176](https://github.com/Stand-With-Crypto/swc-internal/issues/176)
> chore: Add voter_information_researched action schema

- prisma/schema.prisma
- src/app/api/inngest/route.ts
- src/inngest/functions/sms/backfillSMSStatusField.ts
- src/inngest/functions/sms/index.ts
- src/mocks/models/mockUser.ts
This reverts commit 225fbbd0da44b3ad4a0a490d43daad57547052e7.
closes 
fixes 
[#66](https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/66)
> Revert "fix: fully remove old sms fields (#1300)"

- src/actions/actionCreateUserActionRsvpEvent.ts
A small change to improve our boards filtering in Mixpanel.
> Improves logging on rsvp user action logic

- docs/Contributing.md
Added the latest version of the process we have for updating the DB schema
> docs: rewrite the database changes contributing guide

- next.config.js
> feat: add dc and nv vanity urls

- next.config.js
> feat: add /nv/5 vanity url

- src/actions/actionCreateUserActionEmailDebate.ts
- src/mocks/models/mockUser.ts
This PR fixes some issues preventing the deploy to prod and preview envs
> Fix mockUser and actionCreateUserActionEmailDebate

- src/inngest/functions/backfillReactivation/index.tsx
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/181
fixes
> refactor: add separate steps and remove unnecessary findMany

- src/app/[locale]/events/[state]/[eventSlug]/page.tsx
- src/app/[locale]/events/[state]/page.tsx
- src/components/app/pageEvents/components/stateEventsDialogContent.tsx
We were redirecting the user to 404 for DC events because we were using the wrong condition check
> Fix DC state events

- src/utils/server/sms/SendSMSError.ts
> fix: flag invalid phone number if received error 21614

- src/inngest/functions/backfillReactivation/index.tsx
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/181
fixes
> refactor: adjust cron job to work again

- src/components/app/pageVoterGuide/disclaimer.tsx
- src/components/app/pageVoterGuide/index.tsx
- src/utils/shared/getUserActionsProgress.ts
> Add Turbovote disclaimer & remove voting_information action from ignore list

- cypress/e2e/11-action-mint-your-supporter-nft.cy.ts
- src/utils/web/userActionUtils.ts
This PR temporarily removes NFT mint from the user actions list
> Removes mint action from actions list

- src/components/app/userActionFormSuccessScreen/userActionFormSuccessScreenNextAction.tsx
This PR fixes an issue where we were showing actions that weren't supposed to be shown to the user.
> Fix: not removing excluded actions on success screen

- src/components/app/updateUserProfileForm/step1/control.tsx
- src/components/app/updateUserProfileForm/step1/variant.tsx
> Fix being unable to update invalid phone number

- package.json
- prisma/schema.prisma
- src/app/[locale]/races/page.tsx
- src/app/[locale]/races/state/[stateCode]/district/[district]/page.tsx
- src/app/[locale]/races/state/[stateCode]/page.tsx
- src/app/api/inngest/route.ts
- src/inngest/functions/backfillReactivation/index.tsx
- src/inngest/functions/user/clearUpActions.ts
- src/inngest/inngest.ts
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/194
fixes 
- added a function to help us clearing user actions for QA purposes only
> feat: add inngest function to delete user actions

- src/components/app/pageUserProfile/index.tsx
- src/components/app/userActionFormSuccessScreen/userActionFormSuccessScreenNextAction.tsx
This PR changes the message displayed after the user has completed all actions so that the user does not feel that there are still actions to be taken at that moment.
> feat: changes `Keep going!` to `Great job!` when the user has completed all actions

- src/utils/server/builderIO/swcEvents.ts
closes [#204](https://github.com/Stand-With-Crypto/swc-internal/issues/204)
This PR changes how we are loading data because builderIO has a default limit of 30 records and we have more than that number of events now.
> Loads events with offset

- prisma/schema.prisma
- src/inngest/functions/user/deleteUserActions.ts
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/205
fixes
> fix: prevent complete removal and opt_in removal

- src/components/app/pageVoterGuide/disclaimer.tsx
> Change Turbovote disclaimer style

- src/components/app/navbar/index.tsx
> Close navbar when clicking Vote button

- src/components/app/pageVoterGuide/index.tsx
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1399
fixes
> refactor: reorder items into vote page

- src/components/app/dtsiPersonHeroCard/index.tsx
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/198
fixes
> style: adjust politician card styling

- next.config.js
Vanity URL for https://docs.google.com/document/d/10rbmu692hXuYezVsGgR9lL21TtoWO6d3f872Rb823t8/edit#heading=h.y7hd1hajlsxk
> feat: add wi_3 sms vanity url

- src/inngest/functions/initialSignupUserCommunicationJourney/initialSignupUserCommunicationJourney.tsx
- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
- src/inngest/functions/sms/goodbyeSMSCommunicationJourney.ts
- src/inngest/functions/sms/unstopConfirmationSMSCommunicationJourney.ts
- src/inngest/functions/sms/welcomeSMSCommunicationJourney.ts
> fix: change / to . in all inngest function IDs

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
This reverts commit dde3a012389c3695a30dbcc62222887225e95127.
closes 
fixes
> Revert "feat: add enqueue message timebox (#1381)"

- src/inngest/functions/sms/utils/enqueueMessages.test.ts
- src/inngest/functions/sms/utils/enqueueMessages.ts
- src/utils/server/sms/utils/getUserByPhoneNumber.ts
This reverts commit b72447897b462555d8183260e063518c7f83ac40.
closes 
fixes
> Revert "fix: remove lodash template from addVariablesToMessage (#1367)"

- src/components/app/navbar/index.tsx
> Add creator defense banner

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> fix: revert back enqueue timebox

- src/components/app/pageLocationKeyRaces/locationRaceSpecific/index.tsx
> Reorder presidential race candidates

- next.config.js
closes 
fixes 
Vanity URL for https://docs.google.com/document/d/10rbmu692hXuYezVsGgR9lL21TtoWO6d3f872Rb823t8/edit#heading=h.p48ablgw9p66
> feat: add pa sms vanity url

- src/components/app/navbar/index.tsx
- src/components/app/userActionFormVoterAttestation/useRacesByAddress.ts
> Order presidential race

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
This reverts commit 2bcc85f6ece4577ab3c3a50440a8b0aeb2d47374.
closes 
fixes
> Revert "fix: revert back enqueue timebox (#1411)"

- next.config.js
> feat: add voter day sms vanity URL

- src/components/app/pageEvents/components/eventDialogContent.tsx
- src/components/app/pageEvents/components/promotedEvents.tsx
This PR changes event link colors so that the user can understand what is a link or not
> Changes links color for events

- next.config.js
- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> fix: bulk sms info & voter day vanity URL

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
- src/inngest/functions/sms/utils/enqueueMessages.test.ts
- src/inngest/functions/sms/utils/enqueueMessages.ts
- src/inngest/functions/sms/utils/getSMSVariablesByPhoneNumbers.ts
- src/utils/server/sms/actions.ts
- src/utils/server/sms/utils/getUserByPhoneNumber.ts
- src/utils/server/sms/utils/variables.ts
closes [#222](https://github.com/Stand-With-Crypto/swc-internal/issues/222)
fixes [PROD-SWC-WEB-4R9](https://stand-with-crypto.sentry.io/issues/5790000029/events/5a322e5a4599472fb16bfca7b2bc8c30/); [PROD-SWC-WEB-4QH](https://stand-with-crypto.sentry.io/issues/5770756711/?referrer=github_integration)
> fix: sms variables

- src/components/app/navbar/index.tsx
> Remove creator defense banner

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> feat: add current segments in queue param to bulk sms

- src/components/app/authentication/thirdwebLoginContent.tsx
- src/utils/shared/experiments.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1428
fixes
> refactor: remove phone number experiment

- package.json
- src/inngest/functions/airdropNFT/airdropNFT.tsx
- src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts
- src/inngest/functions/backfillFailedNFTCronJob/index.ts
- src/inngest/functions/backfillNFT/index.ts
- src/inngest/functions/backfillNFT/logic.ts
- src/inngest/functions/backfillNFTCronJob/index.ts
- src/inngest/functions/backfillReactivation/index.tsx
- src/inngest/functions/backfillSessionId/index.ts
- src/inngest/functions/cleanupPostalCodes/index.ts
- src/inngest/functions/cleanupPostalCodes/logic.ts
- src/inngest/functions/eventNotification/index.ts
- src/inngest/functions/eventNotification/logic.ts
- src/inngest/functions/setPrimaryCryptoAddressOfUser/index.ts
- src/inngest/functions/setPrimaryCryptoAddressOfUser/logic.ts
- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
- src/inngest/functions/sms/utils/enqueueMessages.test.ts
- src/inngest/functions/sms/utils/enqueueMessages.ts
- src/inngest/inngest.ts
- src/utils/shared/logger.ts
- src/utils/shared/prettyLog.ts
closes [#125](https://github.com/Stand-With-Crypto/swc-internal/issues/125)
fixes
> feat: child logger

- src/utils/server/thirdweb/onLogin.ts
> Merge verified users

- src/components/app/pageHome/heroImage.tsx
closes #1441 
This PR changes SWC Hero image from America Loves Crypto Tour to Voter Guide
> Changes the hero image from eventos to voter guide

- src/utils/server/mergeUsers/mergeUsers.ts
- src/utils/server/thirdweb/onLogin.ts
> Transfer address when merging users

- src/app/[locale]/press/[slug]/page.tsx
- src/app/[locale]/press/mock.tsx
- src/app/[locale]/press/page.tsx
- src/components/app/pagePress/press/index.tsx
- src/components/app/pagePress/pressRelease/index.tsx
- src/components/ui/trackedInternalLink.tsx
- src/utils/shared/slugify.ts
- src/utils/web/clientAnalytics.ts
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/231
fixes
> refactor: add press release pages

- next.config.js
- src/inngest/functions/sms/utils/getSMSVariablesByPhoneNumbers.ts
- src/inngest/functions/sms/welcomeSMSCommunicationJourney.ts
- src/utils/server/sms/messages.ts
closes [#197](https://github.com/Stand-With-Crypto/swc-internal/issues/197)
fixes 
- Changing the welcome sms to redirect users to the /vote page
> feat: link to vote page on welcome sms

- src/app/[locale]/press/[slug]/page.tsx
- src/app/[locale]/press/page.tsx
- src/components/app/pagePress/mock.tsx
- src/components/app/pagePress/press/index.tsx
- src/components/app/pagePress/pressRelease/index.tsx
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/240
fixes
> feat: add new press pages

- src/components/app/dtsiFormattedLetterGrade/index.tsx
- src/components/app/dtsiPersonHeroCard/dtsiPersonHeroCard.stories.tsx
- src/data/dtsi/fragments/fragmentDTSIPersonCard.ts
- src/data/dtsi/queries/queryDTSIPersonDetails/dtsiPersonDetailsQueryString.ts
- src/data/dtsi/schema.graphql
- src/utils/dtsi/dtsiStanceScoreUtils.ts
- src/utils/shared/findRecommendedCandidate.ts
> Score language changes

- src/data/aggregations/getTotalAdvocatesPerState.ts
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/119
fixes
> refactor: remove distinct from count

- src/app/api/verified-swc-partner/user-action-opt-in/route.ts
> Change sentry error level for invalid phone numbers

- src/inngest/functions/sms/enqueueMessages.ts
- src/utils/server/sms/sendSMS.ts
fixes [PROD-SWC-WEB-4YG](https://stand-with-crypto.sentry.io/issues/5931945048/events/e5663eb1bc5d470da7c1194728d77f24/); [PROD-SWC-WEB-4YH](https://stand-with-crypto.sentry.io/issues/5932149087/events/22928f7e71834e4982a21efefe8fdc7b/)
This PR fixes two bugs that were introduced by #1457
> fix: enqueue messages sentry errors

- src/components/app/pageAdvocatesHeatmap/advocatesHeatmap.tsx
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1471
fixes
> fix: adjust svg rendering on safari

- src/components/app/pageVoterGuide/constants.tsx
> fix: card sizes on desktop

- src/components/app/pageVoterGuide/disclaimer.tsx
- src/components/app/pageVoterGuide/index.tsx
> fix: disclaimer position on voter page

- src/components/app/geoGate.tsx
> be more permissive on geofence targeting to make sure we don't block US citizens

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
- src/inngest/functions/sms/enqueueMessages.ts
closes 
fixes 
Adds the total chunks in the enqueue messages step to make it more visible how many steps are left
> feat: improve visibility of how many steps are left

- src/app/[locale]/internal/user-settings/userConfig.tsx
- src/hooks/useSession.ts
- src/middleware.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1490
fixes
> refactor: adjust cookie options for session and user ids

- src/app/[locale]/(homepageDialogDeeplink)/action/[action]/all/layout.tsx
- src/app/[locale]/(homepageDialogDeeplink)/action/[action]/all/page.tsx
- src/components/app/homepageDialogDeeplinkLayout.tsx
- src/components/app/userActionGridCTAs/components/userActionGridCampaignsDialog.tsx
closes #1497 
This PR prepares a new deeplink to be used by the CB app whenever we have more than one campaign active at the same time for a specific action.
> feat: creates action campaigns deeplink

- next.config.js
> feat: add sms shortlink for oh campaign

- src/app/api/inngest/route.ts
> fix: remove civic api backfill while we sort out the api quota issue

- src/app/api/inngest/route.ts
> feat: revert disabled inngest fn

- next.config.js
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/274
fixes
> chore: adjust content security policy

- src/app/[locale]/races/state/[stateCode]/district/[district]/page.tsx
> Fix static district page generation

- next.config.js
Vanity URLs for these messages https://docs.google.com/document/d/1UfHbfMXHzN9-IVMy8WpC8txQxZk8eOTAxipF2ix_vaA/edit?tab=t.0
> feat: voter-guide-2 SMS vanity URL

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
closes #1527 
fixes [PROD-SWC-WEB-523](https://stand-with-crypto.sentry.io/issues/6014790105/events/ef6b8d5bf2f542f298f2abf872faea70/)
Currently when fetching the phone numbers we're returning a collection with all phone numbers and this is causing the function to fail when the internal state reaches 32 MB.
```js
// Payload returned by each step now
[{ phoneNumber: "+1xxx" }]
// After this PR
["+1xxx"]
```
> fix: return array of string instead of collection when fetching phone numbers

- src/utils/server/sms/messages.ts
> fix: welcome sms variable

- next.config.js
- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
- Adds vanity URLs for these messages https://docs.google.com/document/d/1UfHbfMXHzN9-IVMy8WpC8txQxZk8eOTAxipF2ix_vaA/edit?pli=1&tab=t.0
- Increases the starting time to send bulk-messages from 11 a.m to 9 a.m.
> feat: add voter-guide vanity URLs

- next.config.js
> feat: add vanity url for cb push notifications

- src/actions/actionCreateUserActionCallCongressperson/index.ts
- src/actions/actionCreateUserActionEmailCongressperson.ts
- src/actions/actionUpdateUserProfile.ts
- src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts
- src/utils/server/externalOptIn/handleExternalUserActionOptIn.ts
- src/utils/shared/getCongressionalDistrictFromAddress.ts
> feat: add abstraction for not found congressional district log

- src/components/app/pageLocationKeyRaces/locationStateSpecific/stancesSection.tsx
> Fix import

- src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/index.tsx
> feat: add banner to the live results page

- src/components/app/pageVoterGuide/constants.tsx
- src/components/app/pageVoterGuide/index.tsx
- src/components/app/pageVoterGuide/voterJourneyStepList.tsx
> refactor: add i voted into vote page

- src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/index.tsx
> feat: change badge copy

- src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/index.tsx
- src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/liveResultsMap.tsx
> Show map on mobile

- src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> Persist only if theres data

- src/data/aggregations/decisionDesk/utils.ts
> fix: var naming

- src/data/aggregations/decisionDesk/utils.ts
> fix: runtime error toLowerCase

- src/data/aggregations/decisionDesk/getAllRacesData.ts
> refactor: adjust votes getting

- src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> fix: add ? to undefined variable

- src/data/aggregations/decisionDesk/utils.ts
> fix: replace toLowerCase with lodash util

- src/data/aggregations/decisionDesk/utils.ts
> fix: toLowerCase bug

- src/data/aggregations/decisionDesk/utils.ts
> chore: add debug logs

- src/data/aggregations/decisionDesk/utils.ts
> fix: remove logs

- src/data/aggregations/decisionDesk/utils.ts
> feat: add sentry log to catch statement

- src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
- src/utils/server/decisionDesk/schemas.ts
> fix: adjust congress data for la state

- src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/LiveResultCard/avatarBox.tsx
- src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/LiveResultCard/keyRaceLiveResultCard.tsx
> Fix duplicated candidate

- src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/presidentialRaceResult.tsx
> style: add link to winner avatar

- next.config.js
> feat: election results sms vanity url

- src/components/app/pageDonate/ctas.tsx
- src/components/app/userActionGridCTAs/index.tsx
> feat: add className override to the donate page ctas

- src/app/[locale]/topLevelClientLogic.tsx
- src/hooks/usePromoteDevParticipation.ts
> feat: add developer promotion on the console

- src/app/api/public/sms/events/messages/route.ts
Improve Sentry logs to audit [#1613](https://github.com/Stand-With-Crypto/swc-web/issues/1613)
> fix: update Sentry message to log message body instead of phone number

- src/inngest/functions/backfillUserCommunicationMessageStatus/index.ts
Introduced a `queryLimit` variable to split the `DATABASE_QUERY_LIMIT` in half to avoid "Output size is too large" errors.
> fix: adjust query limit to prevent output size errors

- README.md
- docs/Contributing.md
- docs/Verified SWC Partner Guide.md
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1632
fixes
> docs: adjust docs

- src/inngest/functions/datadog/cleanup/index.ts
closes #1635 
This PR changes the cron job schedule from daily at 3 AM to hourly execution. Additionally, the synthetic tests are now run every 10 minutes. The code has also been refactored to improve maintainability.
> feat: improves datadog cleanup function and decreases cron job schedule

- src/components/app/userActionFormSuccessScreen/UserActionFormSuccessScreenFeedback.tsx
- src/components/app/userActionFormSuccessScreen/index.tsx
- src/components/app/userActionFormSuccessScreen/joinSWC.tsx
- src/components/app/userActionFormSuccessScreen/userActionFormSuccessScreenNextAction.tsx
- src/components/app/userActionVotingDay/index.tsx
- src/components/app/userActionVotingDay/sections/success.tsx
This PR removes the hardcoded text on the success screen related to Election Day.
> feat: removes hardcoded election success screen

- next.config.js
> feat: add SMS shortlink for secvote redirection

- sentry.client.config.ts
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/145
fixes
> chore: adjust sentry integration

- next.config.js
> feat: add second secvote vanity URL

- src/components/app/navbarGlobalBanner/navbarGlobalBannerContent.tsx
This PR changes the return statement when hydration has not completed yet
> fix: blinking message on global banner

- src/components/app/pagePrivacyPolicy/index.tsx
closes #1668 
Fulfill the legal request to update the policy copy
> feat: change public policy copy

- next.config.js
Metamask login is not working due to a CSP missing configuration
> feat: add walletconnect.org to connect-src allow list

- src/components/app/userActionFormCommon/layout.tsx
- src/components/app/userActionFormNFTMint/sections/intro.tsx
> Fix hydration error on ntf-mint flow

- src/components/app/cookieConsent/cookieConsentManageModal/index.tsx
- src/components/app/navbar/index.tsx
- src/components/app/navbar/navbarLoggedInButton/index.tsx
- src/components/app/pagePoliticianDetails/scoreExplainer.tsx
- src/components/ui/drawer.tsx
closes #1677 
fixes [PROD-SWC-WEB-5DT](https://stand-with-crypto.sentry.io/issues/6148274872/?referrer=github_integration) [PROD-SWC-WEB-5DS](https://stand-with-crypto.sentry.io/issues/6148274793/?referrer=github_integration)
> Add missing accessibility props

- src/components/app/navbar/navbarLoggedInButton/index.tsx
> Fix signin button

- src/components/app/navbar/navbarLoggedInButton/index.tsx
Reverts Stand-With-Crypto/swc-web#1682
> Revert "Fix signin button"

- package-lock.json
- package.json
closes 
fixes 
Recent Thirdweb releases have fixes for connection issues, this should reduce the few errors related to Thirdweb we are seeing on Sentry
> Bump thirdweb version to 5.80.0

- src/components/app/userActionFormCallCongressperson/sections/address/index.tsx
- src/components/app/userActionFormEmailCongressperson/index.tsx
> Fix Call form

- package-lock.json
- package.json
> Upgrade react-hook-form to v7.54.2

- src/utils/shared/phoneNumber.ts
> feat: add metadata to phoneNumber validation errors

- src/components/app/userActionGridCTAs/constants/ctas.tsx
- src/components/app/userActionGridCTAs/index.tsx
This PR adds a new email CTA for the welcome the new congress email campaign.
> feat: adds the new email campaign CTA

- src/app/api/public/sms/events/messages/route.ts
- src/utils/server/sms/identifyIncomingKeyword.test.ts
- src/utils/server/sms/identifyIncomingKeyword.ts
> fix: correct unidentified keyword validation logic

- src/app/api/public/sms/events/messages/route.ts
> fix: simplify Sentry capture message for unidentified keywords

- src/utils/web/googlePlaceUtils.ts
closes #1652
fixes 
Calling getDetails with only place_id field will refresh the place_id and the request is free of charge.
> Refresh place_id on error

- next.config.ts
> feat: add SMS shortlink redirect for new congress email retry

- next.config.ts
> feat: add email shortlink for broker reporting rule

- src/app/[locale]/internal/page.tsx
- src/app/[locale]/internal/user-info/page.tsx
- src/utils/server/getCountryCode.ts
> feat: user info page

- bin/vercel_deploy.sh
closes 
fixes 
removed until we understand what's happening https://vercel.com/coinbase-vercel/swc-web/6fmuvvBxf1xKrWNW5vWtwPH1SHLA?filter=errors
> chore: temporarily disable DB schema check in Vercel deployment script

- src/utils/server/localeRouter/index.ts
- src/utils/shared/supportedLocales.ts
This reverts commit ac2e3c1f6cc81e790f8dec926c95ba3ca55ad224.
closes 
fixes
> Revert "feat: save locale information on middleware (#1792)"

- prisma/schema.prisma
> feat: replace tenantId default value from US to us

- src/app/[countryCode]/internal/user-settings/userConfig.tsx
- src/utils/server/getCountryCode.ts
> feat: cookie country code parsing

- src/components/ui/pageSubTitle/pageSubTitle.builder.tsx
- src/components/ui/pageTitleText/pageTitleText.builder.tsx
> refactor: simplify default size prop in Builder.io components

- .gitignore
- src/app/layout.tsx
closes https://github.com/Stand-With-Crypto/swc-internal/issues/339
fixes
> Change fetchCache config

- .eslintrc.js
> chore: add no unstable nested components lint rule

- prisma/schema.prisma
- src/app/api/identified-user/full-profile-info/route.ts
- src/bin/seed/seedLocalDb.ts
- src/clientModels/clientUserAction/clientUserAction.ts
- src/clientModels/clientUserAction/sensitiveDataClientUserAction.ts
- src/components/app/pageUserProfile/getAuthenticatedData.tsx
- src/components/app/recentActivityRow/activityAvatar.tsx
- src/components/app/userActionFormSuccessScreen/constants.ts
- src/data/recentActivity/getPublicRecentActivity.ts
- src/mocks/models/mockUserActionRefer.ts
- src/utils/server/nft/claimNFT.tsx
- src/utils/shared/activeUserAction.ts
- src/utils/shared/urlsDeeplinkUserActions.ts
- src/utils/shared/userActionCampaigns.ts
closes #1835 
fixes 
Schema changes for the new user action
https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/91
> Create User Action REFER

- src/components/app/recentActivityRow/variantRecentActivityRow.tsx
> Add missing REFER action to switch case

- src/bin/oneTimeScripts/detectAndRemoveInvalidDTSISlugs.ts
- src/data/dtsi/queries/queryDTSIPeopleBySlugForUserActions.ts
Cleanup script to remove invalid DTSI slugs from our test DB
> feat: add script to detect and remove invalid DTSI slugs from user actions

- src/components/ui/command.tsx
> Fix address field

- src/actions/actionUpdateUserCountryCode.ts
- src/app/[countryCode]/internal/user-settings/userConfig.tsx
- src/validation/fields/zodSupportedCountryCode.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1895
fixes
> feat: add server action to update user country code

- src/components/ui/dialog/index.tsx
- src/globals.css
> fix: adjust dialog scroll area overflow behavior

- src/utils/server/thirdweb/onLogin.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1899
fixes
> feat: update login flow to handle user country code cookie

- src/components/app/navbarGlobalBanner/index.tsx
- src/components/app/pageDonate/ctas.tsx
- src/components/app/userActionGridCTAs/constants/ctas.tsx
- src/components/app/userActionGridCTAs/index.tsx
- src/components/app/userActionGridCTAs/skeleton.tsx
> revert: new broker reporting rule sjres3 banner

- src/components/app/dtsiClientPersonDataTable/filters.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1970
fixes
> refactor: improve stance filtering logic in person data table

- src/components/app/pageDonate/ctas.tsx
- src/components/app/userActionGridCTAs/index.tsx
- src/components/app/userActionGridCTAs/skeleton.tsx
> Update grid columns

- src/components/app/navbarGlobalBanner/index.tsx
- src/components/app/userActionGridCTAs/constants/ctas.tsx
This PR disables the email action and removes the campaign navbar banner
> feat: disables email campaign after H.J.Res.25 vote section

- src/middleware.ts
- src/utils/server/getCountryCodeCookie.ts
- src/utils/server/internationalRedirectHandler.test.ts
- src/utils/server/internationalRedirectHandler.ts
- src/utils/server/obfuscateURLCountryCode/index.ts
- src/utils/server/serverAnalytics/serverAnalytics.ts
- src/utils/server/serverLocalUser.ts
- src/utils/server/thirdweb/onLogin.ts
- src/utils/shared/supportedCountries.ts
- src/utils/web/getCountryCodeForClientAnalytics.ts
Reverts Stand-With-Crypto/swc-web#1999
> Revert "Revert "feat: international homepage redirect (#1948)""

- src/actions/actionCreateUserActionRsvpEvent.ts
- src/utils/server/getCountryCodeFromURL.ts
- src/utils/server/obfuscateURLCountryCode/index.ts
- src/utils/server/thirdweb/onLogin.ts
> Save current page country code

- src/app/api/inngest/route.ts
- src/inngest/functions/backfillCountryCodes/index.ts
- src/inngest/types.ts
- src/utils/server/thirdweb/onLogin.ts
> Backfill unsupported country codes with US

- src/components/app/navbar/index.tsx
> fix: add polls back to navbar

- src/data/verifiedSWCPartners/userActionOptIn.ts
- src/utils/server/externalOptIn/handleExternalUserActionOptIn.ts
Temporary PR for today's bugbash
> temporary disables country code validation

- src/app/[countryCode]/internal/user-settings/userConfig.tsx
closes  https://github.com/Stand-With-Crypto/swc-web/issues/2028
fixes
> fix: only call server action only when logged in

- src/actions/actionCreateUserActionRsvpEvent.ts
- src/utils/server/getCountryCodeFromURL.ts
- src/utils/server/obfuscateURLCountryCode/index.ts
- src/utils/server/thirdweb/onLogin.ts
* WIP: Get country code from url
* Create getCountryCodeFromURL function
* Replace getCountryCodeCookie with getCountryCodeFromURL
closes 
fixes
> Save current page country code (#2012)

- prisma/schema.prisma
> Index referralId

- src/app/(builder)/[countryCode]/layout.tsx
- src/app/[countryCode]/layout.tsx
- src/components/app/builder/builderPageLayout.tsx
- src/components/app/layout/layout.tsx
> feat: add country specific navbar and footer to builder.io layout

- next.config.ts
- prisma/schema.prisma
- src/app/api/public/x-redirect/[state]/route.ts
This PR updates the feature branch to be in sync with main
> chore: sync feature branch with main | 03/26

- src/utils/shared/auStateUtils.ts
- src/utils/shared/caProvinceUtils.ts
- src/utils/shared/gbCountryUtils.ts
- src/utils/shared/usStateUtils.ts
> feat: add utility functions for Australian, Canadian, British, and US state/province/country code mappings

- src/components/app/userActionFormShareOnTwitter/au/index.tsx
- src/components/app/userActionFormShareOnTwitter/ca/index.tsx
> Change twitter account name for AU and CA

- src/components/app/userActionFormJoinSWC/successDialog.tsx
- src/components/app/userActionFormSuccessScreen/index.tsx
- src/components/app/userActionFormSuccessScreen/userActionFormSuccessScreenNextAction.tsx
- src/components/ui/dialog/index.tsx
> Fix success modal padding

- src/components/app/notFoundLayout.tsx
> Add hero banner to not-found page

- sentry.client.config.ts
> chore: add a sentry ignore to the google places migration warning

- src/app/au/config.tsx
- src/components/app/authentication/thirdwebLoginContent.tsx
- src/components/app/navbarGlobalBanner/index.tsx
- src/components/app/pageEvents/components/featuredPastEvents.tsx
- src/components/app/pageEvents/utils/getUniqueEventKey.ts
- src/components/app/pageHome/au/index.tsx
- src/components/app/pageHome/common/foundersCarousel.tsx
- src/components/app/pageHome/common/types.ts
- src/components/app/pageHome/gb/index.tsx
- src/components/app/pagePress/NewsList.tsx
- src/utils/server/builder/models/data/founders.ts
- src/utils/shared/zod/getSWCFounders.ts
* Disable phone sign-up for countries outside the US
* Fixed global banner overflowing on mobile
* Remove partners on Australia Navbar
* Add border radius to news preview image
* Make the news preview image a square on mobile
* Center featured events if there are less then 3
* Rename `Founders` to `Featured founders`
* Change layout of the founders section into a multi row approach on desktop
> fix: design inconsistencies

- cypress/e2e/13-user-action-unavailable.cy.ts
- cypress/e2e/14-navbar-global-banner.cy.ts
- src/components/app/navbarGlobalBanner/redirectbannerContent.tsx
NextJS has some problem with router.push or the Link component when the href is /.
Because of that, we had to change the behavior to navigate the user with window.location to guarantee that the entire application will match the selected country
> fix: global navbar banner redirect link

- src/components/app/geoGate.test.tsx
This PR adds tests to GeoGate component to guarantee that it will work as expected in all scenarios
> test: adds tests for GeoGate to guarantee that is is working as expected

- src/components/app/pageHome/common/topLevelMetrics.tsx
> Top level metrics copy changes

- src/components/app/cookieConsent/common/manageCookiesModal.tsx
> Add intl contact email to cookie consent modal

- src/components/app/authentication/loginDialogWrapper.tsx
- src/components/app/pagePolls/activePoll.tsx
- src/components/app/pagePolls/protectedSubmitButton.tsx
This PR fixes the sign up block that shows that actions are only for US users on non US SWC pages during sign up.
> fix: update profile geogate blocking supported country users from completing the sign up

- src/components/app/pageHome/gb/index.tsx
This PR updates the description in the partners section for the UK homepage.
We also need to update the description in Builder.io for the UK partners page [In progress...]
> chore: updates UK partners section description

- src/app/au/races/page.tsx
- src/app/au/races/state/[stateCode]/district/[district]/house-of-representatives/page.tsx
- src/app/au/races/state/[stateCode]/page.tsx
- src/app/ca/races/page.tsx
- src/app/ca/races/state/[stateCode]/district/[district]/house-of-commons/page.tsx
- src/app/ca/races/state/[stateCode]/page.tsx
- src/components/app/pageHome/au/index.tsx
- src/components/app/pageHome/ca/index.tsx
- src/components/app/pageHome/common/topLevelMetrics.tsx
- src/components/app/pageHome/gb/index.tsx
- src/components/app/pageLocationKeyRaces/common/locationRaces/index.tsx
> fix: bunch of intl bug bash items

- next.config.ts
> feat: add redirect for SMS shortlink to new SB 1797

- src/actions/actionUpdateUserCountryCode.ts
closes 
fixes 
- Delete `SWC_COOKIE_CONSENT` cookie on User country change
> Delete cookie consent on country change

- src/inngest/functions/backfillIntlUsers/logic.ts
> Use correct countryCode for Zebu csv backfill

- src/app/au/config.tsx
- src/components/app/pageHome/au/index.tsx
> fix(au): remove community page

- next.config.ts
> feat: add SMS shortlink for Paul Atkins in next.config.ts

- src/app/[countryCode]/config.tsx
- src/components/app/navbar/index.tsx
- src/components/app/recentActivityRow/recentActivityRow.tsx
> Change activity row styles & Navbar donate button

- src/components/app/pageLocationKeyRaces/us/locationRaceGovernorSpecific/index.tsx
> refactor: remove pack from governor's bottom

- src/components/app/recentActivityRow/recentActivityRowAnimatedContainer.tsx
- src/utils/shared/stateUtils.ts
> fix: filter invalid administrativeAreaLevel1 on recent activities feed

- src/actions/actionCreateUserActionPoll.ts
- src/actions/actionCreateUserActionRsvpEvent.ts
- src/actions/actionCreateUserActionTweet.ts
- src/actions/actionCreateUserActionTweetAtPerson.ts
- src/actions/actionUpdateUserHasOptedInSMS.ts
- src/utils/server/getCountryCodeFromURL.ts
- src/utils/server/serverWrappers/withServerActionMiddleware.ts
> fix: change where country code comes from on actions

- src/bin/seed/seedLocalDb.ts
- src/components/app/pagePolls/index.tsx
- src/data/polls/getPollsData.ts
- src/hooks/usePollsResultsData.ts
- src/mocks/models/mockUserActionPoll.ts
- src/mocks/models/mockUserActionPollAnswer.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/2175
fixes
> refactor: adjust polls fetching

- src/components/app/pageHome/gb/hero.tsx
Updates the home page hero CTA to the debanking action
> feat: change gb home cta to a debanking action

- src/actions/actionUpdateUserProfile.ts
- src/utils/server/externalOptIn/handleExternalUserActionOptIn.ts
> disable maybeGetCongressionalDistrictFromAddress for intl domains

- src/app/ca/races/page.tsx
- src/components/app/pagePoliticians/ca/index.tsx
> CA election copy changes

- src/app/au/races/state/[stateCode]/district/[district]/house-of-representatives/page.tsx
- src/app/ca/races/state/[stateCode]/district/[district]/house-of-commons/page.tsx
> refactor: adjust district states pages to generate logic

- src/inngest/functions/backfillNFTCronJob/index.ts
- src/utils/server/nft/claimNFT.tsx
closes 
fixes [PROD-SWC-WEB-66D](https://stand-with-crypto.sentry.io/issues/6552011689/events/03960c36c6f04507a8b60958b80ae38e/)
- Changed `Promise.all` for `Promise.allSettled`, allowing all NFT claim attempts to complete regardless of any individual failures
> Add missing nft data for VOTER_REGISTRATION user action

- src/app/api/inngest/route.ts
- src/inngest/functions/sms/backfillMissingCommunications.ts
- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
- src/inngest/functions/sms/index.ts
- src/inngest/types.ts
closes [#1993](https://github.com/Stand-With-Crypto/swc-web/issues/1993)
* Fixed the bulk-sms query
* Added backfill script as described in the task
> fix: bulk sms missing communication

- src/components/app/pageHome/gb/hero.tsx
> fix: typo in gb Hero CTA

- src/app/gb/config.tsx
> Add politician scores entry to the UK navbar

- src/app/[countryCode]/internal/user-info/page.tsx
- src/data/verifiedSWCPartners/userActionOptIn.ts
- src/utils/server/externalOptIn/handleExternalUserActionOptIn.ts
- src/utils/server/externalOptIn/types.ts
- src/validation/userActionOptIn/zodExternalUserActionOptIn.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/2219
fixes 
- This is an attempt to decrease this function's response time
Current updated branch: 
Main branch as-is:
> rerfactor: attempt to decrease optin action response time

- src/components/app/pagePoliticians/au/index.tsx
> fix: correct typo in AU politicians page description

- src/app/[countryCode]/politicians/page.tsx
- src/app/au/politicians/page.tsx
- src/app/ca/politicians/page.tsx
- src/app/gb/politicians/page.tsx
- src/components/app/dtsiClientPersonDataTable/common/useTableFilters.ts
- src/components/app/pagePoliticians/au/index.tsx
- src/components/app/pagePoliticians/ca/index.tsx
- src/components/app/pagePoliticians/gb/index.tsx
- src/components/app/pagePoliticians/us/index.tsx
closes  https://github.com/Stand-With-Crypto/swc-web/issues/2229
fixes
> refactor: update dynamic rendering for politicians pages to force-static

- next.config.ts
- src/app/gb/config.tsx
> Remove uk politicians page

- src/components/app/pageHome/gb/index.tsx
> remove uk politicians home section

- next.config.ts
- src/components/app/pageHome/gb/index.tsx
> Redirect uk politician details page to homepage

- src/components/app/recentActivityRow/constants.ts
- src/components/app/recentActivityRow/variantRecentActivityRow.tsx
This PR fixes the follow on X description on the activity feed.
> fix: wrong follow on x description in activity feed

- src/components/app/pagePoliticianDetails/common/generateOgImage.tsx
> fix: conditionally display stance scores in OG image generation

- src/app/api/inngest/route.ts
- src/inngest/functions/capitolCanary/constants.ts
- src/inngest/functions/capitolCanary/deleteNotSupportedCountryCodeAdvocates.ts
- src/inngest/functions/capitolCanary/upsertAdvocateInCapitolCanary.ts
- src/inngest/types.ts
- src/utils/server/capitolCanary/baseUpsertRequest.ts
- src/utils/server/capitolCanary/metadata.ts
- src/utils/server/capitolCanary/updateAdvocate.ts
> feat: add inngest script to add delete tag to intl advocates

- src/app/[countryCode]/referrals/[[...page]]/page.tsx
- src/components/app/pageReferrals/heading.tsx
closes 
fixes 
- Removed 'referrals' mentions to better reflect that the leaderboard is currently showing advocates and not referrals count
- This is only shown for unauthed users
> Referrals page copy change

- src/inngest/functions/capitolCanary/constants.ts
- src/inngest/functions/capitolCanary/isAdvocateSupported.ts
- src/inngest/functions/capitolCanary/upsertAdvocateInCapitolCanary.ts
closes #2276 
fixes PROD-SWC-WEB-614
> fix: remove test user from cc

- src/app/ca/config.tsx
> feat: remove legal text from footer configuration in CA

- next.config.ts
> feat: add genius floor sms vanity URL

- src/components/app/userActionFormEmailCongressperson/campaignMetadata.ts
- src/components/app/userActionGridCTAs/constants/us/usCtas.tsx
- src/utils/shared/urlsDeeplinkUserActions.ts
> feat: change email campaign to genius

- src/inngest/functions/sendgridContactsCronJob/index.ts
> Add Sendgrid cron schedule

- src/components/app/userActionFormEmailCongressperson/campaignMetadata.ts
> feat: change email campaign body

- next.config.ts
> fix: rename genius campaign

- src/inngest/functions/sendgridContactsCronJob/config.ts
- src/inngest/functions/sendgridContactsCronJob/index.ts
- src/inngest/functions/sendgridContactsCronJob/logic.ts
- src/utils/server/sendgrid/marketing/contacts.ts
> Fix upload size check

- src/inngest/functions/sendgridContactsCronJob/logic.ts
> Log sync error to Sentry

- next.config.ts
> feat: add shortlink for clarity house campaign

- prisma/schema.prisma
This PR is the first step for implementing the user deletion logic. Verified partners will be able to sync with this table to check if a user should be deleted on their end.
[Deploy request](https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/123)
> feat: creates new UserDeletionLog table

- src/app/[countryCode]/config.tsx
- src/utils/shared/urls/index.ts
> feat: change resources links on the us footer

- src/components/app/navbarGlobalBanner/us/currentCampaign.tsx
> feat: add genius banner to us

- src/components/app/pageVoterGuide/constants/us/usCtas.tsx
> feat: replace voter attestation with opt in on voter guide page

- src/utils/server/sms/identifyIncomingKeyword.ts
> feat: add additional help keywords for SMS

- src/app/api/public/swc-civic/electoral-zone/route.ts
- src/utils/server/swcCivic/utils/getLatLongFromAddress.ts
> feat: improve logging on electoral-zone route

- src/actions/actionCreateUserActionEmailCongresspersonIntl.tsx
- src/utils/server/quorum/utils/fetchQuorum.ts
- src/utils/server/serverAnalytics/serverAnalytics.ts
> Log error to Sentry & skip email

- src/components/app/pagePolls/pollItem.tsx
- src/components/app/pagePolls/pollResultItem.tsx
- src/components/app/pageVoterGuide/voterJourneyStepList.tsx
- src/components/app/userActionGridCTAs/components/campaignsCheckmarks.tsx
- src/components/app/userActionGridCTAs/components/successScreenActionCard.tsx
- src/components/app/userActionGridCTAs/components/userActionCard.tsx
- src/components/app/userActionGridCTAs/components/userActionGridCampaignsDialog.tsx
- src/components/app/userActionGridCTAs/icons/checkIcon.tsx
> Wrap action card checkmarks

- src/app/[countryCode]/config.tsx
> feat: add clarity footer link

- src/components/app/navbarGlobalBanner/us/currentCampaign.tsx
> feat(us): remove banner

- src/components/app/userActionGridCTAs/constants/us/usCtas.tsx
> feat(us): disable genius campaign

- .vscode/settings.json
- next.config.ts
- src/app/ca/(homepageDialogDeeplink)/action/email/page.tsx
- src/components/app/recentActivityRow/viewKeyPageRecentActivityRow.tsx
- src/components/app/userActionFormViewKeyPage/dialog.tsx
- src/components/app/userActionGridCTAs/components/userActionGridCampaignsDialog.tsx
- src/components/app/userActionGridCTAs/constants/ca/caCtas.tsx
- src/utils/shared/urls/index.ts
- src/utils/shared/userActionCampaigns/ca/caUserActionCampaigns.ts
> feat: ca house rising action

- src/inngest/functions/backfillAddressElectoralZone/config.ts
- src/inngest/functions/backfillAddressElectoralZone/index.ts
- src/inngest/functions/backfillAddressElectoralZone/logic.ts
> Fix script pagination skipping records

- src/inngest/functions/backfillAddressElectoralZone/config.ts
- src/inngest/functions/backfillAddressElectoralZone/logic.ts
> Remove google places requests

- src/components/app/authentication/authentication.builder.tsx
- src/components/app/authentication/maybeAuthenticatedContent.tsx
> fix: add empty loading component on builder Authentication component

- sentry.client.config.ts
- src/utils/shared/fetchReq.ts
> fix: group fetch req sentry errors

- src/app/[countryCode]/(homepageDialogDeeplink)/action/email/page.tsx
- src/app/au/(homepageDialogDeeplink)/action/email/page.tsx
- src/app/ca/(homepageDialogDeeplink)/action/email/page.tsx
- src/app/gb/(homepageDialogDeeplink)/action/email/page.tsx
> fix: remove small size on email action deeplink dialog

- sentry.client.config.ts
- src/components/app/pageDonate/heading.tsx
> fix: suppress wallet auto connect issues and remove nft mint cta

- src/inngest/functions/backfillAddressFieldsWithGooglePlaces/index.ts
- src/inngest/functions/backfillAddressFieldsWithGooglePlaces/logic.ts
> fix: move backfill address fields timeout to processor

- src/components/app/userActionFormEmailCongressperson/us/campaigns/20250613-clarity-act-house.tsx
- src/components/app/userActionGridCTAs/constants/us/usCtas.tsx
> feat: change clarity campaign copy

- src/app/[countryCode]/config.tsx
> Hide local policy page

- src/components/app/pageHome/us/hero.tsx
> Update US hero for the clarity email action

- next.config.ts
> feat: add sms clarity vanity URL

- src/components/app/updateUserProfileForm/step1/index.tsx
fixes [PROD-SWC-WEB-CS3](https://stand-with-crypto.sentry.io/issues/6732197014/)
> fix: handle undefined user countryCode on updateUserProfileForm

- next.config.ts
- sentry.client.config.ts
- src/components/app/navbarGlobalBanner/au/currentCampaign.tsx
fixes [PROD-SWC-WEB-4W2](https://stand-with-crypto.sentry.io/issues/5876226755/)
> fix: au hydration errors

- sentry.client.config.ts
Updated the \`COMMON_ERROR_MESSAGES_TO_GROUP\` array in \`sentry.client.config.ts\` to include 27 new error patterns based on analysis of the past 30 days of Sentry data from \`prod-swc-web\`.
- **High-volume network errors** (18k+ occurrences): \`Failed to fetch TypeError\`, \`Load failed TypeError\`, \`Event request via fetch failed\`
- **Global application errors** (17k+ occurrences): \`Global Error Page Displayed\`
- **Google Maps/Places API errors** (7k+ occurrences): \`Could not load \"places_impl\"\`, \`Failed to load Google Maps script\`, \`place ID is no longer valid\`
- **Database/Prisma errors** (2k+ occurrences): \`Invalid prisma.user.update() invocation\`, \`Object Not Found Matching Id\`
- **Mobile browser/WebKit errors** (1k+ occurrences): \`window.webkit.messageHandlers\` …
> chore: update Sentry error grouping patterns

- src/components/app/pageUnsubscribe/au/index.tsx
- src/components/app/pageUnsubscribe/ca/index.tsx
- src/components/app/pageUnsubscribe/commom/resubscribeButton.tsx
- src/components/app/pageUnsubscribe/gb/index.tsx
- src/components/app/pageUnsubscribe/us/index.tsx
- src/utils/shared/urls/index.ts
> Add countryCode to ResubscribeButton

- src/inngest/functions/backfillIntlUsers/logic.ts
- src/inngest/functions/sendgridContactsCronJob/index.ts
> Increase maxWait and timeout values for backfill users transaction

- src/utils/server/builder/models/data/bills.ts
- src/utils/shared/zod/getSWCBills.ts
Fix a small issue with the bills list.
> fix: bills list

- src/components/app/pageBillDetails/partials/timelineSection/constants.ts
- src/components/app/pageBillDetails/partials/timelineSection/index.tsx
- src/components/ui/timeline/constants.ts
- src/components/ui/timeline/majorMilestone.tsx
- src/components/ui/timeline/minorMilestone.tsx
- src/components/ui/timeline/progress.tsx
- src/components/ui/timeline/timeline.tsx
- src/components/ui/timeline/types.ts
- src/utils/server/builder/models/data/bills.ts
- src/utils/shared/zod/getSWCBills.ts
This pull request addresses the issues identified during the recent bug bash session. The following changes have been implemented to enhance the UI and improve functionality:
Alignment Adjustment:
- The “X” marker has been moved up by 1px to ensure better alignment with the through line.
Color Update:
- The color of the “X” marker has been changed from red to gray. This adjustment aims to reduce visual distraction and create a more cohesive design.
Hover and Click Behavior:
- Resolved the weird behavior experienced when clicking and hovering over small points within the timeline section. The interaction should now be smoother and more intuitive.
Outline Color Matching:
- The outline color of the empty plot points has been updated to match the color of the through line, providing a more …
> fix: bill timeline bug bash

- src/components/app/pageBillDetails/filters.tsx
closes #2576 
This PR addresses the issue of the filters on the Bills page not functioning on mobile devices.
> refactor: simplify SelectContent component in Filters by removing unnecessary touch event handling

- src/components/app/pageDayOfAction/index.tsx
update livestream from youtube to X
> update livestream to x

- src/components/app/pagePetitionDetails/milestones/index.tsx
- src/components/app/pagePetitionDetails/milestones/item.tsx
- src/components/app/pagePetitionDetails/milestones/milestones.stories.tsx
- Introduced the PetitionMilestones component to display milestones based on petition goals and current signatures.
- Implemented automatic milestone generation based on predefined thresholds.
- Created MilestoneItem component for individual milestone representation.
- Added Storybook stories for various scenarios, including default, progress with milestones, and custom milestones.
- The storybook stories were AI generated.
> feat: add PetitionMilestones component

- src/components/app/userActionViewKeyPageDeeplinkWrapper/redirect.tsx
fixes https://stand-with-crypto.sentry.io/issues/5013597000/events/latest/?environment=production&project=4506490717470720&query=is%3Aunresolved&referrer=latest-event&seerDrawer=true
> dont use next.js router primitives for external URLS

- src/actions/actionCreateUserActionPetitionSignature.ts
- src/app/[countryCode]/petitions/page.tsx
- src/bin/seed/seedLocalDb.ts
- src/components/app/pagePetitionDetails/debugger/index.tsx
- src/components/app/pagePetitionDetails/debugger/petitionDataEditor.tsx
- src/components/app/pagePetitionDetails/debugger/petitionMilestonesEditor.tsx
- src/components/app/pagePetitionDetails/debugger/useMockedPetitionData.ts
- src/components/app/pagePetitionDetails/index.tsx
- src/components/app/pagePetitionDetails/milestones/index.tsx
- src/components/app/pagePetitionDetails/milestones/milestones.stories.tsx
- src/components/app/pagePetitionDetails/pagePetitionDetailsWithDebugger.tsx
- src/components/app/pagePetitionDetails/signatoriesCarousel/index.tsx
- src/components/app/pagePetitionDetails/signatureContext.tsx
- src/components/app/pagePetitionDetails/summary/index.tsx
- src/components/app/pagePetitionDetails/summary/summary.stories.tsx
- src/components/app/pagePetitions/card/index.tsx
- src/components/app/pagePetitions/debugger/index.tsx
- src/components/app/pagePetitions/debugger/petitionsDataEditor.tsx
- src/components/app/pagePetitions/index.tsx
- src/components/app/pagePetitions/pagePetitionsWithDebugger.tsx
- src/components/app/pagePetitions/petitionsContent.tsx
- src/components/app/userActionFormPetitionSignature/constants.ts
- src/components/app/userActionFormPetitionSignature/dialog.tsx
- src/components/app/userActionFormPetitionSignature/header.tsx
- src/components/app/userActionFormPetitionSignature/index.tsx
- src/components/ui/badgesAutomaticCarousel/index.tsx
- src/hooks/useIsPetitionSigned.ts
This PR introduced some features and fixed the bug bash issues.
- Created the DEBUGGER feature (to run on preview and local environments and allow mocking values).
- Fixed all the [bug bash](https://docs.google.com/document/d/1lnny89tU0RcQWvWR5DghXTdL3jeWhOvngsxQcALkhxE/) issues.
**All the debugger related code was AI generated.**
> feature: final adjusts

- next.config.ts
> feat: add new email redirection rule for clarity act

- src/utils/server/externalOptIn/handleExternalUserActionOptIn.ts
- src/utils/server/sms/actions.ts
> feat: delay comms in 5h for idv upsell signups

- src/components/app/userActionFormEmailCongressperson/us/campaigns/20250918-usdc-rewards.tsx
- src/components/app/userActionFormEmailCongressperson/us/campaigns/index.ts
- src/components/app/userActionGridCTAs/constants/us/usCtas.tsx
- src/utils/shared/urlsDeeplinkUserActions.ts
- src/utils/shared/userActionCampaigns/us/usUserActionCampaigns.ts
Reverts Stand-With-Crypto/swc-web#2734
> Revert "chore: remove USDC Rewards campaign files and references from the cod…"

- src/components/app/navbarGlobalBanner/us/currentCampaign.tsx
- src/utils/shared/urls/index.ts
- Added USDC banner campaign to US.
> feat: add USDC Rewards campaign banner and URL generation

- src/app/api/public/swc-civic/electoral-zone/by-address/route.ts
> feat: add waitUntil to update address location logic

- src/app/eu/[language]/community/activity/[[...page]]/page.tsx
- src/app/eu/config.tsx
- src/components/app/pageCommunity/eu/constants.tsx
- src/components/app/pageCommunity/eu/getPageData.ts
- src/components/app/pageCommunity/eu/index.tsx
- src/components/app/pageHome/eu/recentActivityAndLeaderboardTabs.tsx
- src/utils/shared/urls/externalUrls.ts
closes #2715
- Created the EU community page with recent activity
> feature: create EU community page
