- src/actions/actionCreateUserActionLiveEvent.ts
- src/components/app/userActionFormLiveEvent/claimNft.tsx
Display informative error message in live event action flow when the event is not live yet or inactive.
**UI changes**
_Web_
type=routine 
risk=low 
impact=sev5
> [trivial] Display live event server action error message

- .github/workflows/cypress.yml
This PR enables Cypress in pull requests. Why? Because we have recently implemented a local MySQL database _specifically_ for Cypress tests, so now we have a simple and deterministic way of accessing entries in a database for Cypress tests.
CI passes.
type=routine 
risk=low 
impact=sev5
> [feature] enable Cypress in pull requests

- src/actions/actionCreateUserActionCallCongressperson/index.ts
- src/actions/actionCreateUserActionEmailCongressperson.ts
- src/actions/actionCreateUserActionLiveEvent.ts
- src/actions/actionCreateUserActionTweet.ts
- src/actions/actionCreateUserActionVoterRegistration.ts
- src/data/verifiedSWCPartners/userActionOptIn.ts
- src/utils/server/serverAnalytics/serverAnalytics.ts
We'll use [this report in mixpanel](https://mixpanel.com/project/3191713/view/3702825/app/insights#report/52770313/ratio-of-actions-created-to-duplicate-action-attempts) to flag any weird ratios of duplicate/real actions occurring
type=routine 
risk=low 
impact=sev5
> remove sentry warnings, use mixpanel ratio report instead

- src/app/api/internal/commerce-webhook/route.ts
- src/utils/server/coinbaseCommerce/paymentRequest.ts
- src/utils/server/coinbaseCommerce/storePaymentRequest.ts
Relates to #615.
This PR attempts to fix the Coinbase Commerce webhook events <> Mixpanel by getting the local user from the user. Why? Because we want to be able to associate webhook events to a user.
Some other changes:
- this PR now track the UserAction creation for the donation
- this PR implements some bug fixes regarding fetching the pricing values from the webhook event
- this PR now correctly adds the other user data (crypto address, email address, and session if available) to the `UserAction`
_Tested with logged-in user_:
https://github.com/Stand-With-Crypto/swc-web/assets/135282747/2923036e-85cc-4f0d-bd91-bd4b10548f54
_Tested with logged-out user_: …
> [bug] fix Coinbase Commerce webhook events <> Mixpanel and add additional user data for donation `UserAction`s

- src/app/api/inngest/route.ts
- src/bin/oneTimeScripts/cleanupPostalCodes.ts
- src/bin/oneTimeScripts/setPrimaryCryptoAddressOfUser.ts
- src/inngest/functions/cleanupPostalCodes.ts
- src/inngest/functions/setPrimaryCryptoAddressOfUser.ts
- src/inngest/onScriptFaillure.ts
Added a new inngest function to update user primary crypto address in case of users having multiple crypto addresses but have the wrong one as primary.
**UI changes**
type=routine 
risk=low 
impact=sev5
> Add new inngest function to update user primary crypto address

- src/actions/actionCreateUserActionCallCongressperson/index.ts
- src/actions/actionCreateUserActionEmailCongressperson.ts
- src/actions/actionCreateUserActionLiveEvent.ts
- src/actions/actionCreateUserActionTweet.ts
- src/actions/actionCreateUserActionVoterRegistration.ts
- src/utils/server/getMaybeUserAndMethodOfMatch.ts
fixes #662 
This was a typescript issue. Since now we have sessions with only validated emails, those users won't have a `userCryptoAddress`, that said previously we were forcing the user match type so the crypto address were not nullable.
This changes that type and also changes how we check if it exists from `'userCryptoAddress' in userMatch` to `'userCryptoAddress' in userMatch && userMatch.userCryptoAddress`. Both are necessary bc TS uses the first check to infer the type of `userMatch` (it is an union of two types) and the second one to actually check if we have the property set. (noting that `'a' in { a: null }` is true)
type=routine 
risk=low 
impact=sev5
> fix: add validation for not null crypto address

- .github/PULL_REQUEST_TEMPLATE.md
- public/logo/shield-black-bg.svg
- src/app/[locale]/questionnaire/page.tsx
- src/utils/shared/urls.tsx
closes #656 
This creates the questionnaire CTA page
This also changes the PR template to have closing keywords for sentry and github issues
**UI changes**
_Web_
_Mobile Web_
type=routine 
risk=low 
impact=sev5
> Questionnaire Splashpage

- cypress/e2e/3-page-politicians.cy.ts
- cypress/e2e/4-action-email-your-congressperson.cy.ts
- src/data/dtsi/fetchDTSI.ts
- src/mocks/dtsi/mockResolvers/dtsiPersonRoleResolver.ts
- src/mocks/dtsi/queryDTSIMockSchema.ts
Since we did a new mocking structure to dtsi running locally, some changes had to be made to cypress to adapt to it instead of the real api
type=routine 
risk=low 
impact=sev5
> tests: change tests to adapt to dtsi mocks

- src/app/api/internal/manually-revalidate-path/route.ts
Allow core contributors to revalidate cached endpoints manually. Useful when theres a bug that was fixed but is still cached.
type=routine 
risk=low 
impact=sev5
> Add "manually revalidate paths" endpoint

- src/utils/shared/googleCivicInfo.ts
fixes PROD-SWC-WEB-K9
In [this issue](https://stand-with-crypto.sentry.io/issues/4947101303/?environment=production&project=4506490717470720&query=is%3Aunresolved+timesSeen%3A%3E%3D10&referrer=issue-stream&statsPeriod=30d&stream_index=0) the results return a rep whos firstname differs from DTSI (its an abbreviation) ![image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/30ecfca4-9323-48d4-83c0-e82b39cb8533)
This fallback logic ensures we match in this case.
type=routine 
risk=low 
impact=sev5
> [fix] fallback to matching DTSI to google civic API by just last name

- src/bin/smokeTests/onNewLogin/9testCaseWithLongAcquisitionReferrer.ts
- src/bin/smokeTests/onNewLogin/index.ts
- src/bin/smokeTests/onNewLogin/utils.ts
- src/utils/server/serverLocalUser.ts
closes https://github.com/Stand-With-Crypto/swc-web/issues/676
fixes https://stand-with-crypto.sentry.io/issues/5067506303/?referrer=github_integration
Trim the acquisition referer when greater than 191 characters. 
type=routine 
risk=low 
impact=sev5
> Trim char for Acquisition referer

- src/utils/server/thirdweb/fetchCurrentClaimTransactionFee.ts
Relates to #600 
This is a small PR that reduces the gas limit override for transaction fee estimations. Why? Because looking at the used gas limit for the past transactions, they are lower than the current override.
**UI changes**
No UI changes.
N/A
type=routine 
risk=low 
impact=sev5
> [feature] reduce gas limit for transaction fee estimation in NFT backfill cron job

- src/inngest/functions/airdropNFT.ts
- src/utils/server/nft/updateMintNFTStatus.ts
This PR removes storing the transaction's gas price in our MySQL database for NFT airdrops. Why? Because the `cost_at_mint` column should record the cost when a user spends their own funds to mint an NFT (at the moment, that is only the supporter NFT) - airdrops do not involve user funds, so technically the cost at mint is 0.
**UI changes**
No UI changes.
We need to write a script to set the `cost_at_mint` and `cost_at_mint_usd` fields to be 0 for `nft_mint` rows where `nft_slug NOT IN ('stand-with-crypto', 'stand-with-crypto-supporter')`
type=routine 
risk=low 
impact=sev5
> [bug] remove storing gas price in MySQL database for NFT airdrops 

- src/components/app/pageDonate/donateButton.tsx
- src/components/app/pageUserProfile/mergeAlertCTA.tsx
- src/components/app/userActionFormCallCongressperson/sections/suggestedScript.tsx
- src/components/app/userActionFormEmailCongressperson/index.tsx
- src/components/app/userActionFormLiveEvent/claimNft.tsx
- src/components/app/userActionFormNFTMint/sections/transactionWatch.tsx
- src/components/app/userActionFormVoterRegistration/sections/claimNft.tsx
- src/utils/server/withServerActionMiddleware.ts
- src/utils/web/formUtils.ts
closes https://github.com/Stand-With-Crypto/swc-web/issues/670
fixes [PROD-SWC-WEB-18Q](https://stand-with-crypto.sentry.io/issues/5029315222/?referrer=github_integration)
I added a check of the result of an action in withServerActionMiddleware function and throw an error if the result is undefined. This is to avoid reading a field of an undefined result on the client side.
I don't think I fully understand the promises in javascript. So I an not fully confident of my solution here. 
I was able to test it on local, but not sure how I can test this on Preview
type=routine 
risk=low 
impact=sev5
> Handle undefined result from action

- src/app/api/internal/commerce-webhook/route.ts
- src/bin/smokeTests/nft/airdropNFT.ts
- src/inngest/functions/airdropNFT.ts
- src/inngest/functions/backfillNFT/logic.ts
- src/inngest/functions/backfillNFTCronJob/index.ts
- src/utils/server/nft/claimNFT.ts
- src/utils/server/nft/payload.ts
- src/utils/shared/airdropNFTETHTransactionFeeThreshold.ts
Closes #600 
Closes #704 
This PR reenables the conditional live airdrop (where the condition is that the current estimated transaction fee is under a defined threshold). Why? Because ideally we want the user to receive their NFT as soon as possible, but we also do not want to spend too much ETH on airdrop transaction fees. Thus, we perform the live airdrop if transaction fees are low - otherwise, we will skip the live airdrop and let the NFT backfill cron job airdrop the NFT at a later point.
This PR also returns a proper response from the NFT backfill cron job that includes the stop reason and the remaining number of NFT user actions in the backfill backlog. Why? So we can easily audit the result of any run and to see the trend of backlogged user actions.
**UI …
> [feature] reenable conditional live airdrop and return proper response for NFT backfill cron job

- src/inngest/functions/backfillNFTCronJob/index.ts
Relates to #600 
Closes #703 
This PR adds a Sentry alert when there is an old (eligible) user action that is still missing their NFT. Why? Because we want to be able to audit if our NFT backfill cron job is having issues and make any environment variable adjustments (_e.g._ during an extended bull market when fees may stay high for a long period of time).
No UI changes.
- We only fetch for the first oldest action because that's all we need
- The threshold for being old is set to 3 days in the past
- If there is no user action, then we just `return` because we are all caught up
type=routine 
risk=low 
impact=sev5
> [feature] add alert when there is an old (eligible) user action that is still missing their NFT

- src/components/app/userActionFormCallCongressperson/sections/intro.tsx
- src/components/app/userActionFormCallCongressperson/sections/suggestedScript.tsx
closes #693 
This PR is a simple changes that prevents automatic scrolling to the bottom of the modal when the `useEffect` hook focus on the modal. Why? Because it's annoying that the scroll state goes to the very bottom.
This issues seems to only impact the "call rep" flow.
_Web before_:
https://github.com/Stand-With-Crypto/swc-web/assets/135282747/580d2a05-921f-4425-9bab-6b1a7beb6777
_Web after_:
https://github.com/Stand-With-Crypto/swc-web/assets/135282747/8258cb56-06ec-402c-8df4-c8eb461ac5a0
_Mobile before_:
https://github.com/Stand-With-Crypto/swc-web/assets/135282747/65fa472c-1130-47d4-bd8b-43b9727bed10
_Mobile after_:
https://github.com/Stand-With-Crypto/swc-web/assets/135282747/4ab21b74-3063-4f62-9ab3-539a3dc2b09e
N/A
type=routine 
risk=low …
> [bug] prevent automatic scrolling when focusing on modal

- docs/Contributing.md
This PR fixes two incorrect links in contributing documentation inside the "knowledge pre-requisites" section by removing unnecessary `/docs` from each link.
closes #719 
@travisbloom-cb could you please review this PR? Thank you!
> docs: updates knowledge pre-requisites links in contributing guideline

- prisma/schema.prisma
relates to #660 
This is a small PR that includes a MySQL index for the `datetime_created` field. Why? Because for the auditing cron job, I am planning to audit in batches of users in order of `datetime_created`.
Why `datetime_created`? In my opinion, that is the ideal field to use in order to _not_ skip any user rows when iterating through batches of users.
N/A
From my local branch to `testing`: https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/12
N/A
type=routine 
risk=low 
impact=sev5
> [feature] include MySQL index for `datetime_created` field

- src/actions/actionCreateUserActionNFTMint.ts
This is a super simple PR that changes the NFT slug within the NFT mint flow from `'swc-shield'` to `'stand-with-crypto-supporter'`. Why? Because the `'swc-shield'` slug is the NFT that is _airdropped_ to all users who log-in, which is not the same as the _manually purchased_ NFT from the mint flow.
No UI changes.
N/A
type=routine 
risk=low 
impact=sev5
> [bug] change NFT mint flow's NFT slug from `'swc-shield'` to `'stand-with-crypto-supporter'`

- src/app/api/inngest/route.ts
- src/inngest/functions/cleanupNFTMints/index.ts
- src/mocks/models/mockNFTMint.ts
closes internal ticket 14
unblocks #660 
This PR implements a one-time Inngest script to clean up "non-user-funded" NFT mints by resetting the `cost_at_mint` and `cost_at_mint_usd` back to 0 for NFT mints that are not funded by the users. Why? Because the currently stored information is not correct and should be reset appropriately, and #660 is soft-blocked by this.
No UI changes.
This PR also updates the mock NFT mint to only include "cost at mint" for user-funded mints.
Video demo (only accessible by Coinbase employees): https://drive.google.com/file/d/1ezFDfyVomdfIjzp6iFNWx-AfcTPODPCQ/view?usp=sharing
https://github.com/Stand-With-Crypto/swc-web/assets/135282747/b233f8f0-279e-4f02-b221-db62e3dbb4ee
type=routine 
risk=low 
impact=sev5
> [feature] implement one-time Inngest script to clean up "non-user-funded" NFT mints 

- prisma/schema.prisma
- src/actions/actionCreateUserActionCallCongressperson/index.ts
- src/actions/actionCreateUserActionEmailCongressperson.ts
- src/actions/actionCreateUserActionLiveEvent.ts
- src/actions/actionCreateUserActionTweet.ts
- src/actions/actionCreateUserActionVoterRegistration.ts
- src/actions/actionUpdateUserProfile.ts
- src/data/verifiedSWCPartners/userActionOptIn.ts
- src/mocks/models/mockUser.ts
- src/utils/server/coinbaseCommerce/storePaymentRequest.ts
- src/utils/server/thirdweb/onLogin.ts
relates to internal issue 16
This PR adds a new `hasRepliedToOptInSms` field for the users table. Why? Because even though a user has opted-in via the SWC website, they may not respond to the SMS message from Capitol Canary. Responding to the SMS message is how an advocate can _fully_ opt into SMS messaging, thus we need to keep track of that.
This PR also fixes two Capitol Canary SMS opt-in bugs:
- We were accidentally marking the Capitol Canary advocate as an explicitly SMS opt-out if the respective SWC user supplied their phone number without checking the opt-in checkbox
- We were also accidentally opting out the _new_ phone number if the SWC user changed their phone number
This is important because Capitol Canary does not allow advocates to opt back into SMS (we should really talk to …
> [feature + bug] add new `hasRepliedToOptInSms` field for users table, and fix Capitol Canary SMS opt-in bug

- prisma/schema.prisma
relates to internal issue 16
This is a small PR that adds the default value for the new boolean field. Why? Because PlanetScale requires a default value for newly added fields - otherwise, a deploy request will fail (see [failed request](https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/14)).
No UI changes.
From my DB branch to `testing`: https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/16
Nothing to note.
type=routine 
risk=low 
impact=sev5
> [feature] add default value for `hasRepliedToOptInSms` field

- src/actions/actionUpdateUserProfile.ts
relates to internal issue 16
This PR fixes a bug(?) related to the Capitol Canary SMS opt-outs where, if a user is inputting a new phone number, then we only want to _explicitly_ opt-out a user's old phone number from SMS if their old phone number was _explicitly_ opted-in. Why? This is also to work around some Capitol Canary limitations around opt-ins/outs.
No UI changes.
No notes.
type=routine 
risk=low 
impact=sev5
> [bug] fix bug related to Capitol Canary SMS explicit opt-outs 

- src/components/app/authentication/thirdwebLoginContent.tsx
- src/components/app/userActionFormEmailCongressperson/index.tsx
- src/components/app/userActionFormEmailCongressperson/skeleton.tsx
This is a small PR that updates the external link for the Quorum Privacy Policy. Why? Because the current link leads to a dead (404) page now. Also, looking at Wayback Machine, the existing privacy policy is from 2014, but there are newer revisions of their privacy policy.
_OLD_:
https://github.com/Stand-With-Crypto/swc-web/assets/135282747/047d9655-d380-49fd-89dd-993a66a80c87
_NEW_:
https://github.com/Stand-With-Crypto/swc-web/assets/135282747/70a937a8-6718-4f97-9358-a582558e2925
No specific notes.
type=routine 
risk=low 
impact=sev5
> [bug] update external link for Quorum Privacy Policy

- src/components/app/dtsiAvatar.tsx
- src/hooks/useGetDTSIPeopleFromAddress.ts
closes 
fixes https://stand-with-crypto.sentry.io/issues/5055966004/?environment=production&project=4506490717470720&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=3
Bug with our type definitions
- [ \X] Locally
type=routine 
risk=low 
impact=sev5
> fix crash that occurs when api fails

- src/app/api/inngest/route.ts
- src/inngest/functions/capitolCanary/backfillSMSOptInReply.ts
- src/utils/server/capitolCanary/fetchAdvocates.ts
- src/utils/server/capitolCanary/payloadRequirements.ts
closes internal issue 16
This PR implements an Inngest script that will backfill the SMS reply flag for the SWC users using all the Capitol Canary advocate information. Why? Since [this PR](https://github.com/Stand-With-Crypto/swc-web/pull/738) is already merged, we should update the SWC users that have already existed before the PR.
No UI changes.
This script is implemented with the limitations of Inngest and Vercel in mind. This script is also design to run ad-hoc.
Used a testing database that contains production information and the production Capitol Canary API credentials.
type=routine 
risk=low 
impact=sev5
> [feature] implement script to backfill SMS reply flag for SWC users

- src/components/ui/googlePlacesSelect/index.tsx
- src/hooks/useGoogleMapsScript.ts
- src/hooks/usePlacesAutocompleteAddress.ts
closes #748
fixes PROD-SWC-WEB-1NK
Since we now add the google maps script without `PLACES_AUTOCOMPLETE` as callback (that's because it isn't defined) we started getting an undefined callback error when we tried to load a second `script`, to solve that we're just removing manually setting this name in `usePlacesAutocomplete` and using the default `Function.prototype` for all use cases. That should stop rendering multiple `script` tags.
type=routine 
risk=low 
impact=sev5
> fix: remove setting the callback name for use-places-autocomplete

- src/app/api/verified-swc-partner/get-user-metadata/[emailAddress]/route.ts
- src/data/verifiedSWCPartners/getUserMetadata.ts
New endpoint verified partners can leverage to deep link users in to the app
type=routine 
risk=low 
impact=sev5
> endpoint for verified partners to get back session/user ids

- src/app/api/verified-swc-partner/get-user-metadata/route.ts
on testing, passing an email address with "+" and other url-used characters causes weird behavior (not seen on local). Converting this to a POST request to reduce these edge cases. 
type=routine 
risk=low 
impact=sev5
> convert get-user-metadata endpoint to POST to remove unpredictability of escaping GET params

- src/utils/shared/googleCivicInfo.ts
fixes https://stand-with-crypto.sentry.io/issues/4947101303/?environment=production&project=4506490717470720&query=is%3Aunresolved+timesSeen%3A%3E%3D10&referrer=issue-stream&statsPeriod=30d&stream_index=3
Reps like cherfilus-mccormick have a dash in DTSI but no dash in google civic api. This fix ensures we can fuzzy match them accurately.
type=routine 
risk=low 
impact=sev5
> match reps who have dashes in dtsi but no dashes in google

- src/utils/shared/phoneNumber.test.ts
- src/utils/shared/phoneNumber.ts
- src/validation/fields/zodPhoneNumber.ts
Adds support for international phone number to the default zod field schema. This is causing coinbase 1-click signup registrations to fail
type=routine 
risk=low 
impact=sev5
> fix: add support for international phone numbers on zodPhoneNumber schema

- src/components/app/authentication/maybeAuthenticatedContent.tsx
- src/components/app/userActionFormNFTMint/sections/intro.tsx
- src/validation/fields/zodPhoneNumber.ts
This small PR fixes the "mint NFT" flow when "logged-in" using user ID + session ID query parameters. Why? Because currently the "mint NFT" will hang due to incorrect log-in checks.
_BEFORE_:
https://github.com/Stand-With-Crypto/swc-web/assets/135282747/9d3e1ddc-c0cc-4bed-9b2d-cc31a5679663
_AFTER_:
https://github.com/Stand-With-Crypto/swc-web/assets/135282747/e673ae1e-a0ca-49bb-bd98-2bab2fcdf0a3
No notes.
type=routine 
risk=low 
impact=sev5
> [bug] fix "mint NFT" flow when "logged-in" as session user

- src/components/ui/googlePlacesSelect/index.tsx
Reverted the removal of whitespace-normal in google places select component
type=routine
risk=low
impact=sev1
> Fix: google places select overflowing

- cypress/e2e/6-donation-card-redirect.cy.ts
- src/components/app/navbar/index.tsx
- src/components/app/pageDonate/donateButton.tsx
- src/components/app/userActionRowCTA/constants.tsx
- src/utils/shared/activeUserAction.ts
- src/utils/shared/urlsDeeplinkUserActions.tsx
- src/utils/web/userActionUtils.ts
Our donation's provider is currently down. Disabling our main CTAs until they're back online.
type=routine 
risk=low 
impact=sev5
> disable donation CTAs until re-enabled

- src/components/app/cryptoSupportHighlight/index.tsx
- src/components/app/pagePoliticianDetails/index.tsx
- src/utils/dtsi/dtsiStanceScoreUtils.ts
fix bug where stances were being shown as pending when score was zero
| ![image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/db82e514-c805-4da4-bd8a-72d23b3ee7bb) | ![image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/232807ad-9863-4ff9-b678-2e67e4bfd2bb) |
type=routine 
risk=low 
impact=sev5
> fix bug where stances were being shown as pending when score was zero

- .github/PULL_REQUEST_TEMPLATE.md
Two main things driving this simplification:
- We want our PR template to be friendly to the open source community who might not have context in to internal norms
- Because we have vercel preview branches, made the template more focused on leaning on that feature for UX review
> simplify our pull request template

- docs/Contributing.md
Re-adds the mysql install instruction to Contributing doc so that developers are able to run E2E tests.
> Docs: re-adds mysql install instruction

- src/app/[locale]/(homepageDialogDeeplink)/action/nft-mint/page.tsx
- src/app/[locale]/(homepageDialogDeeplink)/action/sign-up/page.tsx
- src/app/[locale]/topLevelClientLogic.tsx
- src/components/app/userActionFormCallCongressperson/homepageDialogDeeplinkWrapper.tsx
- src/components/app/userActionFormEmailCongressperson/homepageDialogDeeplinkWrapper.tsx
- src/components/app/userActionFormEmailCongressperson/index.tsx
- src/components/app/userActionFormLiveEvent/homepageDialogDeeplinkWrapper.tsx.tsx
- src/components/app/userActionFormNFTMint/homepageDialogDeeplinkNFTMintWrapper.tsx
- src/components/app/userActionFormVoterRegistration/homepageDialogDeeplinkWrapper.tsx
- src/hooks/usePreventOverscroll.ts
closes #787
- Even though there is a CSS property called overscroll that should prevent the background scrolling behavior, it didn't work in any scenario that I tested. 
P.S.: I also didn't remove the homepage content from the background because on desktop the user can see what is behind the modal because it is not full height/width
> Prevents overscroll on deeplinks

- src/components/app/pagePoliticianDetails/generateOgImage.tsx
- src/components/app/updateUserProfileForm/step1.tsx
> increase font-size for politician og-images, and fix spacing bug on profile form

- src/components/app/userActionFormEmailCongressperson/index.tsx
Returning email modal to be full height only on mobile. Tested the homepage modal and action flow on desktop and mobile and everything is working as expected.
> style: fixing email modal height

- src/components/app/userActionFormEmailCongressperson/index.tsx
- src/components/ui/combobox.tsx
- src/components/ui/dialog/index.tsx
closes 
#818 
fixes
- Disabled radix-ui Dialog's default behavior of auto-focusing on its first focusable child when opened.
- Focus on input only on Desktop devices.
This behavior was impacting different flows, but just one of them was focusing on a input (`UserActionFormEmailCongressperson`).
> Do not auto-focus inputs for actions on mobile

- src/components/ui/combobox.tsx
- src/hooks/usePreventMobileKeyboardOffset.ts
closes 
[#37](https://github.com/Stand-With-Crypto/swc-internal/issues/37)
fixes 
This is a known issue regarding the keyboard in iOS devices because the component is not resized to fit the screen height when using `100dvh` but instead it behaves like `100vh` and the keyboard offsets the content to top. The only way I found to fix this problem is making the entire screen scroll to top, so I had to save the current scroll height, scroll the entire page to the top and then scroll the page back to the previous scroll value after the modal is closed.
https://github.com/Stand-With-Crypto/swc-web/assets/167922524/234ac6c2-7ce3-425f-b051-81b1798a3cc5
https://github.com/Stand-With-Crypto/swc-web/assets/167922524/d41a6962-a880-4be4-af2c-1fbb54bc2b4a
I used sessionStorage instead of a state because …
> iOS keyboard offsetting the address input dialog

- .env.example
- src/app/api/internal/commerce-webhook/route.ts
- src/app/api/internal/in-app-donations/route.ts
- src/utils/server/coinbaseCommerce/createCharge.ts
closes #222 
This PR introduces `createInAppCharge` function copying functionality of backend endpoint for in app donations  from SwC V1.
@travisbloom-cb @lucasrmp-cb should this function also accept `userId` and `sessionId` like `createCharge`? I exposed `api/internal/in-app-donations`, not sure though if this is right approach if we're planning to add frontend to this feature.
It was tested via running local server and curling endpoint to hit commerce v2 api (I was only able to migrate my account to prod on commerce beta/api - commerce dev env still responds with v1 api):
`data_swc.json` file
```json
{
"address": "My test address, 11-111",
"email": "my-test-email@coinbase.com",
"employer": "Coinbase",
"full_name": "John Doe",
"is_citizen": false,
"occupation": "occupation test"
}
``` …
> feature: migrate v1 inAppDonations to swc v2

- src/components/app/dtsiCongresspersonDisplay.tsx
closes #832 
Adds padding bottom to DtsiCongresspersonDisplay component to prevent the absolute positioned content from being cut off because of container padding.
> Adds padding to Dtsi Congressperson display to prevent absolute content from not showing

- cypress/e2e/3-page-politicians.cy.ts
- src/components/app/dtsiClientPersonDataTable/columns.tsx
- src/components/app/dtsiClientPersonDataTable/dataTable.tsx
- src/components/app/dtsiClientPersonDataTable/filters.ts
- src/components/app/dtsiClientPersonDataTable/globalFiltersUtils.tsx
- src/components/app/dtsiClientPersonDataTable/index.tsx
closes #568
Fixed broken e2e test for politicians page.
The test was breaking because Cypress flags the button as not-actionable due to it being outside the viewport. To fix it, we only need to call `scrollIntoView()`. Another option is to use `click({ force: true })` to skip visibility checks, but that's not ideal.
But theres another problem:
Interacting with the filters too fast may introduce too many rerenders and break the test. One band-aid solution would be to call `cy.wait()` after every filter is applied. However, the ideal solution is to let react-table handle the filters state.
I refactored the way filters are handled to be more in line with the react-table documentation. By doing so, rerenders have been reduced and there's no need for `cy.wait()` calls.
type=routine 
risk=low …
> Fix politicians page e2e tests

- src/utils/server/getGooglePlaceIdFromAddress.ts
closes #632 
fixes PROD-SWC-WEB-1HJ
This encodes the `address` query param in the google places api call. Why? That was causing problems with addresses that contained a `#` sign
> fix: encode address on google api call

- cypress/e2e/4-action-email-your-congressperson.cy.ts
- cypress/e2e/8-action-call-your-congressperson.cy.ts
- src/components/app/dtsiPersonHeroCard/dtsiPersonHeroCard.stories.tsx
- src/components/ui/googlePlacesSelect/index.tsx
closes #850 
Added some type validations for google places api results to prevent returning vague addresses that would cause Capitol Canary to fail.
> feat: adds type validation for google places api results

- src/validation/forms/zodEmailYourCongressperson.ts
- src/validation/forms/zodUserActionFormEmailCongressperson.ts
We made the validation error message more clear for max length email messages. Reported by this tweet:
https://twitter.com/jastirn/status/1790459417701323012
> fix(email): change message for max length message

- src/app/api/identified-user/performed-user-action-types/route.ts
- src/components/app/recentActivityRow/variantRecentActivityRow.tsx
- src/components/app/userActionFormSuccessScreen/getNextAction.tsx
- src/components/app/userActionFormSuccessScreen/userActionFormSuccessScreenMainCTA.tsx
- src/components/app/userActionRowCTA/userActionRowCTAsAnimatedListWithApi.tsx
- src/components/app/userActionRowCTA/userActionRowCTAsListWithApi.tsx
closes #875 
This PR changes how we calculate the next action suggestion based on performed user actions. Now we are also checking if the user has completed X action from the current campaign.
> Calculates next action using campaign

- src/clientModels/clientAddress.ts
- src/components/app/userActionFormCallCongressperson/index.tsx
- src/components/app/userActionFormEmailCongressperson/index.tsx
This PR updates address default value condition to check if a route property is present in user.address. The objective is to reduce errors related to address not found on google api.
> Updates address default value condition

- src/components/app/pagePoliticianDetails/questionnaireAccordion.tsx
- src/hooks/useUrlHash.ts
closes #864 
This PR removes all async conditions evaluation from questionnaire component to remove possible layout shifts.
> feat: removes async code to remove layout shift

- cypress/e2e/8-action-call-your-congressperson.cy.ts
- src/components/app/userActionFormCallCongressperson/sections/suggestedScript.tsx
closes #887
This adds a phone number display and removes the "call complete" guard from the desktop version of the call action.
Mobile shouldn't change
> feat: add phone number display to desktop call action

- src/components/app/pageBills/index.tsx
ensure key bills are displayed ordered at the top of the bills page
> ensure key bills are displayed ordered at the top of the bills page

- next.config.js
- src/app/[locale]/topLevelClientLogic.tsx
There are lingering broken URLs users are getting sent to. We want to gracefully fail when they land on SWC.
> gracefully fail when user gets sent to broken url

- src/components/app/clientCurrentUserDTSIPersonCardOrCTA.tsx
- src/components/app/dtsiCongresspersonAssociatedWithFormAddress.tsx
- src/components/app/pageLocationStateSpecific/userLocationRaceInfo.tsx
- src/components/app/pageLocationUnitedStates/userAddressVoterGuideInput.tsx
- src/components/app/userActionFormCallCongressperson/sections/address/index.tsx
- src/hooks/useGetDTSIPeopleFromAddress.ts
- src/hooks/useGetDistrictFromAddress.ts
- src/utils/shared/getCongressionalDistrictFromAddress.ts
closes #899 
fixes 
When user does not have an address we were still making the request to the API because we passed an empty string and did not prevent the request from being made in these cases. This PR prevents this from happening and makes more clear that addresses can be `null` or `undefined`.
> Minimize Google Civic Api usage

- src/components/app/userActionFormSuccessScreen/hasOptedInToMembershipForm.tsx
closes #589 
Changed a go back button to an arrow icon on top left of the dialog
> Changes go back to a top left arrow icon

- src/app/api/internal/manually-revalidate-path/route.ts
closes #886 
Changes manually-revalidate-path route to support all locales
> Adds locale support for manually revalidate path

- package-lock.json
- package.json
- src/app/[locale]/layout.tsx
closes #91
This PR adds the NextJS Loader lib to SWC after this [issue](https://github.com/TheSGJ/nextjs-toploader/issues/66) has been resolved.
> Adds Nextjs Loader

- src/hooks/useGetDTSIPeopleFromAddress.ts
- src/utils/shared/getCongressionalDistrictFromAddress.ts
closes #914 
This PR removes the DC lock that blocked the DC residents from using the email and call flow
> Ensures Call and Email flow works for DC residents

- sentry.client.config.ts
- src/hooks/useHandlePageError.ts
closes #848 
This PR tries to add a conditional to don't log the errors caused by outlook bots from showing up in sentry and mixpanel.
> Prevent Outlook error spikes

- src/components/app/userActionFormNFTMint/sections/checkout/index.tsx
This changes how we check if the user has a connected wallet in the checkout step of the nft mint action. Why? Seems like `useAddress` has some inconsistency where it is not returning for valid addresses.
> fix: change session check to useSession on nft mint

- src/utils/web/clientExperiments.ts
fixes 
When we randomly get an experiment variant based on their percentages we are correctly getting a random variant but when returning it, we always select the first variant that turns out to be the control variant. This PR fixes it.
> Fix experiments always returning the control variant

- src/actions/actionUpdateUserHasOptedInSMS.ts
Not sure if the `shouldSendSmsOptinConfirmation: true` should be sent. cc @travisbloom-cb
> Trigger capitol canary on sms opt in

- next.config.js
closes #934 
This PR adds a new header to control cache following the nextjs documentation for image [optimization](https://nextjs.org/docs/app/api-reference/components/image#caching-behavior)
> Adds cache header for images

- cypress/e2e/07-action-voter-registration.cy.ts
- cypress/e2e/11-action-mint-your-supporter-nft.cy.ts
- cypress/support/commands.ts
#951
closes 
fixes 
adds a login command in cypress to ease the usage throughout other user actions
ex.: `cy.waitForLogin({ trigger: cy.get('button[type="button"]').contains('Join To Claim NFT') })`
> test: add cypress login command

- src/hooks/useHandlePageError.ts
This PR is a new attempt to try to catch the outlook error using [this](https://github.com/getsentry/sentry-javascript/issues/3440#issuecomment-828834651) suggestion as reference.
> New attempt to try to catch outlook error

- src/app/[locale]/layout.tsx
- src/components/app/pageHome/index.tsx
- src/components/app/ukDisclaimerBanner/ukDisclaimerBanner.tsx
- src/utils/shared/urls/index.ts
#952
closes 
fixes 
- adds a banner to disclaim the new UK stand with crypto website.
- mobile version the banner becomes clickable in its entirety
> feat: add uk website disclaimer with link

- .env.example
- src/bin/reports/generateCommitReportByPerson.ts
- src/bin/reports/generateProjectData.ts
closes [#49
](https://github.com/Stand-With-Crypto/swc-internal/issues/49)
Created two new scripts to export project data 
You need to create a new env variable named GITHUB_TOKEN with the classic token created with the correct read privileges. You can create a new token accessing this [link](https://github.com/settings/tokens), selecting `Tokens (Classic)` and then selecting read access to `repo` and `project`, like so:
> Scripts to export project data

- src/components/app/dtsiCongresspersonAssociatedWithFormAddress.tsx
- src/components/app/userActionFormEmailCongressperson/index.tsx
- src/components/app/userActionFormEmailCongressperson/skeleton.tsx
closes #960 
This PR fixes a bug where the dtsiSlugs field value was not being updated correctly when the users closes and then reopens the email flow modal.
> Email message not updating correctly between action modal re-renders

- prisma/schema.prisma
- src/mocks/models/mockUserActionEmailRecipient.ts
This PR adds a new optional emailAddress field for the UserActionEmailRecipient model for the #959 task.
[Deploy Request](https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/22)
> feat: addes a new emailAddress field for UserActionEmailRecipient

- src/app/[locale]/internal/user-action-deeplinks/page.tsx
- src/clientModels/clientUserAction/sensitiveDataClientUserAction.ts
- src/components/app/nftHub/nftDisplay.tsx
- src/components/app/pageUserProfile/index.tsx
- src/components/app/userActionFormSuccessScreen/getNextAction.tsx
- src/components/app/userActionFormSuccessScreen/userActionFormSuccessScreenNextAction.tsx
- src/components/app/userActionRowCTA/constants.tsx
- src/components/app/userActionRowCTA/userActionRowCTAsAnimatedList.tsx
- src/components/app/userActionRowCTA/userActionRowCTAsAnimatedListWithApi.tsx
- src/components/app/userActionRowCTA/userActionRowCTAsList.tsx
- src/components/app/userActionRowCTA/userActionRowCTAsListWithApi.tsx
- src/utils/shared/checkIfUserActionWithCampaignIsComplete.ts
- src/utils/shared/userActionCampaigns.ts
- src/utils/web/userActionUtils.ts
This PR changes how we get the CTA cards and every logic related to that so that we will be able to have more than one CTA from the same action type but with different campaign. For example: we can have the CTA to email the congressperson and another CTA to email CNN about the presidential debate. The idea is to be able to show two or more CTAs with the same action type, but with different campaigns.
This PR is related to the task #959 and it will have a fast follow that will have everything related to creating the email CNN flow.
> Changes SWC CTA logic to include campaigns

- src/hooks/useHandlePageError.ts
The objective is to ensure that the Cause property will be added if the error occurs from newsletter. This will set all email related errors to have this Cause property, but the idea is to make sure that this property will be added when the condition is met. This way, we can guarantee that the problem is how we are trying to handle the error and not something related to MixPanel.
This PR code is temporary. We will try new ways to catch the bug on next PRs
> Investigates if the cause property will show up in MixPanel

- src/app/api/internal/dtsi-updated-slugs-webhook/route.ts
- src/data/dtsi/fetchDTSI.ts
- src/data/dtsi/queries/queryDTSIAllPeople.ts
closes #811 
Didn't find any documentation on NextJS that supports the assumption that we can call revalidatePath for api routes. Because of that, all people DTSI request wasn't updated when the Webhook was called. I checked on NextJS 15 release doc to check if anything like this could be supported in the future, but I didn't find anything.
To be able to handle this cache situation, I decided to use a NextJS feature of revalidating tags for fetch requests. This way, I can revalidate the all people DTSI request based on a tag. It is very similar on how React Query tags work.
Documentation on [revalidateTag](https://nextjs.org/docs/app/api-reference/functions/revalidateTag)
> Changes DTSI API Webhook revalidation logic

- src/components/ui/googlePlacesSelect/index.tsx
closes #973 
Changes text align for google places api input to be left aligned.
> Changes text align to left in address input field

- prisma/schema.prisma
- src/clientModels/clientUserAction/sensitiveDataClientUserAction.ts
This PR updates the prisma schema so that address is not required in UserActionEmail model.
PlaneScale deploy request: https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/24
Related to #980
> Removes address requirement from user action email model

- src/components/app/userActionFormEmailCongressperson/index.tsx
- src/components/ui/googlePlacesSelect/index.tsx
closes #947 
This PR changes the google places api options based on the search results to prevent vague addresses to be used on email flow that would case Capitol Canary to fail when trying to find the related congressperson with the provided address.
> Changes google places select results to be more strict in US

- src/components/app/pageDonate/sumDonationsCounter.tsx
- src/components/app/pageHome/topLevelMetrics.tsx
- src/data/aggregations/getSumDonations.ts
closes #946 
This adds the donations breakdown to SwC and FairShake
> feat: add donations breakdown

- src/app/api/public/dtsi/all-people/route.ts
- src/data/dtsi/fetchDTSI.ts
- src/data/dtsi/queries/queryDTSIAllPeople.ts
This PR changes how we are handling cache in all dtsi route handler.
I was investigating on how caching was handle on the api route: /public/dtsi/all-people and I saw that we are defining the route cache as 10 minutes. This would prevent the revalidateTag logic from working because even though the fetch request was being invalidated, the route would keep returning the cache result for 10 minutes.
As we are able to cache the fetch request based on this doc: https://nextjs.org/docs/app/api-reference/functions/fetch, I decided to change the caching for the api route to be completely dynamic and always hitting the fetch function, but as we moved the 10 minutes revalidate prop into the fetch request, it should keep the same "caching" behavior as the route is just going to call the fetch req …
> Changes caching logic from route to fetch req in all dtsi api route

- src/components/app/pageHome/topLevelMetrics.tsx
closes #1022 
Changed the donated tooltip to work on desktop and mobile.
This fix was inspired by this two issues: https://github.com/radix-ui/primitives/issues/1573#issuecomment-1698975904 and https://github.com/radix-ui/primitives/issues/955#issuecomment-960610209
> Fix donated tooltip behavior not working on mobile

- src/components/app/pageUserProfile/disabledUserActionCampaigns.ts
This PR adds some missing previously used campaigns to prevent the profile page from breaking.
> Adds missing previous campaings

- sentry.client.config.ts
- src/hooks/useHandlePageError.ts
- src/instrumentation.ts
closes #848 
fixes 
- Correctly handle sentry events other than Errors
- Add filtering paramenter do global error page events caused by `ChunkLoadError`
> Deal with error spikes caused by SWC email campaigns

- src/app/[locale]/community/leaderboard/[[...page]]/page.tsx
- src/clientModels/clientUser/clientLeaderboardUser.ts
- src/components/app/pageLeaderboard/constants.tsx
- src/data/aggregations/getSumDonationsByUser.ts
- src/data/pageSpecific/getHomepageData.ts
closes #1044
One of the main reasons why the donation leaderboard page was taking so long to build was related to ENS avatar and name lookups.  As we can't remove the feature of showing the donator ENS information, I added pagination for this page to reduce the amount of ENS lookup calls for each page. We also had an unnecessary DB query that I removed.
> Fix: Leaderboard page build performance

- src/data/web3/getENSDataFromCryptoAddress.ts
- src/utils/shared/raceAll.test.ts
- src/utils/shared/raceAll.ts
closes #1044 
This PR creates a new approach for returning default values for promises inside an Promise.all when a defined maximum timeout is reached. The idea here is to prevent the build page worker on Vercel from killing the build process because a promise was not resolved during the default 60 seconds limit on the Leaderboard page.
> Fix: Leaderboard page build timeout

- src/components/app/userActionRowCTA/constants.tsx
- src/utils/server/getMaybeUserAndMethodOfMatch.ts
closes #1074 
This changes the copy for the email action subtext and fixes a type issue that is blocking builds
> feat: change copy for email subtext

- cypress.config.ts
closes #1046 
This PR addresses the issue of flaky tests that are causing inconsistencies in our CI workflows. To mitigate this, Cypress offers a retry functionality that helps prevent flaky tests from disrupting our deployment cycles. Additionally, there is an experimental feature that allows us to set a maximum number of retries and a minimum number of successful passes, establishing a threshold for a test to be considered successful. In this PR, I’ve implemented this feature by setting the maximum retries to 5 and requiring at least 2 successful runs for a test to be considerate a pass.
[Documentation for this experimental feature](https://docs.cypress.io/guides/references/experiments#Experimental-Test-Retries)
> Defines new strategy to handle `flaky` tests

- next.config.js
closes #1064 
This PR disables the lint step in next build for Vercel deploys to fix the build process being stuck during build some times.
More information around this issue can be found [here](https://www.reddit.com/r/nextjs/comments/1dqslt6/nextjs_hangs_and_fails_on_linting_and_checking/)
Example of error occurring: [Link](https://vercel.com/coinbase-vercel/swc-web/44hsm4BiCqcRj7t4fvN9YvqcFLpj?filter=errors)
Documentation used for this change: [Link](https://nextjs.org/docs/app/api-reference/next-config-js/eslint)
---
There is a chance that we'll have to disable the type validation step as well. For so, we will use this documentation: [Link](https://nextjs.org/docs/app/api-reference/next-config-js/typescript)
> Adds `ignoreDuringbuilds` eslint config to `next.config.js`

- src/components/app/pageAdvocatesHeatmap/advocatesHeatmapTooltip.tsx
> add name of state to map hover tooltip

- src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts
Database has a limit of rows returned, this fixes this issue, making sure to always query addresses in batches the same size or smaller than the DB limit while also respecting the max addresses to backfill each day.
> FIX Append congressional district metadata to users address backfill function

- src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts
Making all queries in a single step was reaching vercel's serverless functions memory limit, so the query now returns only used data and each query is done a different step
> Fix: usCongressionalDistrict backfill inngest function memory limit reaching

- src/components/app/pageUserProfile/previousCampaignsList.tsx
closes #1072 
Filters the previous completed campaigns to prevent duplicated cards in profile page.
> Removes duplicated previous campaign cards

- .env.example
- src/utils/server/email/index.ts
- src/utils/server/email/sendMail.ts
- src/utils/server/email/utils/verifySignature.ts
fixes PROD-SWC-WEB-26X
This disables Sendgrid locally when the env variables are not set
> fix: conflict when using sendgrid prod on local env

- src/utils/shared/googleCivicInfo.ts
closes 
fixes 
We are getting a lot of errors on the Inngest function to backfill usCongressionalDistricts with reason `CIVIC_AP_DOWN`. This is being caused because Inngest doesn't make a request to our production static URL `https://standwithcrypto.org`, making instead to the URL created by Vercel on each deploy and the Civic API key on production only accepts requests from referrer `https://standwithcrypto.org`. This PR adds the correct URL to the referrer on production.
> fix: add correct referrer to google civic api requests

- src/app/[locale]/(homepageDialogDeeplink)/action/sign-up/page.tsx
closes #1129
Fixes an error when the user is already signed in, but navigates to `action/sign-up` causing a client render error
> Fix: `Rendered more hooks than during the previous render.` in `action/sign-up`

- package-lock.json
- package.json
- src/actions/actionCreateUserActionCallCongressperson/index.ts
- src/actions/actionCreateUserActionEmailCongressperson.ts
- src/actions/actionCreateUserActionLiveEvent.ts
- src/actions/actionCreateUserActionNFTMint.ts
- src/actions/actionCreateUserActionTweet.ts
- src/actions/actionCreateUserActionTweetAtPerson.ts
- src/actions/actionCreateUserActionVoterRegistration.ts
- src/actions/actionUpdateUserHasOptedInSMS.ts
- src/actions/actionUpdateUserHasOptedInToMembership.ts
- src/actions/actionUpdateUserInformationVisibility.ts
- src/actions/actionUpdateUserProfile.ts
- src/app/api/internal/commerce-webhook/route.ts
- src/utils/server/coinbaseCommerce/storePaymentRequest.ts
- src/utils/server/externalOptIn/handleExternalUserActionOptIn.ts
- src/utils/server/nft/mintPastActions.ts
- src/utils/server/sms/actions.ts
- src/utils/server/thirdweb/onLogin.ts
- src/utils/server/thirdweb/onLogout.ts
closes #841 
Refactor our server side analytics calls to take advantage of nextjs [waitUntil
](https://vercel.com/docs/functions/functions-api-reference#waituntil)
Every server action should now be 70-90ms faster, as they no longer wait for mixpanel responses
> Refactor serverside analytics calls to use waitUntil

- src/app/[locale]/(homepageDialogDeeplink)/action/sign-up/page.tsx
Removing GeoGate logic to try to fix this [error](https://stand-with-crypto.sentry.io/issues/5595992458/events/0f4c8352c0aa4136bff486bf1dbe07a4/?project=4506490717470720&referrer=issue_details.related_trace_issue)
> Removes GeoGate logic from Sign up deeplink

- src/utils/server/email/constants.ts
In a few sentry errors we identified that we're sending vercel deploy urls to transaction email links, this fixes it
> fix: change email base url

- src/hooks/useAuthUser.ts
Updated the `useThirdwebAuthUser` hook so that it doesn't return the user object if no user is found in the JWT.
> Fix bug where we were returning auth user when none existed

- src/components/app/authentication/loginDialogWrapper.tsx
- src/components/app/updateUserProfileForm/index.tsx
- src/hooks/useSections/index.tsx
- src/hooks/useSections/useSections.types.ts
closes #1142 
Fixes profile form displaying old data after submit and the profile visibility step is now only disabled on the onboarding flow
> Fix profile form showing stale data after submit

- src/app/api/verified-swc-partner/user-action-opt-in/route.ts
closes #1160 
Allows partners to signup users with invalid phone numbers and improve Sentry logs by appending the request body.
> Allow partner endpoint to accept invalid phone numbers

- src/components/app/userActionFormNFTMint/sections/checkout/index.tsx
closes #1163 
Users were not being redirected to the success screen after initiating a minting process. Consequently, the server action associated with the success screen was not being triggered.
We are not using the `onTransationConfirmed` callback because the transaction may take a while to be confirmed, so instead we redirect to the `TRANSACTION_WATCH` section as soon as the user triggers the transaction.
> NFT-Mint user action form to redirect on transaction sent

- prisma/schema.prisma
This PR fixes an issue related to rsvp user action table model
> Fix: rsvp event name in prisma schema

- src/app/[locale]/layout.tsx
- src/app/embedded/email/unsubscribe-success/layout.tsx
- src/app/embedded/map/layout.tsx
- src/app/global-error.tsx
- src/components/app/defaultLocaleLayout.tsx
closes #1188 
fixes  
Users that are using google translate are having an issue after logging in that causes the page to break and the user gets stuck on the global error page. This is being caused by google translate messing with react dom. This PR fixes this issue preventing google translate to translate swc-web pages.
> Fix: google translate breaking swc-web

- src/utils/shared/getUserActionsProgress.ts
closes #1196
This PR fixes the calc around completed user actions
7 is the expected number here
> Fix wrong completed action numbers in profile page

- cypress/e2e/12-action-join-stand-with-crypto.cy.ts
- cypress/support/commands.ts
This PR reactivates the join e2e test to test login and update profile flow.
As we are mocking the login by generating a random wallet each time cypress clicks on the test login button, the old flow of login -> update profile -> logout -> don't ask for profile update again won't work because each login click now generates a new user.
> Reactivates Join E2E test

- src/components/app/userActionFormVoterAttestation/index.tsx
fixes PROD-SWC-WEB-4G5
This is adding a validation for error and success treatments to the races requests on the pledge flow when the request is not active
> fix: add validation for active request in voter pledge races

- src/utils/server/email/templates/ui/heading.tsx
- src/utils/server/email/templates/ui/keepUpTheFightSection.tsx
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1215
fixes 
added more padding around action images 
before:
after:
> style: adjust actions email template

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
- src/inngest/functions/sms/utils/communicationJourney.ts
- src/inngest/functions/sms/utils/enqueueMessages.ts
We intend to test a new variation of bulk messages by sending the legal disclaimer along with the actual bulk text, so to do this we need to remove the default welcome message that's being sent in the bulk sms
> fix: remove default bulk welcome

- src/components/app/userActionFormVoterRegistration/constants.ts
- src/components/app/userActionFormVoterRegistration/index.tsx
- src/components/app/userActionFormVoterRegistration/sections/survey.tsx
- src/components/app/userActionFormVoterRegistration/sections/voterRegistrationForm.tsx
This PR adds a new confirm registration step for  users who have registered to vote because it's important for these folks to check their registration because they might have had an issue come up, their address might be out of date, etc
> Creates new confirm registration form

- src/inngest/functions/sms/utils/communicationJourney.ts
- src/inngest/functions/sms/utils/enqueueMessages.test.ts
- src/inngest/functions/sms/utils/enqueueMessages.ts
closes #1223 
fixes PROD-SWC-WEB-4KD
Previously, `enqueueMessages` was invoking `createCommunicationJourneys` and `createCommunication` for each message, leading to a **pool connection limit exceeded** error. The new approach with `bulkCreateCommunicationJourney` reduces database interactions by consolidating them into a single call per `journeyType`.
Users are divided into 2 chunks of **500**.
- For each chunk of 500 users and 2 message types (BULK + WELCOME):
- (500 messages * 3 findMany calls) * 2 message types = 3000 * 2 chunks = 6000 findMany calls
- (500 messages * 2 createMany calls) * 2 message types = 2000 * 2 chunks = 4000 createMany calls
- For each chunk of 500 users and 2 message types (BULK + WELCOME):
- 3 findMany calls * 2 message types = 6 * 2 chunks = 12 findMany calls
- …
> fix: pool connection limit exceeded

- src/components/app/navbar/index.tsx
closes #1180 
This PR changes the navbar breakpoints because after adding the new events link, the navbar is not collapsing early enough causing UI shifts.
**P.S.: I decided to use this custom value because no other one tailwind default one would work and I also decided to not customize the Tailwind theme to add this new custom breakpoint because it only makes sense for the navbar context and is out of the normal breakpoint recomendations.**
> Changes navbar breakpoints

- src/components/app/pageEvents/components/eventsMap.tsx
- src/components/app/pageEvents/components/eventsNearYou.tsx
- src/components/app/pageEvents/components/stateEventsDialogContent.tsx
- src/components/app/pageEvents/components/upcomingEvents.tsx
- src/components/app/pageEvents/eventsPageDialogDeeplinkLayout.tsx
- src/components/app/pageEvents/index.tsx
closes #1280
This PR fixes the state events dialog problem of showing past events. You can check the current error here: https://standwithcrypto.org/events/ga
> Fix: State events dialog showing past events

- src/components/app/navbar/navbarLoggedInButton/index.tsx
closes #1170
fixes 
Signup with wallet/phone number and not finishing the profile:
After finishing the profile:
Signup with email, without providing a name:
> Show 'Profile' instead of wallet hash for users without info

- src/components/app/cookieConsent/cookieConsent.tsx
- src/components/app/cookieConsent/useCookieConsent.ts
- src/utils/shared/executionEnvironment.ts
- src/utils/web/clientAnalytics.ts
closes  https://github.com/Stand-With-Crypto/swc-internal/issues/167
fixes 
Global privacy control on new browsers and if the user enables it, we must not track or show cookies consent banners whatsoever
https://globalprivacycontrol.org/
https://global-privacy-control.glitch.me/
> feat: add global privacy control awareness

- src/components/app/pageUserProfile/index.tsx
- src/components/app/userActionFormSuccessScreen/index.tsx
closes #1279
This PR fixes the issue where the list of completed actions is not updated upon action complete on profile page
> feat: updates user actions on profile page after the user completes an action

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
- src/utils/server/sms/messagingClient.ts
- src/utils/server/sms/sendSMS.ts
closes 
fixes [PROD-SWC-WEB-4ET](https://stand-with-crypto.sentry.io/issues/5691014147/events/84a3cb3472c14dcc85faa7845b045314/)
Right now, we're queuing all messages in a single Inngest step, but this is causing timeout errors on Vercel because the step takes too long. This PR changes that by sending a batch of 750 messages per step.
> fix: bulk sms timeout

- src/utils/server/formatENSAvatar.ts
- src/utils/shared/parseENSImageUrl/index.ts
- src/utils/shared/parseENSImageUrl/parseENSAvatarUrl.test.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1264
fixes  https://stand-with-crypto.sentry.io/issues/5003561526/?referrer=github_integration
allow for data uri avatar images such as below:
> refactor: add ens extra avatar format parsing

- src/app/[locale]/races/page.tsx
- src/app/[locale]/races/state/[stateCode]/district/[district]/page.tsx
- src/app/[locale]/races/state/[stateCode]/page.tsx
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1342
fixes
> refactor: adjust dynamicParams to false when dynamic = 'error'

- src/actions/actionCreateUserActionVotingInformationResearched.tsx
- src/components/app/userActionFormVotingInformationResearched/dialog.tsx
- src/components/app/userActionFormVotingInformationResearched/formConfig.ts
- src/components/app/userActionFormVotingInformationResearched/index.tsx
- src/components/ui/googlePlacesSelect/index.tsx
[GH-176](https://github.com/Stand-With-Crypto/swc-internal/issues/176)
Adds the `userActionFormVotingInformationResearched` form & dialog to be used in the Voter Guide page
Added `initOnMount: false` to the `usePlacesAutocomplete` hook to fix the undefined maps error. We are manually initializing the hook once the `GoogleMapScript`  status is `ready`.
> User action form for voting_information_researched action

- src/actions/actionCreateUserActionViewKeyRaces.ts
- src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts
- src/utils/server/externalOptIn/handleExternalUserActionViewKeyRaces.ts
- src/utils/shared/getCongressionalDistrictFromAddress.ts
- src/utils/shared/googleCivicInfo.ts
closes #1234 
This PR saves the district number as 'NOT_FOUND' to prevent addresses that are broken from being processed everyday in the backfill cron job.
> Prevents broken address from being processed on backfill repeatedly

- src/inngest/functions/sms/utils/enqueueMessages.test.ts
- src/inngest/functions/sms/utils/enqueueMessages.ts
- src/utils/server/sms/utils/getUserByPhoneNumber.ts
closes [#191](https://github.com/Stand-With-Crypto/swc-internal/issues/191)
Adds support for variables in the sms body so that we can send custom messages for each user
> feat: support sms message variables

- src/inngest/functions/sms/utils/enqueueMessages.test.ts
- src/inngest/functions/sms/utils/enqueueMessages.ts
- src/utils/server/sms/utils/getUserByPhoneNumber.ts
This reverts commit e0dcccf8b78818f50746e300b7a7a4b5ea7a5fd0.
closes 
fixes
> Revert "feat: support sms message variables (#1352)"

- src/components/app/userActionFormEmailDebate/skeleton.tsx
Fixing a weird behavior on the email debate dialog skeleton title.
> Fix skeleton title on mobile

- src/hooks/useGoogleMapsScript.ts
- src/hooks/usePlacesAutocompleteAddress.ts
- src/hooks/useScript.ts
closes #1349 
fixes 
Added `initOnMount: false` to ensure that the `usePlacesAutocomplete` hook only initializes after the google maps script is loaded.
Also added `&loading=async` to fix this warning
> Fix google places script error

- src/inngest/functions/sms/utils/enqueueMessages.test.ts
- src/inngest/functions/sms/utils/enqueueMessages.ts
- src/utils/server/sms/utils/getUserByPhoneNumber.ts
closes 
fixes 
The lodash `template` function was causing timeouts on Vercel, preventing messages from being sent, so I switched to a simpler approach using regex.
> fix: remove lodash template from addVariablesToMessage

- cypress/e2e/04-action-email-your-congressperson.cy.ts
- cypress/e2e/06-donation-card-redirect.cy.ts
- cypress/e2e/08-action-call-your-congressperson.cy.ts
- cypress/e2e/13-user-action-unavailable.cy.ts
- src/components/app/pageUserProfile/disabledUserActionCampaigns.ts
- src/utils/shared/getUserActionsProgress.ts
- src/utils/web/userActionUtils.ts
closes #1354 
This PR temporarily disables Call, Email and Donate actions to only show the actions that are directly related to the 2024 election. It also updates how we calculate completed actions in profile page to fix a bug that was calculating actions that are not in the CTA list.
> Disables user actions not directly related to the election

- src/components/app/recentActivityRow/variantRecentActivityRow.tsx
This PR fixes the issue of not showing DC events on the activity feed because we were using a const that doesn't have the US territories, only main states.
> Activity feed not showing dc events

- src/inngest/functions/eventNotification/logic.ts
- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
closes 
fixes [PROD-SWC-WEB-4SY](https://stand-with-crypto.sentry.io/issues/5820938436/events/88c1107c11254961a1073adb346299b4/)
> fix: event reminder sending wrong payload to bulk-sms

- src/inngest/functions/sms/utils/enqueueMessages.ts
- src/utils/shared/logger.ts
closes 
fixes 
Adding more logs to `enqueuMessage` to debug a timeout issue with bulk-sms
> fix: add more logs to enqueueMessages

- src/inngest/functions/airdropNFT/airdropNFT.tsx
- src/utils/server/serverAnalytics/serverAnalytics.ts
This adds better logging and register the exception from `resolveWithTimeout` from server analytics flush, this should add more context to #1151
> fix: analytics flush hanging up

- package-lock.json
- package.json
- src/components/app/pageDonate/donateButton.tsx
- src/utils/server/thirdweb/onLogin.ts
- src/utils/web/formUtils.ts
closes #1353 
We had incidents in the past where the Sentry logs were mixed with less relevant errors and that made harder to identify we had a critical problem happening. To address that we're increasing the criticality of exceptions captured in critical flows of the app.
In order to not flood the `fatal` level, to start we're only considering errors occurring on the login and donate flows as fatal errors.
> feat: increase criticity of errors on critical flows

- src/app/[locale]/topLevelClientLogic.tsx
- src/middleware.ts
- src/utils/shared/userId.ts
Remove `sessionId` & `userId`  params from url. This will not have an impact on client analytics or logout the user.
> Erase sessionId param from url

- src/app/api/public/sendgrid/events/route.ts
- src/inngest/functions/airdropNFT/airdropNFT.tsx
- src/inngest/functions/backfillReactivation/index.tsx
- src/inngest/functions/initialSignupUserCommunicationJourney/initialSignupUserCommunicationJourney.tsx
- src/utils/server/email/sendMail.ts
- src/utils/server/email/templates/becomeMemberReminder.tsx
- src/utils/server/email/templates/contactYourRepresentativeReminder.tsx
- src/utils/server/email/templates/finishSettingUpProfileReminder.tsx
- src/utils/server/email/templates/followOnXReminder.tsx
- src/utils/server/email/templates/initialSignUp.tsx
- src/utils/server/email/templates/nftArrived.tsx
- src/utils/server/email/templates/nftOnTheWay.tsx
- src/utils/server/email/templates/phoneNumberReminder.tsx
- src/utils/server/email/templates/reactivationReminder.tsx
- src/utils/server/email/templates/registerToVoteReminder.tsx
- src/utils/server/nft/claimNFT.tsx
While building mixpanel dashboards we noticed we didn't have a way to group url by origin, that caused a lot of versions of the same url to be visible, this fixes it and adds a new field to help identify which campaign that click is coming from (redundant field in some cases, but useful in others)
> feat: add more info to email events

- src/app/api/public/sendgrid/events/route.ts
On a recent change we added a parse to the url before registering an email event, this removed the pathname information from it. This solves it
> fix: change how we parse the url before registering the mixpanel event

- next.config.js
Vanity URL for https://docs.google.com/document/d/10rbmu692hXuYezVsGgR9lL21TtoWO6d3f872Rb823t8/edit#heading=h.7wlfos2ex7fp
> feat: add voter guide p2p sms vanity url

- src/app/api/public/sms/events/status/route.ts
fixes [PROD-SWC-WEB-4PP](https://stand-with-crypto.sentry.io/issues/5759605772/events/ed4f22dd54aa4dc78da63744299f93b2/), [PROD-SWC-WEB-4CR](https://stand-with-crypto.sentry.io/issues/5669084486/events/d8e5af6ce225454493acd7a2ad441fc2/)
This PR increases the timeout between retries for getting user communication
> fix: increase retry timeout time on sms status webhook

- next.config.js
Change the voter guide vanity url because we'll be sending this communication via Twilio and not P2P anymore
> fix: remove p2p from voter guide sms utm_medium

- src/inngest/functions/sms/enqueueMessages.ts
closes 
fixes 
We were returning the result of a .push call instead of the actual array with new elements to the failedPhoneNumbers hash map
> fix: use spread to return the correct failedPhoneNumbers payload

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
Sometimes bulk SMS fails due to Inngest errors, so by increasing the retry count, we make it more resilient to these issues. We also don’t need to worry about sending duplicate messages because, during the next retry, we filter out phone numbers that have already received that communication under the same campaign name
> fix: set max-retry-count to 1 in bulk-sms

- src/app/api/public/sms/events/fails/route.ts
- src/app/api/public/sms/events/status/route.ts
closes 
fixes [PROD-SWC-WEB-4CR](https://stand-with-crypto.sentry.io/issues/5669084486/events/3fe546327ca94d2e95c62e1a7419e459/)
Some Twilio errors are flooding Sentry, so this PR is:
- Filtering errors related to the mobile carrier when sending SMS errors to Sentry
- Returning 200 even when we couldn't find the userCommunication on the status webhook
- Commenting the error related to not finding the userCommunication, because we'll fix it in [#260](https://github.com/Stand-With-Crypto/swc-internal/issues/260)
> fix: twilio errors flooding sentry

- docs/Add a new user action.md
- docs/Working with two or more campaigns active.md
closes #1470 
This PR updates the documentation for `Create New Action` and `Working with Multiple Campaigns` to reflect the recent changes introduced by the new grid action CTAs that we implemented in the past few weeks.
> Docs: Updates create action and multiple campaigns doc

- src/utils/server/thirdweb/onLogin.ts
closes #1507 
fixes 
`existingUsers` query takes too long to complete. We tried to index every field and that did not solve the issue, so our best bet is that the OR operator makes it hard for prisma to optimize the query properly. To solve this, we are dividing this query into multiple queries done in parallel so we have smaller and optimized queries instead of a big complex query.
To test it out we made this query on production database, that took more than 3s to complete:
```sql
SELECT user.id, user.datetime_updated,
user.datetime_created, user.first_name, user.last_name,
user.phone_number, user.address_id,
user.information_visiblity, user.primary_user_email_address_id,
user.primary_user_crypto_address_id, user.has_opted_in_to_emails,
user.has_opted_in_to_membership, …
```
> feat: divide complex login query with OR operator for multiple smaller queries done in paralellel

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
Now that we're using a short-code we don't need all this logic related to time to empty queue and segmentes count
> fix: remove unnecessary bulk-SMS logic

- prisma/schema.prisma
- src/components/app/homepageDialogDeeplinkLayout.tsx
- src/components/app/pageHome/index.tsx
- src/components/app/pageHome/topLevelMetrics.tsx
- src/data/aggregations/getCountVoterActions.ts
- src/data/pageSpecific/getHomepageData.ts
closes #272 
This is replacing the Policymaker box on the `TopLevelMetrics` cart to a new metric that counts voter actions we have, top level metrics are any of the following:
- VOTER_REGISTRATION
- VOTER_ATTESTATION
- VOTING_INFORMATION_RESEARCHED
-  VIEW_KEY_RACES
https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/73
> feat: change policymaker contacts to voter actions count

- src/components/app/pageHome/topLevelMetrics.tsx
> fix: revert order on top level metrics

- src/inngest/functions/sms/tests/enqueueMessages.test.ts
- src/inngest/functions/sms/utils/getSMSVariablesByPhoneNumbers.ts
- src/utils/server/sms/utils/variables.test.ts
- src/utils/server/sms/utils/variables.ts
This PR changes how we apply variables to the sms body by using Lodash's [template](https://lodash.com/docs/4.17.15#template) function. This function allows us to use ternary expressions, enabling us to handle cases when variables have no value.
> feat: support ternary expressions on sms body

- src/components/app/cookieConsent/useCookieConsent.ts
closes #1541 
fixes [PROD-SWC-WEB-4ZM](https://stand-with-crypto.sentry.io/issues/5963833040/events/b94d04c50a0c4112a3f757750e2d9d80/)
Sometimes Mixpanel isn't loaded when the user accepts or rejects our cookies, so we need to attempt to initialize the analytics client each time the user interacts with cookies.
> fix: init mixpanel on cookie consent

- prisma/extensions/logQuery.ts
- src/utils/server/prismaClient.ts
This PR adds a new database logging extension to help get query execution time metric.
> feat: adds new logging prisma extension

- prisma/extensions/logQuery.ts
- src/utils/server/prismaClient.ts
This PR changes prisma log to use JSON.stringify to help improve all arguments visibility
> Changes prisma logging args to improve visibility

- src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
Updated to use event name for local environment instead of cron job schedule. This ensures we're not running a cron job during local development.
> fix: update inngest config to use event name on local environment

- cypress/e2e/06-donation-card-redirect.cy.ts
- cypress/e2e/12-action-join-stand-with-crypto.cy.ts
- cypress/support/commands.ts
closes #1598 
This PR restores some E2E tests for actions that were restored after the election
> chore: restores e2e tests after election

- docs/Contributing.md
closes #1597 
This PR updates the `Contributing` documentation by adding a new tip related to database query logging.
> docs: updates `Contributing` doc with database tip

- src/app/api/public/sms/events/status/route.ts
- src/inngest/functions/backfillUserCommunicationMessageStatus/index.ts
fixes PROD-SWC-WEB-4CR
We're currently receiving requests without query parameters. In these cases, we should attempt to find the user_communication. Only if it isn't found should we throw an error.
> fix: parse requests without search params

- src/utils/shared/locationSpecificPages.ts
closes #1595 
This PR removes all candidates who lost the 2024 election from the endorsed candidates page
> chore: removes endorsed candidates who lost the election

- prisma/schema.prisma
- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
Bulk sms query with new status index
Bulk sms query without the status index
[#77](https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/77)
> fix: indexing message status

- src/app/api/public/sms/events/messages/route.ts
- src/utils/server/sms/identifyIncomingKeyword.test.ts
- src/utils/server/sms/identifyIncomingKeyword.ts
closes [#1613](https://github.com/Stand-With-Crypto/swc-web/issues/1613)
This pull request introduces a new function to identify incoming SMS keywords and refactors the existing keyword identification logic to improve readability and maintainability. It also includes corresponding unit tests for the new function.
> feat: implement keyword identification for SMS responses and add tests

- src/app/api/inngest/route.ts
- src/inngest/functions/sms/backfillOptedOutUsers.ts
- src/inngest/functions/sms/index.ts
- src/inngest/types.ts
- src/utils/server/sms/identifyIncomingKeyword.test.ts
- src/utils/server/sms/identifyIncomingKeyword.ts
- src/utils/server/sms/index.ts
- src/utils/server/sms/messagingClient.ts
closes [#1618](https://github.com/Stand-With-Crypto/swc-web/issues/1618)
This PR adds a backfill script to opt out users who tried to opt out with a break line or empty space after the STOP keyword
> feat: add backfill script to opt out users who weren't opted out correctly

- cypress/e2e/09-page-politician-details.cy.ts
- src/components/app/pagePoliticianDetails/index.tsx
- src/components/app/pagePoliticianDetails/questionnaireAccordion.tsx
- src/components/app/scrollToTopOnRender.tsx
closes #814 
This PR addresses a long-standing issue where, on mobile devices in production, if you visit a politician's page, scroll down, then navigate back and to a different politician's page, the scroll position from the previous page is unexpectedly carried over to the new page. This requires the user to manually scroll back to the top.
I've tested various approaches to fix this, including [enabling and disabling scroll behavior on router.push](https://nextjs.org/docs/app/api-reference/functions/use-router#disabling-scroll-to-top), but this didn’t resolve the issue. I also tried adding an ID to the politician photo section and appending it to the router's pathname, but that approach didn't work either. Given that all politician page components are server-side rendered and useEffect …
> fix: politician page scroll

- src/data/recentActivity/getPublicRecentActivity.ts
closes [#309](https://github.com/Stand-With-Crypto/swc-internal/issues/309)
We noticed that this query was not using the correct index, and to fix it we need to remove `internalStatus` from `where`.
Query with `where`:
Query without `where`:
> fix: remove where from recent activities query so that it uses the correct index

- src/app/api/inngest/route.ts
- src/inngest/functions/datadog/cleanup/index.ts
To ensure we don't store unnecessary data, it's important to clean up any information generated by synthetic tests in the production environment, especially since we need to go through login and complete user actions during testing.
This PR deletes all user actions and email addresses related to synthetic test users.
> feat: creates synthetic tests clean up cron job

- src/inngest/functions/datadog/cleanup/index.ts
This PR updates the condition for deleting emails. Previously, it only deleted emails created within the last hour. The new version will delete all emails created more than one hour prior to the execution of the Inngest function.
> fix: datadog synthetic tests emails not being deleted

- src/components/app/userActionFormSuccessScreen/constants.ts
- src/components/app/userActionFormSuccessScreen/smsOptIn.tsx
closes #1362 
This PR updates the success screen description based on the authentication state, ensuring we do not state that the user will receive the NFT if they are not logged in with Thirdweb.
- x] Locally
> Changes action success screen message

- src/components/app/pageUserProfile/index.tsx
closes #1665 
fixes 
The UpateProfileForm shows twice due to two instances being mounted on the page (1 mobile & 1 desktop). The solution is to use javascript to conditionally mount the components.
> Fix double profile modal

- sentry.client.config.ts
This PR adds new common error messages from frequent Sentry error logs that do not have a clear indicator of the problem or reason.
> feat: updates `COMMON_ERROR_MESSAGES_TO_GROUP` errors

- next.config.ts
Vanity URL for the victory lap [SMS](https://docs.google.com/document/d/1CLY7WZswo9lsHhNFR_LnJ33s9GjhuqBs8D9WCEgUKds/edit?tab=t.0#heading=h.k1imdll89s23)
> fix: add redirect for The Block News URL

- src/app/[locale]/(homepageDialogDeeplink)/action/call/page.tsx
- src/app/[locale]/(homepageDialogDeeplink)/action/email-debate/page.tsx
- src/app/[locale]/(homepageDialogDeeplink)/action/email/page.tsx
- src/app/[locale]/(homepageDialogDeeplink)/action/live-event/[slug]/page.tsx
- src/app/[locale]/(homepageDialogDeeplink)/action/nft-mint/page.tsx
- src/app/[locale]/(homepageDialogDeeplink)/action/share/page.tsx
- src/app/[locale]/(homepageDialogDeeplink)/action/tweet-at-person/[slug]/page.tsx
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1694
fixes 
- Moved ErrorBoundary component to wrap the content inside HomepageDialogDeeplinkLayout for better error handling.
- Updated all relevant action pages: call, email, email-debate, live-event, nft-mint, share, and tweet-at-person.
- Ensured consistent structure across all deeplink actions to improve maintainability and readability.
> refactor: restructure ErrorBoundary usage in homepage dialog deeplinks

- src/mocks/dtsi/mockResolvers/dtsiQueryResolver.ts
- src/utils/dtsi/dtsiPersonRoleUtils.tsx
Now that the new congress is in office and DTSI is updated, we need to update what we assume is the current session of congress on the frontend
> update APIs to point to new congress

- next.config.ts
Adds vanity URL for [this](https://docs.google.com/document/d/1CLY7WZswo9lsHhNFR_LnJ33s9GjhuqBs8D9WCEgUKds/edit?pli=1&tab=t.0#heading=h.gvqve1o4rr73) SMS communication
> feat: add SMS shortlink for new member activation

- src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
Updates the message delivery status validation when fetching the bulk SMS phone number list to exclude 'PROCESSING' messages, preventing duplicate message sends.
> fix: update getPhoneNumberList validation to not include PROCESSING messages

- src/app/api/public/sms/events/status/route.ts
- src/utils/server/serverAnalytics/shared.ts
fixes [PROD-SWC-WEB-4WW](https://stand-with-crypto.sentry.io/issues/5895385971/)
Increase SMS status webhook duration to fix timeout
> fix: increase ANALYTICS_FLUSH_TIMEOUT_MS to 10000

- src/validation/fields/zodDTSISlug.ts
Turns out it's possible that dtsi slugs only have two dashes, I'm removing the 3 dashes validation for that reason
closes 
fixes
> fix: remove 3 dashes validation from dtsi slug

- src/actions/actionCreateUserActionEmailCongressperson.ts
- src/components/app/userActionFormEmailCongressperson/index.tsx
- src/components/app/userActionFormEmailCongressperson/skeleton.tsx
- src/validation/forms/zodUserActionFormEmailCongressperson.ts
closes  https://github.com/Stand-With-Crypto/swc-web/issues/1740
fixes
> feat: add autoComplete off attribute to message textarea component

- next.config.ts
Vanity URL for [this](https://docs.google.com/document/d/1CLY7WZswo9lsHhNFR_LnJ33s9GjhuqBs8D9WCEgUKds/edit?tab=t.0#heading=h.ab4kcs4gvyg0) SMS
> feat: add new SMS shortlink redirect for new congress activation

- src/utils/shared/phoneNumber.ts
closes #1762 
fixes [PROD-SWC-WEB-5K0](https://stand-with-crypto.sentry.io/issues/6200525119/)
Before the change, a `TOO_SHORT` parse error will break the form:
https://github.com/user-attachments/assets/69b1571d-140f-4abb-be0f-4bbbe39d7ee2
After the change we display proper user feedback and correct analytics info:
https://github.com/user-attachments/assets/6fce7f27-b17e-4cc0-8486-3efd77024d0d
> Display invalid phone number instead of throwing

- src/utils/server/localeRouter/index.ts
- src/utils/shared/supportedLocales.ts
closes #1781 
This PR adds new logic to save the locale information on our middleware to be used in actions, Mixpanel and Sentry
> feat: save locale information on middleware

- src/app/api/public/sms/events/fails/route.ts
- src/app/api/public/sms/events/status/route.ts
- src/inngest/functions/sms/tests/enqueueMessages.test.ts
- src/utils/server/sms/SendSMSError.ts
- src/utils/server/sms/errorCodes.ts
closes [#312](https://github.com/Stand-With-Crypto/swc-internal/issues/312)
- Added more errors to be filtered from Sentry in the SMS fails webhook
- Added a log to Sentry when the SMS status webhook cannot find the user
> fix: improve SMS webhook Sentry logging

- src/components/app/geoGate.tsx
- src/components/app/pageDonate/heading.tsx
- src/components/app/pageEvents/index.tsx
fixes [PROD-SWC-WEB-5Q5](https://stand-with-crypto.sentry.io/issues/6256951763/events/716c384999894130b2cc6cc6f4931e4c/)
Make unavailableContent optional as React.cloneElement is complaining about it being null
> fix: make unavailableContent optional in GeoGate component

- prisma/schema.prisma
- src/components/app/navbarGlobalBanner/index.tsx
- src/mocks/models/mockAddress.ts
- src/mocks/models/mockNFTMint.ts
- src/mocks/models/mockUser.ts
- src/mocks/models/mockUserAction.ts
- src/mocks/models/mockUserActionCall.ts
- src/mocks/models/mockUserActionDonation.ts
- src/mocks/models/mockUserActionEmail.ts
- src/mocks/models/mockUserActionOptIn.ts
- src/mocks/models/mockUserActionRsvpEvent.ts
- src/mocks/models/mockUserActionTweetAtPerson.ts
- src/mocks/models/mockUserActionViewKeyRaces.ts
- src/mocks/models/mockUserActionVoterAttestation.ts
- src/mocks/models/mockUserActionVoterRegistration.ts
- src/mocks/models/mockUserActionVotingDay.ts
- src/mocks/models/mockUserActionVotingInformationResearched.ts
- src/mocks/models/mockUserEmailAddress.ts
- src/utils/shared/isValidCountryCode.ts
- src/utils/shared/supportedCountries.ts
closes #1778 
This PR updates the Prisma schema by adding a new `tenantId` column to all models required for our internationalization process.
PlanetScale limits deploy requests to a maximum of 10 tables being updated. Because of this, I'll merge the first 10 tables and then create a second deploy request with the rest to complete the migration.
First deploy request: https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/79
Second deploy request:
P.S.: We are temporarily setting the default value to "US" just for the migration. Afterwards, I'll create another deploy request to remove the default value.
> feat: add tenantId to models for multi-country support

- next.config.ts
- sentry.client.config.ts
fixes [PROD-SWC-WEB-5PZ](https://stand-with-crypto.sentry.io/issues/6243931808/events/51af5add355f4e1588f708d42c0c8478/)
Implemented a check to determine if the current window is within an iframe and discard errors if the parent URL matches any in the `IGNORED_IFRAME_PARENT_URLS` list.
> chore: add builder.io to Sentry ignore patterns

- src/app/[countryCode]/events/[state]/[eventSlug]/page.tsx
- src/app/[countryCode]/events/[state]/page.tsx
- src/app/[countryCode]/events/page.tsx
- src/app/api/public/builder/events/data/route.ts
closes #1809 
This PR removes time-based revalidation on events page.
> chore: remove revalidate and update events route revalidation paths

- src/app/[countryCode]/internal/user-settings/userConfig.tsx
- src/components/app/navbarGlobalBanner/index.tsx
This PR fixes CA and UK global navbar banner not showing because our banner logic is comparing UK with uk and CA with ca, causing a mismatch and the corresponding banner not showing
> fix: CA and UK banners not showing with custom cookie

- cypress/e2e/14-navbar-global-banner.cy.ts
This PR decreases repeated code by creating a function to get the specific countryCode cookie value for each test case.
> refactor: improve country code E2E test

- src/bin/reports/usersGroupedByCompletedActionsNumber.ts
closes #1824 
This PR creates a new bin script to generate metrics of user quantities grouped by the number of completed actions, excluding the OPT_IN action.
> feat: add report generation for users grouped by completed actions

- src/components/app/navbar/index.tsx
closes #1844 
Currently, we have two components, LoginButton and DonateButton, that are created inside the NavBar component without memoization. The problem here is that whenever any cookies change or any other topClientLogic hook re-renders, these two components are recreated and mounted again, causing the login dialog to close, for example.
This PR fixes this issue by moving these components out of the NavBar component function to prevent them from being recreated at every render.
> fix: Navbar button components re-render

- src/app/[countryCode]/page.tsx
We noticed we were rebuilding the home page when a path with a `.` character was received, this was caused because having a dot makes the request skip the `middleware.ts` (see the image below) that transforms a `/foo` request into `/en/foo`, that made so the `/[countryCode]/page.tsx` was being called with an unexpected `countryCode`. Since all countryCodes should be explicitly defined we should be using `export const dynamicParams = false` in the page, this adds that configuration.
> fix: stops home from revalidating when receiving an unexpected countryCode

- src/actions/actionCreateCoinbaseCommerceCharge.ts
- src/components/app/pageDonate/donateButton.tsx
closes #1869
fixes 
Safari blocks `window.open()` calls made without user interaction or in async functions. This PR fixes the problem by calling window.open synchronously on user click and then changes the url of that window.
[Same solution used for the Turbovote fix](https://github.com/Stand-With-Crypto/swc-web/pull/1396)
> Fix async window open

- src/app/api/inngest/route.ts
- src/inngest/functions/backfillUserActionRefer/index.ts
- src/inngest/types.ts
closes #1836 
fixes 
Creates an Inngest function to backfill the `UserActionRefer` records based on user acquisition data. The script:
- Dry run mode for validation before persisting changes
- Identifies users who were referred through referral links (utm_source=swc, utm_medium=referral)
- Groups referred users by their referrer's ID
- Creates or updates REFER actions for referrers with accurate referral counts
> Backfill script for user action REFER

- src/inngest/functions/backfillNFTCronJob/index.ts
- src/utils/server/nft/claimNFT.tsx
This PR fixes the NFT backfill inngest function calling a server function that requests cookies to get the tenantId.
> fix: pass tenantId to claimNFT function for improved context handling

- prisma/schema.prisma
closes #1884 
This PR removes the default tenantId value on multiple models in the DB schema.
Deploy request: https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/102
As we can't update more than 10 models at the same time in PlanetScale and to prevent production bugs, we will need to merge this PR first and deploy it to prod. After the PR is merged, I'll execute the database migration steps.
> fix: remove default value for tenantId in multiple models

- src/components/app/pagePress/NewsList.tsx
- src/utils/server/builder/builderSDKClient.ts
- src/utils/server/builder/models/data/news/index.ts
fixes [PROD-SWC-WEB-5V4](https://stand-with-crypto.sentry.io/issues/6327979949/events/c92c5f0fa0c54588a8fca5c5fdb140d7/)
* refactor `getNewsList` into a server action to correctly fetch news in the client
* Mark builderSDKClient as `server-only`
> fix: news fetching using builder.io private key on client

- prisma/schema.prisma
- src/app/api/inngest/route.ts
- src/inngest/functions/districtsRankings/updateRankings.ts
- src/inngest/types.ts
- src/mocks/models/mockAddress.ts
- src/mocks/models/mockUserActionRefer.ts
- src/utils/server/districtRankings/constants.ts
- src/utils/server/districtRankings/getRankingData.ts
- src/utils/server/districtRankings/upsertRankings.ts
- src/utils/shared/urls/index.ts
- src/validation/fields/zodAddress.ts
closes #1837 
- Added Inngest cron job to query the district data and upsert it in Redis;
- Compression is not needed, as the final size is about 45KB; 
- Added an index for address queries;
https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/98
🗒️ Referrals count looks way higher in testing due to the mocking script generating a lot more REFER actions than users;
- Added DC state to our mock data with a probability of 5%, this is because faker does not consider DC as an State 😞
> Referrals ranking cron job

- src/app/[countryCode]/topLevelClientLogic.tsx
- src/bin/smokeTests/onNewLogin/9testCaseWithLongAcquisitionReferrer.ts
- src/utils/server/serverAnalytics/serverAnalytics.ts
- src/utils/server/serverLocalUser.ts
- src/utils/server/thirdweb/onLogin.ts
- src/utils/shared/localUser.ts
- src/utils/web/clientAnalytics.ts
- src/utils/web/clientLocalUser.ts
- src/utils/web/getCountryCodeOnClient.ts
closes #1784 
This PR saves the country code cookie on Mixpanel events and sentry to help track and filter events and errors by country code. 
Note that I'm already using countryCode naming instead of tenantId because we've decided to pivot from the multi-tenant architecture. All other necessary changes to rename tenantId to countryCode will be done afterwards.
> feat: save country code information in mixpanel and sentry

- src/utils/server/serverAnalytics/serverAnalytics.ts
This PR fixes some issues related to trying to load cookies when it is not available.
> fix: remove country code tracking from server analytics

- src/validation/fields/zodSupportedCountryCode.ts
closes #1911 
This PR creates some logic to support cases where the country code for the United Kingdom to be GB instead of UK
Check the last case in this [issue](https://github.com/Stand-With-Crypto/swc-web/issues/1898) for proof of working
> feat: transform country code to support UK as 'gb' in validation

- sentry.client.config.ts
This PR groups error messages created on edge environment.
> feat: add error message for 500 response from recent activity API

- sentry.client.config.ts
This PR groups errors caused by the datadog synthetic tests recorder not allowing cookies to be created.
> fix: edge functions flooding sentry

- src/data/dtsi/queries/queryDTSIBillDetails/index.ts
fixes [PROD-SWC-WEB-5TD](https://stand-with-crypto.sentry.io/issues/6302930936/events/527f367097264a86a95f3c627f6abab4/)
Added a catch to queryDTSIBillDetails so the page redirects to 404 instead of crashing when accessing a invalid bill
> fix: add error handling to queryDTSIBillDetails

- src/app/(builder)/[countryCode]/about/page.tsx
- src/app/(builder)/[countryCode]/advocacy-toolkit/page.tsx
- src/app/(builder)/[countryCode]/content/[[...page]]/page.tsx
- src/app/(builder)/[countryCode]/partners/page.tsx
- src/app/(builder)/[countryCode]/press/[...page]/page.tsx
- src/app/(builder)/[countryCode]/press/page.tsx
- src/app/(builder)/[countryCode]/privacy/page.tsx
- src/app/(builder)/[countryCode]/terms-of-service/page.tsx
- src/components/app/builder/builderComponent.tsx
- src/components/app/builder/builderPageLayout.tsx
- src/utils/server/builder/models/page/constants.ts
- src/utils/server/builder/models/page/utils/getPageContent.ts
- src/utils/server/builder/models/page/utils/getPageDetails.ts
closes [#1887](https://github.com/Stand-With-Crypto/swc-web/issues/1887)
Adds support for country specific page models
> feat: add countryCode parameter to page content

- src/utils/server/externalOptIn/handleExternalUserActionOptIn.ts
- src/utils/server/serverAnalytics/serverAnalytics.ts
This PR re-adds the logic to track the country code in server analytics.
> feat: add country code tracking to server analytics

- src/components/ui/popover.tsx
Removes a11yTitle from prop spreading in the Popover element to fix the following error
> feat: add accessibility title to PopoverContent component

- src/app/[countryCode]/topLevelClientLogic.tsx
- src/components/app/pageAdvocatesHeatmap/advocateHeatmapOdometer.tsx
- src/components/app/pageHome/delayedRecentActivity.tsx
- src/components/app/pageHome/topLevelMetrics.tsx
- src/components/app/pageLeaderboard/dynamicRecentActivity.tsx
- src/components/app/pageLeaderboard/index.tsx
- src/hooks/useApiHomepageTopLevelMetrics.ts
- src/utils/web/clientAnalytics.ts
- src/utils/web/clientLocalUser.ts
- src/utils/web/getCountryCodeForClientAnalytics.ts
- src/utils/web/getCountryCodeOnClient.ts
This PR refactors the use of the getCountryCodeOnClient function to be only in analytics environments where having the default 'not-set' property is not a problem.
> refactor: limits use of `getCountryCodeOnClient` function to analytics only

- next.config.ts
closes #1977 
fixes 
Previously, all redirects from `/join/:referralId` would set a fixed `utm_medium=referral` value, causing any original utm_medium values to be lost. This change ensures accurate attribution tracking by:
1.  Capturing the original utm_medium value when present
2.  Maintaining the default referral value when no utm_medium is provided
> Allow custom utm_medium query param in the /join vanity url

- next.config.ts
closes 
fixes 
Changed the regex group name to `utmMedium` from `utm_medium`. That fixes the bug where the replaced utm_medium would end up like `utm_medium=%3Autm_medium`
> Fix utm_medium param

- src/app/(builder)/[countryCode]/partners/page.tsx
- src/app/[countryCode]/page.tsx
- src/components/app/homepageDialogDeeplinkLayout.tsx
- src/utils/server/builder/models/data/partners.ts
closes [#2003](https://github.com/Stand-With-Crypto/swc-web/issues/2003)
* Adds country code filter to the partners data model. 
* The new field has a type of tags, which allows users to select multiple country codes, so I'm using [$elemMatch](https://www.builder.io/c/docs/querying#code-elem-match-code) to filter
> feat: add country code filter on partners data model

- src/app/(builder)/[countryCode]/about/page.tsx
- src/app/(builder)/[countryCode]/advocacy-toolkit/page.tsx
- src/app/(builder)/[countryCode]/builder/test/page.tsx
- src/app/(builder)/[countryCode]/content/[[...page]]/page.tsx
- src/app/(builder)/[countryCode]/partners/page.tsx
- src/app/(builder)/[countryCode]/press/[...page]/page.tsx
- src/app/(builder)/[countryCode]/press/page.tsx
- src/app/(builder)/[countryCode]/privacy/page.tsx
- src/app/(builder)/[countryCode]/terms-of-service/page.tsx
- src/components/app/builder/builderComponent.tsx
- src/utils/server/builder/models/page/constants.ts
- src/utils/server/builder/models/page/utils/getPageContent.ts
- src/utils/server/builder/models/page/utils/getPageDetails.ts
- src/utils/server/builder/models/page/utils/getPagePaths.ts
Removed support for International Page Model and added new countryCode propriety to all Page Models
> feat: add countryCode filter to Builder.io page model

- next.config.ts
closes [#2033](https://github.com/Stand-With-Crypto/swc-web/issues/2033)
add redirects from `/manifesto` and `/mission` to `/about`
> feat: add redirects for country-specific manifesto and mission pages

- src/utils/server/getCountryCode.ts
- src/utils/server/obfuscateURLCountryCode/index.ts
closes #2009 
This PR updates the function that returns the countryCode based on the IP location to always return a countryCode.
> feat: prevents empty country code in cookie

- next.config.ts
- src/app/api/public/x-redirect/[state]/route.ts
This PR implements a direct product request to support a campaign in which they want to post a tweet that has a link that if someone clicks, redirects the user to also post the same tweet with the same link for other users. The idea is to create some sort of infinite loop where every tweet has a link for someone to post the same tweet.
> feat: creates new tweet redirect login

- src/actions/actionUpdateUserProfile.ts
- src/app/[countryCode]/internal/user-settings/userConfig.tsx
- src/app/api/inngest/route.ts
- src/bin/smokeTests/verifiedSWCPartners/userActionOptIn.ts
- src/inngest/functions/backfillIntlUsers/index.ts
- src/inngest/functions/backfillIntlUsers/logic.ts
- src/inngest/types.ts
- src/utils/shared/phoneNumber.ts
- src/validation/fields/zodPhoneNumber.ts
- src/validation/fields/zodSupportedCountryCode.ts
closes #1914 
fixes 
- Added `zodPhoneNumberWithCountryCode` to parse phone numbers from different countries
Example user backfilled from csv: Name, email, OPT_IN action and sessionId successfully added to the db
- 🗒️  ~~When intl team provides the CSVs, the`createUserDataSchema` must be updated to match the columns, or edit the CSV itself~~
- Intl team still has to provide an CSV for AU, current implementation assumes it will have the same columns as UK & CA
> Backfill users script

- src/components/app/pageHome/common/foundersCarousel.tsx
- src/utils/shared/zod/getSWCFounders.ts
Renamed founders fields to `company` and `companyUrl`
> feat: update founders data structure to include company name and URL

- src/app/[countryCode]/politicians/person/[dtsiSlug]/opengraph-image.tsx
- src/app/[countryCode]/politicians/person/[dtsiSlug]/page.tsx
- src/app/[countryCode]/politicians/person/[dtsiSlug]/twitter-image.tsx
- src/app/au/politicians/person/[dtsiSlug]/opengraph-image.tsx
- src/app/au/politicians/person/[dtsiSlug]/page.tsx
- src/app/au/politicians/person/[dtsiSlug]/twitter-image.tsx
- src/app/ca/politicians/person/[dtsiSlug]/opengraph-image.tsx
- src/app/ca/politicians/person/[dtsiSlug]/page.tsx
- src/app/ca/politicians/person/[dtsiSlug]/twitter-image.tsx
- src/app/gb/politicians/person/[dtsiSlug]/opengraph-image.tsx
- src/app/gb/politicians/person/[dtsiSlug]/page.tsx
- src/app/gb/politicians/person/[dtsiSlug]/twitter-image.tsx
- src/bin/oneTimeScripts/detectAndRemoveInvalidDTSISlugs.ts
- src/components/app/pagePoliticianDetails/common/generateOgImage.tsx
- src/data/dtsi/queries/queryDTSIAllPeopleSlugs.ts
This PR fixes the issue of builder politician detail pages that would never exist in a specific country.
> fix: politicians page static generation

- src/actions/actionCreateUserActionReferral.ts
- src/utils/server/referral/triggerReferralSteps.ts
- src/utils/server/serverLocalUser.ts
- src/utils/server/thirdweb/onLogin.ts
closes 
fixes 
- Added `searchParams` to `mapLocalUserToUserDatabaseFields`
- When a User follows a referral link, `triggerReferralSteps` detects the referral and correctly creates/increments the Referrer's REFER action, but the new User might not get properly attributed with referral acquisition parameters (acquisitionSource, acquisitionMedium, acquisitionCampaign) due to `mapLocalUserToUserDatabaseFields` only extracting the data from the `localUser` (which might not have it). 
- Bind the analytics events to the Referrer
- Currently the REFER action creation events are being incorrectly attributed to the newly created User instead of the Referrer
1. ✅ REFER actions are correctly created and attributed to right Referrer
2. ⚠️ Mixpanel events `User Action Created` for `REFER` are …
> Fix REFER action analytics

- src/components/app/pageHome/common/politiciansSection.tsx
This PR fixes an issue that the politicians homepage section would only display if we had 4 or more politicians pro or against crypto
> fix: politicians homepage section only showing for 4 or more politicians

- src/components/app/dtsiBillCard/index.tsx
- src/components/app/dtsiClientPersonDataTable/common/columns.tsx
- src/components/app/dtsiClientPersonDataTable/stanceHidden.tsx
- src/components/app/dtsiClientPersonDataTable/us/filters.ts
- src/components/app/dtsiPersonHeroCard/index.tsx
- src/components/app/dtsiStanceDetails/index.tsx
- src/components/app/dtsiStanceDetails/types.ts
- src/components/app/pagePoliticianDetails/common/scoreExplainer.tsx
- src/data/dtsi/queries/queryDTSILocationStateSpecificInformation.ts
- src/utils/dtsi/dtsiPersonUtils.ts
closes #1996
- Added hard coded array to hide politician stances
> Hide politicians stances

- src/components/app/userActionFormJoinSWC/successDialog.tsx
- src/components/app/userActionGridCTAs/components/successScreenActionCard.tsx
- src/components/app/userActionGridCTAs/types/index.ts
- src/hooks/useSuccessScreenDialogContext.ts
closes #2117 
This PR fixes an issue where after a user joins SWC, if the user clicks on any of the success dialog next actions, the page is redirected to the corresponding action url, but the success dialog stays open as it is rendered in the navbar.
The approach here was to pass the onChange prop down to the CTA card itself. I decided to use a context to prevent prop drilling inside this dialog as we would need to pass this prop down to 5/6 components to reach the CTA card itself.
> fix: join success dialog not closing after clicking on action CTA

- next.config.ts
Want to ensure that non of the international team's advertising breaks if we need to wait to merge international work.
> redirects for upcoming advertising banners

- cypress/e2e/03-page-politicians.cy.ts
- src/components/app/geoGate.test.tsx
- src/components/app/geoGate.tsx
This PR updates the GeoGate logic to also compare the user.countryCode with the access location and the page country code to decide if the user is allowed to access the content or not.
This is needed because of the following scenario: A US user is traveling to UK. Upon reaching GB, the user tries to open the SWC website (redirected to GB if the access location cookie is not set anymore). The user sign in to SWC and while being an US account, the user won't be able to complete actions in the US but would be available to complete actions in the UK.
This PR fixes that by adding user.countryCode to the comparison
> refactor: enhance GeoGate component

- src/components/app/dtsiClientPersonDataTable/au/filters.ts
- src/components/app/dtsiClientPersonDataTable/common/columns.tsx
- src/components/app/dtsiClientPersonDataTable/common/filters.tsx
- src/components/app/dtsiPersonHeroCard/dtsiPersonHeroCard.stories.tsx
- src/data/dtsi/fragments/fragmentDTSIPersonCard.ts
- src/data/dtsi/schema.graphql
- src/utils/dtsi/dtsiPersonUtils.ts
This PR does the following:
- Adds two new party filters for AU
- Displays the party name on the party column when the party category is OTHER from DTSI
> feat: display politicalAffiliation on party column when affiliation category is OTHER

- src/app/[countryCode]/config.tsx
- src/app/au/config.tsx
- src/app/ca/config.tsx
- src/app/gb/config.tsx
- src/components/app/footer/index.tsx
- src/components/app/footer/sendFeedback.tsx
- src/utils/shared/urls/externalUrls.ts
closes #2104 
This PR fixes the wrong behavior in send feedback button for desktop users that usually don't have the email client configured and were redirected to a blank page with no errors or information about what went wrong.
> fix: send feedback behavior on desktop

- docs/Access location.md
This PR adds a new edge cases section to our access location document
> docs: add edge cases for access location documentation

- src/components/app/pageHome/gb/index.tsx
- src/components/app/recentActivityRow/variantRecentActivityRow.tsx
- src/utils/shared/stateUtils.ts
> fix: update terminology from "Britons" to "Brits" in homepage section

- src/components/ui/pageSubTitle/pageSubTitle.builder.tsx
- src/utils/web/builder/components/text.builder.tsx
closes [#2005](https://github.com/Stand-With-Crypto/swc-web/issues/2005)
Adds fontSize and lineHeight inherit to PageSubTitle children so they respect the subtitle size prop.
http://swc-web-git-fix-builder-subtitle-size-coinbase-vercel.vercel.app/builder/test
> fix: Builder.io subtitle size not working on text component

- src/utils/server/nft/claimNFT.tsx
closes #2212 
fixes [PROD-SWC-WEB-63H](https://stand-with-crypto.sentry.io/issues/6535682712/events/a4c14bbcf2504ed2b53f614204c379ab/)
- Added checks for `nftSlug` and `NFT_SLUG_BACKEND_METADATA`
- Added NFT for the VOTER_ATTESTATION `H1_2025` campaign
> Fix missing NFT definition for VOTER_ATTESTATION action type

- src/actions/actionCreateUserActionEmailCongressperson.ts
- src/components/app/clientCurrentUserDTSIPersonCardOrCTA.tsx
- src/components/app/dtsiPersonHeroCard/dtsiPersonHeroCardRow.tsx
- src/components/app/dtsiPersonHeroCard/index.tsx
- src/data/dtsi/queries/queryDTSIPeopleByCongressionalDistrict.ts
- src/hooks/useGetDTSIPeopleFromAddress.ts
- src/utils/shared/orderSenatorsByImportanceForOutreach.ts
- src/utils/shared/yourPoliticianCategory.ts
closes #2231
fixes 
- Added `GOVERNOR` and `ATTORNEY_GENERAL` categories to `PeopleByUSCongressionalDistrict` query
- Clean up `PeopleByUSCongressionalDistrict` styles to better fit politician name
> Show governor and attorney in politicians section

- src/components/app/userActionGridCTAs/constants/au/auCtas.tsx
This PR fixes the key races australia CTA that was redirecting the user to the email flow instead of the races page.
> fix: key races CTA redirecting to email flow

- src/components/app/userActionFormCallCongressperson/sections/suggestedScript.tsx
- src/utils/shared/googleCivicInfo.ts
closes Stand-With-Crypto/swc-internal#368 
Changed the endpoint we're using to access the divisions information based on [this comment](https://groups.google.com/g/google-civicinfo-api/c/9fwFn-dhktA)
> fix: change representatives endpoint to divisions

- src/app/ca/config.tsx
- src/components/app/userActionGridCTAs/constants/ca/caCtas.tsx
closes #2249 
This PR removes the key races action in Canada and also removes the Key Races link in Canada's navbar.
> chore: disable key races action in Canada

- src/components/app/dtsiClientPersonDataTable/common/filters.tsx
closes #2242
This PR removes a temporary "fix" that caused politicians filters to not work on mobile at all.
> fix: politicians filters select component not working on mobile

- src/app/au/config.tsx
- src/components/app/userActionGridCTAs/constants/au/auCtas.tsx
closes #2258 
- Disables the view key races in Australia actions
- Removed `races` from AU navbar
> chore: disables view key races in Australia

- src/inngest/functions/districtsRankings/updateRankings.ts
- src/utils/server/districtRankings/getRankingData.ts
closes #2243
fixes [PROD-SWC-WEB-5Z9](https://stand-with-crypto.sentry.io/issues/6369092866/events/a7304a87e0244dc594a46185032265d2/)
**Problem:**
The queries fetching advocate and referral counts by district were extremely slow, taking ~140 seconds to finish and sometimes hitting the 3 minutes limit for edge functions. Initial attempts to optimize the single SQL query through indexing, join order hints, and clause simplification failed to significantly improve performance due to the large data volume involved in joins and aggregations.
**Solution:**
Refactored the data fetching approach to run queries in parallel on a per-state basis:
1.  Modified `getAdvocatesCountByDistrict` and `getReferralsCountByDistrict` to accept a `stateCode` and query data only for that specific state.
2. …
> Optimize district ranking job performance

- src/utils/web/googlePlaceUtils.ts
closes #1489 
fixes PROD-SWC-WEB-SE
The issue "Unexpected error type passed to catchUnexpectedServerErrorAndTriggerToast" was fixed.
Previously, the `getAddressWithRetry` function was rethrowing error strings directly from `use-places-autocomplete` without converting them to `Error` instances. This caused an issue because `catchUnexpectedServerErrorAndTriggerToast` expects an `Error`, not a string.
The `getAddressWithRetry` function now converts any error strings to `Error` instances before rethrowing. This ensures `catchUnexpectedServerErrorAndTriggerToast` receives errors in the expected format.
> fix: fix trigger toast error

- src/components/app/recentActivityRow/recentActivityRow.tsx
Restores datetime in community feed for AU and CA
> Feat: show datetime in CA and AU community feed

- src/utils/server/sms/actions.ts
- src/utils/server/sms/messages.ts
fixes [PROD-SWC-WEB-4DP](https://stand-with-crypto.sentry.io/issues/5682999612/events/4fb88413b95a47909a9853eaeda954ad/)
> fix: only send opt-out custom message for countries with shot-code phone number

- src/utils/server/getUserAccessLocationCookie.ts
fixes [PROD-SWC-WEB-63V](https://stand-with-crypto.sentry.io/issues/6537023319/events/15879378e8284af185b11b0f9f91de78/)
> fix: allow mx to pass user access location validation for border cases

- src/utils/server/getGooglePlaceIdFromAddress.ts
closes #2282 
fixes #2282 
This PR migrates the google places autocomplete api from legacy to the new API to stop triggering alerts in Sentry
Migration was done based on these docs: 
- https://developers.google.com/maps/documentation/places/web-service/legacy/migrate-autocomplete
- https://developers.google.com/maps/documentation/places/web-service/place-details
- https://developers.google.com/maps/documentation/places/web-service/legacy/autocomplete
> feat: migrate google.maps.places.PlacesService to the new google.maps.places.Place API

- sentry.client.config.ts
This PR changes how we ignore the google maps api warning from being sent to sentry
> Update Sentry configuration to use regex for Google Maps Autocomplete Service deprecation warning

- sentry.client.config.ts
This PR makes the ignore regex more generic to catch autocomplete and place errors
> chore: makes google places error ignore regex more generic

- src/components/app/layout/layoutScripts/au/index.tsx
fixes #2283 
This PR tries to fix the `ReferenceError: twq is not defined` by adding the necessary twitter analytics script and adding a check before using `twq`
> fix: Twitter event tracking in AuLayoutScript component

- src/utils/server/email/utils/parseEventsWebhookRequest.ts
> Fix isMarketingEmail check failing when event originates from a test marketing email

- prisma/schema.prisma
closes 
fixes [PROD-SWC-WEB-5YK](https://stand-with-crypto.sentry.io/issues/6354564012/events/4605e9c0a4604eb689d216f32567bc4b/)
The query used a large IN clause to fetch user actions, which was inefficient without a proper database index. The fix was to add a new composite index to the user_action table on `(action_type, nft_mint_id, datetime_created)`. This allows the database to efficiently find the required records without performing a full table scan. 
Query profiling results:
Before
After
https://app.planetscale.com/stand-with-crypto/swc-web/deploy-requests/125
> Fix backfillNFT slow db query

- sentry.client.config.ts
closes #2408
This PR adds a new ignore entry on Sentry for network errors. Investigation and decision is detailed in this [issue](https://github.com/Stand-With-Crypto/swc-web/issues/2408)
> chore: adds network error to ignore array

- src/utils/shared/phoneNumber.ts
These changes will improve how we log these errors: https://stand-with-crypto.sentry.io/issues/?project=4506490717470720&query=domain%3AparsePhoneNumberWithError&referrer=issue-list&statsPeriod=30d
> fix: improve Sentry error logging for phone number parsing failures

- src/components/app/pageHome/ca/index.tsx
- src/components/app/pagePress/NewsList.tsx
> fix: press description alignment & wrong founders country on Canada homepage

- src/components/app/sms/smsOptInConsentText.tsx
closes 
fixes 
Updated all references of "Stand With Crypto International Ltd" to "SWC International Ltd" in SMS opt-in consent text for GB, CA, and AU country codes. This aligns with the updated branding guidelines.
The change affects:
- SMS consent text displayed to users in Great Britain, Canada, and Australia when opting into text messages
- Three instances in `src/components/app/sms/smsOptInConsentText.tsx`
This is a simple branding update that changes the legal entity name displayed in user-facing SMS consent text. The functionality remains unchanged.
> feat: update branding from 'Stand With Crypto International Ltd' to 'SWC International Ltd'

- sentry.client.config.ts
Added 'Could not assign Magic Eden provider' to the COMMON_ERROR_MESSAGES_TO_GROUP array in sentry.client.config.ts to group these similar errors together in Sentry reporting. This will help reduce noise and make it easier to track this specific error pattern.
This change follows the existing pattern of grouping common error messages that occur frequently and should be consolidated for better error monitoring.
This is a simple addition to the error grouping list - no functional changes or testing required beyond the existing Sentry configuration.
The change only affects error grouping in Sentry and doesn't require additional testing beyond verification that the configuration is syntactically correct.
> fix(sentry): group Magic Eden provider assignment errors

- .cursor/rules/create-new-email-action-campaign.mdc
- src/components/app/userActionFormEmailCongressperson/au/campaigns/1-default.tsx
- src/components/app/userActionFormEmailCongressperson/au/campaigns/20240611-newmode-debanking.tsx
- src/components/app/userActionFormEmailCongressperson/au/campaigns/20240611-q2-2025-election.tsx
- src/components/app/userActionFormEmailCongressperson/au/campaigns/index.ts
- src/components/app/userActionFormEmailCongressperson/au/index.tsx
- src/components/app/userActionFormEmailCongressperson/ca/index.tsx
- src/components/app/userActionFormEmailCongressperson/common/useEmailActionCampaignMetadata.ts
- src/components/app/userActionFormEmailCongressperson/gb/index.tsx
- src/components/app/userActionFormEmailCongressperson/us/index.tsx
- src/components/app/userActionGridCTAs/constants/au/auCtas.tsx
- src/utils/shared/userActionCampaigns/au/auUserActionCampaigns.ts
This PR implements changes to address [swc-internal#409](https://github.com/Stand-With-Crypto/swc-internal/issues/409).
closes swc-internal#409
- AI Generated
> feat(au-email): add and activate two new AU email campaigns

- src/hooks/useGetDTSIPeopleFromAddress.ts
This PR adds proper error handling to the `getDTSIPeopleFromAddress` function by adding an early return when `notFoundReason` is present in the response data.
- Added a check for `notFoundReason` in the response data
- Return early if `notFoundReason` is present to prevent processing invalid data as `DTSIPeopleByElectoralZoneQueryResult`
Without this check, the function would attempt to process error responses as valid DTSI people data, which could lead to runtime errors or unexpected behavior.
> fix: add early return for notFoundReason in getDTSIPeopleFromAddress

- src/utils/server/externalOptIn/handleExternalUserActionOptIn.ts
- src/utils/server/getAddressFromGooglePlacePrediction.ts
closes 
fixes 
The `addressComponents` returned from the Google Places API is different from the one returned from the client Google Maps API.
- Updated the `AddressComponent` type for the server.
- `handleExternalUserActionOptIn` now only overwrites an address field with google places data if it exists.
> Fix addressComponents type

- src/components/app/dtsiClientPersonDataTable/au/index.tsx
- src/components/app/dtsiClientPersonDataTable/ca/index.tsx
- src/components/app/dtsiClientPersonDataTable/common/filters.tsx
- src/components/app/dtsiClientPersonDataTable/common/table.tsx
- src/components/app/dtsiClientPersonDataTable/common/useTableFilters.ts
- src/components/app/dtsiClientPersonDataTable/gb/index.tsx
- src/components/app/dtsiClientPersonDataTable/us/index.tsx
- src/hooks/useMultipleSearchParamState.ts
closes #581 
- Added a “Reset Filters” button to the Politician page filters section.
- This button allows users to quickly clear all selected filters with a single click, instead of manually resetting each filter one by one.
> feat: add reset filters functionality to global filters component

- src/inngest/functions/backfillAddressFieldsWithGooglePlaces/config.ts
- src/inngest/functions/backfillAddressFieldsWithGooglePlaces/logic.ts
> fix: use Promise.allSettled to update backfilled addresses

- src/components/app/dtsiStanceDetails/dtsiStanceDetailsTweet.tsx
- src/components/app/pagePoliticianDetails/common/politiciansDetails.tsx
Added an overflow control class to do not overflow elements in mobile screens.
> fix: add overflow handling to notable statements section in politician details page

- src/app/api/verified-swc-partner/user-action-opt-in/getNumberFormat.ts
- src/app/api/verified-swc-partner/user-action-opt-in/route.ts
closes #2513 
Added getNumberFormat utility for phone number formatting for investigate better the validations failing.
> feat: add getNumberFormat utility for phone number formatting

- src/components/app/userActionGridCTAs/components/campaignsCheckmarks.tsx
- src/components/app/userActionGridCTAs/components/userActionCard.tsx
- src/components/app/userActionGridCTAs/constants/au/auCtas.tsx
- src/components/app/userActionGridCTAs/constants/ca/caCtas.tsx
- src/components/app/userActionGridCTAs/constants/gb/gbCtas.tsx
- src/components/app/userActionGridCTAs/constants/us/usCtas.tsx
- src/components/app/userActionGridCTAs/index.tsx
This PR adds new styles to call-to-action cards on homepage (a.k.a UserActionCard)
Here are some visual evidencies:
<details>
<summary>
Visual reference (design)
</summary>
**Desktop**
**Mobile**
</details>
Description | Before | After
--- | --- | ---
Desktop card | <img width="278" height="474" alt="image" src="https://github.com/user-attachments/assets/1ed0d9fc-b4a2-485d-894b-3c5f93ba039f" />  | <img width="374" height="452" alt="image" src="https://github.com/user-attachments/assets/4277da01-e666-4920-b459-79d596e60296" />
Mobile card | <img width="401" height="187" alt="image" src="https://github.com/user-attachments/assets/c2079a62-d35d-4235-a47d-3b1770127844" /> | <img width="404" height="177" alt="image" src="https://github.com/user-attachments/assets/14617a2c-dae7-4e37-aee1-93c4e1d …
> feat: enhance action tiles styling

- src/components/app/userActionGridCTAs/skeleton.tsx
fixes #2559 
**Description**
When the profile page was loading, the grid had 4 columns. With the card/layout update, it's expected to have 3.
**Solution**
Instead of showing 4 cols on the skeleton, it shows 3.
> fix: update UserActionGridCTAsSkeleton layout and styling

- docs/api/swagger-recent-activity-by-date.yaml
- src/app/api/public/recent-activity/by-date/[...config]/route.ts
- src/data/recentActivity/getPublicRecentActivityByDateRange.ts
closes #2548 
This creates a new recent activity api route for external third party integrations.
Because this needs to support products other than ours I'm accepting the redundancy in implementation with the current recent activity route to reduce side effects with data changes on the api without prior warning (adding a new action for instance)
> feat: add recent activity by date range endpoint

- .cursor/rules/adding-custom-fields-to-sendgrid.mdc
- src/inngest/functions/sendgridContactsCronJob/checkCustomFields.ts
- src/inngest/functions/sendgridContactsCronJob/config.ts
- src/inngest/functions/sendgridContactsCronJob/logic.ts
- src/utils/server/sendgrid/marketing/constants.ts
Added acquisition tracking custom fields to SendGrid contacts synchronization to capture user acquisition data:
- Added `acquisitionSource`, `acquisitionMedium`, `acquisitionCampaign`, and `acquisitionReferer` fields to the user query and contact mapping
- Increased SendGrid API rate limit cooldown from 30 seconds to 1 minute for better API stability
The main changes are in:
- `src/inngest/functions/sendgridContactsCronJob/logic.ts` - Added acquisition fields to user query and contact conversion
- `src/utils/server/sendgrid/marketing/constants.ts` - Added new custom field constants
- `src/inngest/functions/sendgridContactsCronJob/config.ts` - Increased rate limit cooldown
> feat: add acquisition tracking custom fields to SendGrid contacts

- src/components/app/userActionFormEmailCongressperson/us/campaigns/20250814-day-of-action.tsx
- src/components/app/userActionFormEmailCongressperson/us/campaigns/index.ts
- src/utils/shared/userActionCampaigns/us/usUserActionCampaigns.ts
This PR adds the email campaign for day of action (aug 14).
> feat: add new email campaign for Crypto Day of Action

- src/app/au/referrals/[[...page]]/page.tsx
- src/app/ca/referrals/[[...page]]/page.tsx
- src/components/app/pageCommunity/au/index.tsx
- src/components/app/pageCommunity/ca/index.tsx
- src/components/app/pageCommunity/us/index.tsx
- src/components/app/pageCommunity/us/stateSpecificPage.tsx
- src/components/app/pageHome/au/index.tsx
- src/components/app/pageHome/ca/index.tsx
- src/components/app/pageHome/us/index.tsx
- src/components/app/pageLocalPolicy/us/statePage/districtLeaderboardSection.tsx
- src/components/app/pageReferrals/au/heading.tsx
- src/components/app/pageReferrals/au/index.tsx
- src/components/app/pageReferrals/au/leaderboard.tsx
- src/components/app/pageReferrals/au/yourDivisionRanking.tsx
- src/components/app/pageReferrals/ca/heading.tsx
- src/components/app/pageReferrals/ca/index.tsx
- src/components/app/pageReferrals/ca/leaderboard.tsx
- src/components/app/pageReferrals/ca/yourConstituencyRanking.tsx
- src/components/app/pageReferrals/common/defaultPlacesSelect.tsx
- src/components/app/pageReferrals/common/heading.tsx
- src/components/app/pageReferrals/common/leaderboard/index.tsx
- src/components/app/pageReferrals/common/userAddress.context.tsx
- src/components/app/pageReferrals/common/yourLocationRanking.tsx
- src/components/app/pageReferrals/us/heading.tsx
- src/components/app/pageReferrals/us/index.tsx
- src/components/app/pageReferrals/us/leaderboard.tsx
- src/components/app/pageReferrals/us/yourDistrictRanking.tsx
- src/components/app/pageUserProfile/common/userReferralUrl.tsx
closes #2557 
Unfortunately, it is not possible to fix entirely the layout shift without a re-design on this page, because the user session can only be validated on client-side, which means when the page is hydrated, the signed in session will pop.
**Even so**, the UX can be improved and the shift can be less harmful. The strategy used is to:
- Add a loading skeleton to the referral link (that just appeared out of nowhere before)
- Fixed the select size to remove completely the flick on the skeleton > component transition
Now, everything pops at the exact same time to the screen, which means the sensation of shaking is not felt anymore. The screen flicks once, then stops.
**Key wins**
* Zeroed the layout shift in the signed-off screen (most of the cases) - this case used to be a small …
> Fix/refactor: reduce layout shift on referrals and improve code

- src/data/dtsi/queries/queryDTSIPeopleBySlugForUserActions.ts
- src/data/recentActivity/getPublicRecentActivityByDateRange.ts
This PR implements changes to address #2595.
- Changed query to get person in DTSI changing limit to `1000`, because the limit on SWC DB side is `1000` and we need to reach same limit to get all person's from DTSI API.
> Fixing recent activity by date limit in dtsi query

- src/app/gb/community/referrals/[[...page]]/page.tsx
- src/app/gb/config.tsx
- src/app/gb/page.tsx
- src/components/app/homepageDialogDeeplinkLayout/gb/index.tsx
- src/components/app/pageCommunity/gb/index.tsx
- src/components/app/pageHome/gb/index.tsx
closes #2511 
* Added constituencies rankings to the homepage.
* Added constituencies rankings to community page.
* Added link to the referrals page.
> feat: add links to advocates rankings on GB

- src/components/app/pagePoliticianDetails/common/generateOgImage.tsx
This PR addresses OpenGraph image generation failures when politician profile pictures use unsupported formats by Next.js ImageResponse API.
[Vercel error Log](https://vercel.com/coinbase-vercel/swc-web/logs?levels=error&selectedLogId=pplcb-1756330802087-d7ba95fa4227)
- Added image format validation to detect unsupported formats (WebP) before passing to ImageResponse
- Skip profile pictures with unsupported formats to prevent OpenGraph generation failures
- Maintains fallback to placeholder image when format is not supported, ensuring consistent behavior
> fix(og-image): add support for WebP profile pictures in OpenGraph generation

- src/utils/server/builder/models/data/bills.ts
- src/utils/server/builder/models/data/events.ts
- src/utils/server/builder/models/data/founders.ts
- src/utils/server/builder/models/data/news.ts
- src/utils/server/builder/models/data/partners.ts
- src/utils/server/builder/models/data/petitions.ts
- src/utils/server/builder/models/data/polls.ts
- src/utils/server/builder/models/data/questionnaire.ts
- src/utils/server/builder/models/page/utils/getPageContent.ts
- src/utils/server/builder/models/page/utils/getPageDetails.ts
- src/utils/server/builder/models/page/utils/getPagePaths.ts
If we add localization on builder.io and don't pass the locale param on the request, instead of the field content, we're going to receive an object with the localized values, which is not the expected behavior and must break a lot of things on our side.
To prevent this from happening, we should add the 'locale' param on all the builder.io requests to data models.
> feat: add locale to all builder.io data model requests

- src/inngest/functions/importUsersByCSV/index.ts
Reduces batch size constant from `250` to `150` in the `importUsersByCSV` function.
fixes PROD-SWC-WEB-DBG
> fix: reduce batch size for CSV user import from 250 to 150

- src/components/app/dtsiCongresspersonDisplay.tsx
closes #2754
This PR fixes an error occurring on the call action about the GOVERNOR role not being mapped to a string on the formatDTSICategory function.
> feat: extend formatDTSICategory function to include additional political roles

- src/components/app/recentActivityRow/variantRecentActivityRow.tsx
- src/components/app/userActionFormPetitionSignature/index.tsx
- src/utils/server/i18n/getServerTranslation.ts
- src/utils/server/i18n/getStaticTranslation.ts
- src/utils/shared/i18n/commons.ts
- src/utils/shared/i18n/createI18nMessages.test.ts
- src/utils/shared/i18n/createI18nMessages.ts
- src/utils/shared/i18n/createTranslator.ts
- src/utils/shared/i18n/mergeI18nMessages.test.ts
- src/utils/shared/i18n/mergeI18nMessages.ts
- src/utils/shared/i18n/types.ts
- src/utils/web/i18n/useTranslation.ts
- src/validation/fields/zodGooglePlacesAutocompletePrediction.ts
- src/validation/forms/zodUserActionFormPetitionSignature.ts
- Updated translation functions to use type-safe keys, ensuring that translation keys are validated at compile time.
- Modified components to accept more specific types for translation functions, improving overall type safety and reducing runtime errors.
- Refactored i18n message creation and merging functions to enforce consistent structure and type safety across different languages and countries.
- Improved documentation for translation utilities to clarify usage and examples.
> feature: enhance type safety on translations

- src/components/ui/combobox.tsx
- src/components/ui/googlePlacesSelect/index.tsx
closes #2727 
- Added translations to address picker input
> feature: add translations to address input
